BEGIN;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE tenants (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE users (id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), email citext NOT NULL, name text NOT NULL, role text NOT NULL, active boolean NOT NULL DEFAULT true, password_hash text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, UNIQUE(tenant_id,email));
CREATE TABLE practices (id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), account_number text NOT NULL, practice_name text NOT NULL, status text NOT NULL CHECK(status IN ('active','inactive')), phone text NOT NULL, email text NOT NULL, address text NOT NULL, city text NOT NULL, state text NOT NULL, postal_code text NOT NULL, tax_exempt boolean NOT NULL DEFAULT false, scanner_type text NOT NULL DEFAULT '', office_manager jsonb NOT NULL DEFAULT '{}'::jsonb, notes text NOT NULL DEFAULT '', communication_history jsonb NOT NULL DEFAULT '[]'::jsonb, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, UNIQUE(tenant_id,account_number));
CREATE TABLE doctors (id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), practice_id uuid NOT NULL REFERENCES practices(id), first_name text NOT NULL, last_name text NOT NULL, specialty text NOT NULL DEFAULT '', email text NOT NULL, phone text NOT NULL DEFAULT '', status text NOT NULL CHECK(status IN ('active','inactive')), notes text NOT NULL DEFAULT '', communication_history jsonb NOT NULL DEFAULT '[]'::jsonb, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz);
CREATE TABLE patients (id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), practice_id uuid NOT NULL REFERENCES practices(id), doctor_id uuid NOT NULL REFERENCES doctors(id), patient_reference text NOT NULL, first_name text NOT NULL, last_name text NOT NULL, date_of_birth date, status text NOT NULL CHECK(status IN ('active','inactive')), notes text NOT NULL DEFAULT '', created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, UNIQUE(tenant_id,practice_id,patient_reference));
CREATE TABLE clinical_cases (id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), case_number text NOT NULL, patient_id uuid NOT NULL REFERENCES patients(id), practice_id uuid NOT NULL REFERENCES practices(id), doctor_id uuid NOT NULL REFERENCES doctors(id), status text NOT NULL, tooth_numbers integer[] NOT NULL DEFAULT '{}', arch text NOT NULL, restoration text NOT NULL, material text NOT NULL, shade text NOT NULL, stump_shade text NOT NULL DEFAULT '', rush_priority text NOT NULL, received_date date NOT NULL, due_date date NOT NULL, prescription_notes text NOT NULL DEFAULT '', created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, UNIQUE(tenant_id,case_number));
CREATE TABLE production_work_items (id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), case_id uuid NOT NULL UNIQUE REFERENCES clinical_cases(id), case_number text NOT NULL, route text[] NOT NULL, current_department text NOT NULL, status text NOT NULL, technician_id text, started_at timestamptz, completed_at timestamptz, sla_due_at timestamptz NOT NULL, history jsonb NOT NULL DEFAULT '[]'::jsonb, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz);
CREATE TABLE qc_templates (id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), name text NOT NULL, restoration_types text[] NOT NULL, status text NOT NULL, checklist_items jsonb NOT NULL, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz);
CREATE TABLE qc_inspections (id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), case_id uuid NOT NULL REFERENCES clinical_cases(id), case_number text NOT NULL, template_id uuid NOT NULL REFERENCES qc_templates(id), restoration_type text NOT NULL, outcome text NOT NULL, checklist jsonb NOT NULL, defects jsonb NOT NULL, inspector_id text NOT NULL, inspector_name text NOT NULL, signed_at timestamptz NOT NULL, notes text NOT NULL DEFAULT '', history jsonb NOT NULL DEFAULT '[]'::jsonb, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL);
CREATE TABLE shipments (id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), shipment_number text NOT NULL, barcode_value text NOT NULL, status text NOT NULL, courier text NOT NULL, courier_name text NOT NULL DEFAULT '', tracking_number text NOT NULL DEFAULT '', pickup_scheduled_at timestamptz, shipped_at timestamptz, delivered_at timestamptz, packing_checklist jsonb NOT NULL, notes text NOT NULL DEFAULT '', history jsonb NOT NULL DEFAULT '[]'::jsonb, created_by text NOT NULL, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, UNIQUE(tenant_id,shipment_number), UNIQUE(tenant_id,tracking_number));
CREATE TABLE shipment_cases (shipment_id uuid NOT NULL REFERENCES shipments(id) ON DELETE CASCADE, case_id uuid NOT NULL REFERENCES clinical_cases(id), PRIMARY KEY(shipment_id,case_id));
CREATE TABLE invoices (id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), invoice_number text NOT NULL, practice_id uuid NOT NULL REFERENCES practices(id), practice_name text NOT NULL, status text NOT NULL, terms text NOT NULL, issued_at timestamptz NOT NULL, due_at timestamptz NOT NULL, subtotal numeric(14,2) NOT NULL, discount_total numeric(14,2) NOT NULL, adjustment_total numeric(14,2) NOT NULL, taxable_amount numeric(14,2) NOT NULL, tax_rate numeric(8,6) NOT NULL, tax_amount numeric(14,2) NOT NULL, total numeric(14,2) NOT NULL, amount_paid numeric(14,2) NOT NULL, balance numeric(14,2) NOT NULL, notes text NOT NULL DEFAULT '', created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, UNIQUE(tenant_id,invoice_number));
CREATE TABLE invoice_shipments (invoice_id uuid NOT NULL REFERENCES invoices(id) ON DELETE CASCADE, shipment_id uuid NOT NULL REFERENCES shipments(id), PRIMARY KEY(invoice_id,shipment_id), UNIQUE(shipment_id));
CREATE TABLE invoice_lines (id uuid PRIMARY KEY, invoice_id uuid NOT NULL REFERENCES invoices(id) ON DELETE CASCADE, case_id uuid NOT NULL REFERENCES clinical_cases(id), case_number text NOT NULL, description text NOT NULL, quantity numeric(10,2) NOT NULL, unit_price numeric(14,2) NOT NULL, amount numeric(14,2) NOT NULL);
CREATE TABLE invoice_adjustments (id uuid PRIMARY KEY, invoice_id uuid NOT NULL REFERENCES invoices(id) ON DELETE CASCADE, type text NOT NULL, description text NOT NULL, amount numeric(14,2) NOT NULL, created_by text NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE payments (id uuid PRIMARY KEY, invoice_id uuid NOT NULL REFERENCES invoices(id), amount numeric(14,2) NOT NULL CHECK(amount>0), method text NOT NULL, reference text NOT NULL DEFAULT '', received_at timestamptz NOT NULL, recorded_by text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE monthly_statements (id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), statement_number text NOT NULL, practice_id uuid NOT NULL REFERENCES practices(id), practice_name text NOT NULL, period char(7) NOT NULL, generated_at timestamptz NOT NULL, invoice_ids uuid[] NOT NULL, opening_balance numeric(14,2) NOT NULL, charges numeric(14,2) NOT NULL, payments numeric(14,2) NOT NULL, closing_balance numeric(14,2) NOT NULL, aging jsonb NOT NULL, UNIQUE(tenant_id,statement_number));
CREATE TABLE object_records (id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), owner_type text NOT NULL, owner_id uuid NOT NULL, kind text NOT NULL, provider text NOT NULL, bucket text NOT NULL, object_key text NOT NULL, file_name text NOT NULL, mime_type text NOT NULL, size_bytes bigint NOT NULL CHECK(size_bytes>=0), checksum_sha256 text NOT NULL, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, UNIQUE(provider,bucket,object_key));
CREATE TABLE audit_events (id bigserial PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), actor_id text NOT NULL, actor_name text NOT NULL, action text NOT NULL, entity_type text NOT NULL, entity_id text NOT NULL, occurred_at timestamptz NOT NULL, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());

CREATE INDEX idx_doctors_practice ON doctors(tenant_id,practice_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_patients_practice_doctor ON patients(tenant_id,practice_id,doctor_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_cases_status_due ON clinical_cases(tenant_id,status,due_date) WHERE deleted_at IS NULL;
CREATE INDEX idx_production_queue ON production_work_items(tenant_id,current_department,status,sla_due_at) WHERE deleted_at IS NULL;
CREATE INDEX idx_qc_case_outcome ON qc_inspections(tenant_id,case_id,outcome,signed_at DESC);
CREATE INDEX idx_shipments_status ON shipments(tenant_id,status,updated_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_invoices_practice_due ON invoices(tenant_id,practice_id,status,due_at) WHERE deleted_at IS NULL;
CREATE INDEX idx_audit_entity ON audit_events(tenant_id,entity_type,entity_id,occurred_at DESC);
CREATE INDEX idx_objects_owner ON object_records(tenant_id,owner_type,owner_id) WHERE deleted_at IS NULL;

CREATE OR REPLACE FUNCTION prevent_audit_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'audit_events are immutable'; END $$;
CREATE TRIGGER audit_events_no_update BEFORE UPDATE OR DELETE ON audit_events FOR EACH ROW EXECUTE FUNCTION prevent_audit_mutation();
COMMIT;
