BEGIN;
DROP TRIGGER IF EXISTS case_operational_events_immutable ON case_operational_events;
DROP FUNCTION IF EXISTS prevent_case_operational_event_mutation();
DROP TRIGGER IF EXISTS case_files_source_guard ON case_files;
DROP FUNCTION IF EXISTS prevent_case_file_source_mutation();
DROP TABLE IF EXISTS case_operational_events;
DROP TABLE IF EXISTS vendor_case_package_files;
DROP TABLE IF EXISTS vendor_case_package_product_lines;
DROP TABLE IF EXISTS vendor_case_packages;
DROP TABLE IF EXISTS case_product_line_fulfillment;
DROP TABLE IF EXISTS case_file_product_line_links;
DROP TABLE IF EXISTS case_files;
DROP TABLE IF EXISTS case_cancellations;
DROP TABLE IF EXISTS case_hold_events;
DROP TABLE IF EXISTS tenant_case_cancellation_reasons;
DROP TABLE IF EXISTS tenant_case_hold_reasons;
DROP TABLE IF EXISTS case_intake_profiles;
ALTER TABLE object_records DROP CONSTRAINT IF EXISTS object_records_tenant_id_unique;
COMMIT;
