import { createHash, randomBytes, randomUUID, timingSafeEqual } from 'node:crypto';
import { CommercialAccessError, type ActivationCredential, type CommercialActor } from './commercial-entitlements.js';
import type { AuditEventInput, RepositoryRegistry } from './contracts.js';
import type { LaboratoryTenant } from './tenant-native.js';

const defaultCredentialLifetimeMs=7*24*60*60*1000;
const secretHash=(value:string)=>createHash('sha256').update(value).digest('hex');
const secretEquals=(expected:string,value:string)=>timingSafeEqual(Buffer.from(expected,'hex'),Buffer.from(secretHash(value),'hex'));
const publicCredential=(value:ActivationCredential)=>({id:value.id,tenantId:value.tenantId,issuedBy:value.issuedBy,issuedAt:value.issuedAt,expiresAt:value.expiresAt,activatedAt:value.activatedAt,activatedBy:value.activatedBy,revokedAt:value.revokedAt,revokedBy:value.revokedBy,revocationReason:value.revocationReason,supersedesCredentialId:value.supersedesCredentialId,replacedByCredentialId:value.replacedByCredentialId,metadata:value.metadata});

export class CommercialLicensingService {
  constructor(readonly repositories:RepositoryRegistry){}
  private async audit(repositories:RepositoryRegistry,tenantId:string,actor:CommercialActor,action:string,entityId:string,previousState:unknown,newState:unknown,reason?:string){await repositories.audit.append({tenantId,actorId:actor.actorId,actorName:actor.actorName,action,entityType:'commercial-licensing',entityId,occurredAt:new Date().toISOString(),metadata:{previousState,newState,...(reason?{reason}:{})}} satisfies AuditEventInput);}
  private async platform(repositories:RepositoryRegistry,actor:CommercialActor,tenantId:string){if(actor.platformRole==='platform-admin')return;await this.audit(repositories,tenantId,actor,'commercial.control.rejected','commercial-control',null,{denied:true},'platform-admin-required');throw new CommercialAccessError(403,'Platform commercial administration is required.');}
  private async tenant(repositories:RepositoryRegistry,tenantId:string){const value=await repositories.tenants.get(tenantId);if(!value)throw new CommercialAccessError(404,'Laboratory tenant was not found.');return value;}
  private updated(value:LaboratoryTenant,change:Partial<Pick<LaboratoryTenant,'status'|'activationState'|'commercialActivatedAt'|'commercialSuspendedAt'|'commercialCancelledAt'>>):LaboratoryTenant{return {...value,...change,auditMetadata:{...value.auditMetadata,commercialLifecycleUpdatedAt:new Date().toISOString()}};}
  private credential(tenantId:string){const id=randomUUID(),secret=randomBytes(32).toString('base64url');return {id,raw:`act_${id}.${secret}`,hash:secretHash(`act_${id}.${secret}`),tenantId};}
  private expiry(value:string|undefined){if(!value)return new Date(Date.now()+defaultCredentialLifetimeMs).toISOString();const date=new Date(value);if(Number.isNaN(date.valueOf())||date<=new Date())throw new CommercialAccessError(400,'Activation credential expiry must be in the future.');return date.toISOString();}

  async provision(actor:CommercialActor,input:{name:string;commercialAccountReference:string}){return this.repositories.transaction(async repositories=>{await this.platform(repositories,actor,'00000000-0000-0000-0000-000000000001');if(!input.name.trim()||!input.commercialAccountReference.trim())throw new CommercialAccessError(400,'Laboratory name and commercial account reference are required.');const id=randomUUID();const value={id,name:input.name.trim(),status:'TRIAL' as const,activationState:'PENDING' as const,commercialAccountReference:input.commercialAccountReference.trim(),commercialActivatedAt:null,commercialSuspendedAt:null,commercialCancelledAt:null,auditMetadata:{provisionedBy:actor.actorId,commercialControlPlane:true}};await repositories.tenants.create(value);const tenant=await this.tenant(repositories,id);await this.audit(repositories,id,actor,'commercial.tenant.provisioned',id,null,tenant);return tenant;});}
  async inspect(actor:CommercialActor,tenantId:string){return this.repositories.transaction(async repositories=>{await this.platform(repositories,actor,tenantId);const tenant=await this.tenant(repositories,tenantId);return {tenant,credentials:(await repositories.commercial.listActivationCredentials(tenantId)).map(publicCredential)};});}
  async issue(actor:CommercialActor,tenantId:string,input:{expiresAt?:string;reason?:string}={}){return this.repositories.transaction(async repositories=>{await this.platform(repositories,actor,tenantId);const tenant=await this.tenant(repositories,tenantId);if(tenant.status==='CANCELLED')throw new CommercialAccessError(409,'Cancelled laboratory cannot receive activation credentials.');const prior=(await repositories.commercial.listActivationCredentials(tenantId)).find(value=>!value.revokedAt&&!value.activatedAt&&new Date(value.expiresAt)>new Date());if(prior)await repositories.commercial.revokeActivationCredential(prior.id,actor.actorId,'superseded-by-new-issuance');const generated=this.credential(tenantId);const next=await repositories.commercial.createActivationCredential({id:generated.id,tenantId,secretHash:generated.hash,issuedBy:actor.actorId,expiresAt:this.expiry(input.expiresAt),supersedesCredentialId:prior?.id??null,metadata:{...(input.reason?{reason:input.reason}:{}),algorithm:'sha256-random-256'}});if(prior)await repositories.commercial.revokeActivationCredential(prior.id,actor.actorId,'superseded-by-new-issuance',next.id);await this.audit(repositories,tenantId,actor,'commercial.activation.credential-issued',next.id,null,publicCredential(next),input.reason);return {credential:generated.raw,record:publicCredential(next)};});}
  async activate(actor:CommercialActor,tenantId:string,rawCredential:string){return this.repositories.transaction(async repositories=>{await this.platform(repositories,actor,tenantId);const parsed=/^act_([0-9a-f-]{36})\.([A-Za-z0-9_-]{20,})$/.exec(rawCredential);const fail=async(reason:string)=>{await this.audit(repositories,tenantId,actor,'commercial.activation.failed','activation',null,{accepted:false},reason);throw new CommercialAccessError(403,'Activation credential was rejected.');};if(!parsed)return fail('malformed');const current=await repositories.commercial.getActivationCredential(parsed[1]);if(!current||current.tenantId!==tenantId)return fail('unknown-or-wrong-tenant');if(!secretEquals(current.secretHash,rawCredential))return fail('verifier-mismatch');if(current.revokedAt)return fail('revoked');if(current.activatedAt)return fail('already-consumed');if(new Date(current.expiresAt)<=new Date())return fail('expired');const tenant=await this.tenant(repositories,tenantId);if(tenant.status==='SUSPENDED'||tenant.status==='CANCELLED')return fail('tenant-not-eligible');const consumed=await repositories.commercial.activateCredential(current.id,actor.actorId);if(!consumed)return fail('concurrent-consumption');const next=this.updated(tenant,{status:'ACTIVE',activationState:'ACTIVATED',commercialActivatedAt:new Date().toISOString(),commercialSuspendedAt:null});await repositories.tenants.updateLifecycle(next);await this.audit(repositories,tenantId,actor,'commercial.activation.succeeded',current.id,tenant,{tenant:next,credential:publicCredential(consumed)});return {tenant:next,credential:publicCredential(consumed)};});}
  async revoke(actor:CommercialActor,tenantId:string,credentialId:string,reason:string){return this.repositories.transaction(async repositories=>{await this.platform(repositories,actor,tenantId);const credential=await repositories.commercial.getActivationCredential(credentialId);if(!credential||credential.tenantId!==tenantId)throw new CommercialAccessError(404,'Activation credential was not found.');const previous=publicCredential(credential),revoked=await repositories.commercial.revokeActivationCredential(credentialId,actor.actorId,reason||'revoked-by-platform-admin');let tenant=await this.tenant(repositories,tenantId);if(credential.activatedAt&&tenant.status!=='CANCELLED'){const next=this.updated(tenant,{activationState:'DEACTIVATED'});await repositories.tenants.updateLifecycle(next);tenant=next;}await this.audit(repositories,tenantId,actor,'commercial.activation.credential-revoked',credentialId,previous,{credential:publicCredential(revoked!),tenant},reason);return {tenant,credential:publicCredential(revoked!)};});}
  async rotate(actor:CommercialActor,tenantId:string,credentialId:string,reason:string){return this.repositories.transaction(async repositories=>{await this.platform(repositories,actor,tenantId);const old=await repositories.commercial.getActivationCredential(credentialId);if(!old||old.tenantId!==tenantId)throw new CommercialAccessError(404,'Activation credential was not found.');const generated=this.credential(tenantId);const next=await repositories.commercial.createActivationCredential({id:generated.id,tenantId,secretHash:generated.hash,issuedBy:actor.actorId,expiresAt:this.expiry(undefined),supersedesCredentialId:old.id,metadata:{reason:reason||'rotated',algorithm:'sha256-random-256'}});const revoked=await repositories.commercial.revokeActivationCredential(old.id,actor.actorId,reason||'rotated',next.id);let tenant=await this.tenant(repositories,tenantId);if(old.activatedAt&&tenant.status!=='CANCELLED'){const updated=this.updated(tenant,{activationState:'PENDING'});await repositories.tenants.updateLifecycle(updated);tenant=updated;}await this.audit(repositories,tenantId,actor,'commercial.activation.credential-rotated',old.id,publicCredential(old),{previous:publicCredential(revoked!),replacement:publicCredential(next),tenant},reason);return {credential:generated.raw,record:publicCredential(next),replaced:publicCredential(revoked!)};});}
  async suspend(actor:CommercialActor,tenantId:string,reason:string){return this.transition(actor,tenantId,'SUSPENDED','DEACTIVATED','commercial.tenant.suspended',reason);}
  async reactivate(actor:CommercialActor,tenantId:string,reason:string){return this.transition(actor,tenantId,'ACTIVE','ACTIVATED','commercial.tenant.reactivated',reason);}
  async cancel(actor:CommercialActor,tenantId:string,reason:string){return this.repositories.transaction(async repositories=>{await this.platform(repositories,actor,tenantId);const previous=await this.tenant(repositories,tenantId);const next=this.updated(previous,{status:'CANCELLED',activationState:'DEACTIVATED',commercialCancelledAt:new Date().toISOString()});await repositories.tenants.updateLifecycle(next);for(const credential of await repositories.commercial.listActivationCredentials(tenantId))if(!credential.revokedAt)await repositories.commercial.revokeActivationCredential(credential.id,actor.actorId,'tenant-cancelled');await this.audit(repositories,tenantId,actor,'commercial.tenant.cancelled',tenantId,previous,next,reason);return next;});}
  private async transition(actor:CommercialActor,tenantId:string,status:'SUSPENDED'|'ACTIVE',activationState:'DEACTIVATED'|'ACTIVATED',action:string,reason:string){return this.repositories.transaction(async repositories=>{await this.platform(repositories,actor,tenantId);const previous=await this.tenant(repositories,tenantId);if(previous.status==='CANCELLED')throw new CommercialAccessError(409,'Cancelled laboratory cannot be reactivated.');if(status==='ACTIVE'&&previous.status!=='SUSPENDED')throw new CommercialAccessError(409,'Only suspended laboratories may be reactivated.');const next=this.updated(previous,status==='SUSPENDED'?{status,activationState,commercialSuspendedAt:new Date().toISOString()}:{status,activationState,commercialSuspendedAt:previous.commercialSuspendedAt});await repositories.tenants.updateLifecycle(next);await this.audit(repositories,tenantId,actor,action,tenantId,previous,next,reason);return next;});}
}
