import { expect, test } from '@playwright/test';

const email='dorianhabet@yahoo.com';
const password='NorthStar!2026';

async function login(page:any){
  await page.goto('/');await page.getByLabel('Email').fill(email);await page.getByLabel('Password').fill(password);
  const response=page.waitForResponse((item:any)=>item.url().endsWith('/api/auth/login')&&item.request().method()==='POST');await page.getByRole('button',{name:'Sign in'}).click();expect((await response).status()).toBe(200);
}

test('creates and previews a tenant-scoped Case Journey without duplicate product selection',async({page})=>{
  await login(page);await page.getByRole('button',{name:'Cases',exact:true}).click();await expect(page.getByRole('heading',{name:'Case Intake',level:1})).toBeVisible();await page.getByLabel('Arch selection').selectOption('maxillary');
  const previewResponse=page.waitForResponse((item:any)=>item.url().endsWith('/api/cases/preview')&&item.request().method()==='POST');await page.getByRole('button',{name:'Preview case'}).click();expect((await previewResponse).status()).toBe(200);await expect(page.getByText('CREATE PREVIEW')).toBeVisible();
  const rootResponse=page.waitForResponse((item:any)=>item.url().endsWith('/api/cases')&&item.request().method()==='POST');await page.getByRole('button',{name:'Confirm & create case'}).click();const rootPayload=await rootResponse;expect(rootPayload.status()).toBe(201);const root=await rootPayload.json() as {caseNumber:string};
  await page.locator('.cases-table .table-row',{hasText:root.caseNumber}).getByRole('button',{name:'Remake'}).click();await expect(page.getByLabel('Case relationship')).toHaveValue('REMAKE');await expect(page.getByText('Selected direct parent case')).toBeVisible();await expect(page.locator('.field-help',{hasText:root.caseNumber})).toBeVisible();await expect(page.getByLabel('Case practice')).toBeDisabled();await expect(page.getByLabel('Previous parent case')).toHaveCount(0);
  await page.getByLabel('Remake repair reason').selectOption({index:1});await expect(page.getByLabel('Responsibility')).toHaveValue('');await page.getByLabel('Responsibility').selectOption('SHARED');await page.getByRole('button',{name:'50%',exact:true}).click();await expect(page.getByLabel('Clinic responsibility percentage')).toHaveValue('50.00');await expect(page.getByLabel('Laboratory responsibility percentage')).toHaveValue('50.00');await page.getByLabel('Arch selection').selectOption('maxillary');
  const remakePreviewResponse=page.waitForResponse((item:any)=>item.url().endsWith('/api/cases/preview')&&item.request().method()==='POST');await page.getByRole('button',{name:'Preview case'}).click();expect((await remakePreviewResponse).status()).toBe(200);await expect(page.getByText('CREATE PREVIEW')).toBeVisible();await expect(page.getByText('Root Case',{exact:true})).toBeVisible();await expect(page.locator('.preview-row',{hasText:'SHARED'})).toBeVisible();
  const remakeResponse=page.waitForResponse((item:any)=>item.url().endsWith('/api/cases')&&item.request().method()==='POST');await page.getByRole('button',{name:'Confirm & create case'}).click();const remakePayload=await remakeResponse;expect(remakePayload.status()).toBe(201);const remake=await remakePayload.json() as {caseNumber:string};
  await page.locator('.cases-table .table-row',{hasText:remake.caseNumber}).getByRole('button',{name:'History'}).click();await expect(page.getByText('JOURNEY HISTORY')).toBeVisible();
  await page.locator('.cases-table .table-row',{hasText:root.caseNumber}).getByRole('button',{name:'Repair'}).click();await expect(page.getByLabel('Case relationship')).toHaveValue('REPAIR');await expect(page.getByText('Selected direct parent case')).toBeVisible();await expect(page.getByLabel('Previous parent case')).toHaveCount(0);await page.getByLabel('Remake repair reason').selectOption({index:1});await expect(page.getByLabel('Responsibility')).toHaveValue('');await page.getByLabel('Responsibility').selectOption('DOCTOR_PRACTICE');await page.getByRole('button',{name:'100%',exact:true}).click();await expect(page.getByLabel('Laboratory responsibility percentage')).toHaveValue('0.00');await page.getByLabel('Arch selection').selectOption('maxillary');
  const repairPreviewResponse=page.waitForResponse((item:any)=>item.url().endsWith('/api/cases/preview')&&item.request().method()==='POST');await page.getByRole('button',{name:'Preview case'}).click();expect((await repairPreviewResponse).status()).toBe(200);await expect(page.locator('.preview-row',{hasText:'DOCTOR / PRACTICE'})).toBeVisible();await page.getByRole('button',{name:'Back to edit'}).click();
  await page.locator('.cases-table .table-row',{hasText:remake.caseNumber}).getByRole('button',{name:'Continue'}).click();await expect(page.getByLabel('Case relationship')).toHaveValue('CONTINUATION');await expect(page.getByText('Selected direct parent case')).toBeVisible();await expect(page.locator('.field-help',{hasText:remake.caseNumber})).toBeVisible();await expect(page.getByLabel('Previous parent case')).toHaveCount(0);await expect(page.getByLabel('Continuation stage')).toHaveValue('');await expect(page.getByLabel('Continuation operational state')).toHaveValue('');await expect(page.getByLabel('Continuation stage')).toHaveAttribute('required','');await expect(page.getByLabel('Continuation operational state')).toHaveAttribute('required','');await expect(page.getByText('Tenant policy (inherited)')).toBeVisible();await page.getByLabel('Continuation stage').selectOption({index:1});await page.getByLabel('Continuation operational state').selectOption('AWAITING_RETURN');await page.getByLabel('Arch selection').selectOption('maxillary');
  const continuationPreviewResponse=page.waitForResponse((item:any)=>item.url().endsWith('/api/cases/preview')&&item.request().method()==='POST');await page.getByRole('button',{name:'Preview case'}).click();expect((await continuationPreviewResponse).status()).toBe(200);await expect(page.getByText('Tenant continuation billing policy',{exact:true})).toBeVisible();await expect(page.locator('.preview-row',{hasText:root.caseNumber})).toBeVisible();
  await page.getByRole('button',{name:'Back to edit'}).click();await page.getByRole('button',{name:'New case'}).click();await page.getByLabel('Case relationship').selectOption('REMAKE');await expect(page.getByLabel('Previous parent case')).toBeVisible();
});
