import { expect, test } from '@playwright/test';

const email='dorianhabet@yahoo.com';
const password='NorthStar!2026';

async function login(page:any){
  await page.goto('/');await page.getByLabel('Email').fill(email);await page.getByLabel('Password').fill(password);
  const response=page.waitForResponse((item:any)=>item.url().endsWith('/api/auth/login')&&item.request().method()==='POST');await page.getByRole('button',{name:'Sign in'}).click();expect((await response).status()).toBe(200);await expect.poll(()=>page.evaluate(()=>sessionStorage.getItem('northstar.csrf')??'')).not.toBe('');
}

async function configureCaseBuilderProduct(page:any){
  const sku=`F2A1-E2E-${Date.now()}`;
  const csrfToken=await page.evaluate(()=>sessionStorage.getItem('northstar.csrf')??'');expect(csrfToken).not.toBe('');
  const requestUrl=(path:string)=>new URL(path,page.url()).toString();
  const productInput={sku,productName:'F2A1 Browser Zirconia',description:'Case Builder browser validation product.',categoryCode:'FIX',familyCode:'FIX-E2E',pricingBasis:'PER_TOOTH',defaultTurnaroundBusinessDays:10,configuration:{selection:'SINGLE_TOOTH',allowedArches:['upper','lower']}};
  const missingToken=await page.context().request.post(requestUrl('/api/products'),{data:productInput});expect(missingToken.status()).toBe(403);
  const created=await page.context().request.post(requestUrl('/api/products'),{headers:{'X-CSRF-Token':csrfToken},data:productInput});expect(created.status()).toBe(201);const product=await created.json() as {id:string};
  const price=await page.context().request.post(requestUrl(`/api/products/${product.id}/prices`),{headers:{'X-CSRF-Token':csrfToken},data:{pricingBasis:'PER_TOOTH',amount:'99.00',effectiveFrom:'2000-01-01',effectiveUntil:null,versionNote:'Case Builder browser test price'}});expect(price.status()).toBe(201);
  return product.id;
}

async function addCaseProductLine(page:any,productId:string){
  await page.getByLabel('Restoration category').selectOption('FIX');
  await page.getByLabel('Catalog product').selectOption(productId);
  await expect(page.getByText('Tenant-authoritative current price')).toBeVisible();
  await page.getByLabel('Product line arch').selectOption('upper');
  await page.getByLabel('Product tooth 8').check();
  await page.getByRole('button',{name:'Add Case Product Line'}).click();
  await expect(page.getByText('1 selected')).toBeVisible();
}

test('creates and previews a tenant-scoped Case Journey through authoritative Case Product Lines',async({page})=>{
  await login(page);const productId=await configureCaseBuilderProduct(page);await page.getByRole('button',{name:'Cases',exact:true}).click();await expect(page.getByRole('heading',{name:'Case Intake',level:1})).toBeVisible();
  await addCaseProductLine(page,productId);
  const previewResponse=page.waitForResponse((item:any)=>item.url().endsWith('/api/cases/preview')&&item.request().method()==='POST');await page.getByRole('button',{name:'Preview case'}).click();expect((await previewResponse).status()).toBe(200);await expect(page.getByText('CREATE PREVIEW')).toBeVisible();await expect(page.getByText('Case Product Lines',{exact:true})).toBeVisible();await expect(page.locator('.case-preview-row',{hasText:'Parent Case'})).toHaveCount(0);
  const rootResponse=page.waitForResponse((item:any)=>item.url().endsWith('/api/cases')&&item.request().method()==='POST');await page.getByRole('button',{name:'Confirm & create case'}).click();const rootPayload=await rootResponse;expect(rootPayload.status()).toBe(201);const root=await rootPayload.json() as {caseNumber:string};
  await page.locator('.cases-table .table-row',{hasText:root.caseNumber}).getByRole('button',{name:'Remake'}).click();await expect(page.getByLabel('Case relationship')).toHaveValue('REMAKE');await expect(page.getByText('Selected direct parent case')).toBeVisible();await expect(page.locator('.field-help',{hasText:root.caseNumber})).toBeVisible();await expect(page.getByLabel('Case practice')).toBeDisabled();await expect(page.getByLabel('Previous parent case')).toHaveCount(0);
  await page.getByLabel('Remake repair reason').selectOption({index:1});await expect(page.getByLabel('Responsibility')).toHaveValue('');await expect(page.getByLabel('Responsibility')).toContainText('Doctor / Practice');await expect(page.getByLabel('Responsibility')).toContainText('Patient / External');await page.getByLabel('Responsibility').selectOption('SHARED');await page.getByRole('button',{name:'50%',exact:true}).click();await expect(page.getByLabel('Clinic responsibility percentage')).toHaveValue('50.00');await expect(page.getByLabel('Laboratory responsibility percentage')).toHaveValue('50.00');await addCaseProductLine(page,productId);
  const remakePreviewResponse=page.waitForResponse((item:any)=>item.url().endsWith('/api/cases/preview')&&item.request().method()==='POST');await page.getByRole('button',{name:'Preview case'}).click();expect((await remakePreviewResponse).status()).toBe(200);await expect(page.getByText('CREATE PREVIEW')).toBeVisible();await expect(page.getByText('Root Case',{exact:true})).toBeVisible();await expect(page.locator('.case-preview-row',{hasText:'Shared'})).toBeVisible();await expect(page.locator('.case-preview-row',{hasText:'Parent Case'})).toContainText(root.caseNumber);await expect(page.locator('.case-preview-row',{hasText:'Root Case'})).toContainText(root.caseNumber);
  const remakeResponse=page.waitForResponse((item:any)=>item.url().endsWith('/api/cases')&&item.request().method()==='POST');await page.getByRole('button',{name:'Confirm & create case'}).click();const remakePayload=await remakeResponse;expect(remakePayload.status()).toBe(201);const remake=await remakePayload.json() as {caseNumber:string};
  await page.locator('.cases-table .table-row',{hasText:remake.caseNumber}).getByRole('button',{name:'History'}).click();await expect(page.getByText('JOURNEY HISTORY')).toBeVisible();
  await page.locator('.cases-table .table-row',{hasText:root.caseNumber}).getByRole('button',{name:'Repair'}).click();await expect(page.getByLabel('Case relationship')).toHaveValue('REPAIR');await expect(page.getByText('Selected direct parent case')).toBeVisible();await expect(page.getByLabel('Previous parent case')).toHaveCount(0);await page.getByLabel('Remake repair reason').selectOption({index:1});await expect(page.getByLabel('Responsibility')).toHaveValue('');await page.getByLabel('Responsibility').selectOption('DOCTOR_PRACTICE');await page.getByRole('button',{name:'100%',exact:true}).click();await expect(page.getByLabel('Laboratory responsibility percentage')).toHaveValue('0.00');await addCaseProductLine(page,productId);
  const repairPreviewResponse=page.waitForResponse((item:any)=>item.url().endsWith('/api/cases/preview')&&item.request().method()==='POST');await page.getByRole('button',{name:'Preview case'}).click();expect((await repairPreviewResponse).status()).toBe(200);await expect(page.locator('.case-preview-row',{hasText:'Doctor / Practice'})).toBeVisible();await expect(page.locator('.case-preview-row',{hasText:'Parent Case'})).toContainText(root.caseNumber);await expect(page.locator('.case-preview-row',{hasText:'Root Case'})).toContainText(root.caseNumber);await page.getByRole('button',{name:'Back to edit'}).click();
  await page.locator('.cases-table .table-row',{hasText:remake.caseNumber}).getByRole('button',{name:'Continue'}).click();await expect(page.getByLabel('Case relationship')).toHaveValue('CONTINUATION');await expect(page.getByText('Selected direct parent case')).toBeVisible();await expect(page.locator('.field-help',{hasText:remake.caseNumber})).toBeVisible();await expect(page.getByLabel('Previous parent case')).toHaveCount(0);await expect(page.getByLabel('Continuation stage')).toHaveValue('');await expect(page.getByLabel('Continuation operational state')).toHaveValue('');await expect(page.getByLabel('Continuation stage')).toHaveAttribute('required','');await expect(page.getByLabel('Continuation operational state')).toHaveAttribute('required','');await expect(page.getByLabel('Continuation operational state')).toContainText('Awaiting Clinical Try In');await expect(page.getByLabel('Continuation operational state')).toContainText('Awaiting Return');await expect(page.getByText('Tenant policy (inherited)')).toBeVisible();await page.getByLabel('Continuation stage').selectOption({index:1});await page.getByLabel('Continuation operational state').selectOption('AWAITING_RETURN');await expect(page.getByLabel('Continuation operational state')).toHaveValue('AWAITING_RETURN');await addCaseProductLine(page,productId);
  const continuationPreviewResponse=page.waitForResponse((item:any)=>item.url().endsWith('/api/cases/preview')&&item.request().method()==='POST');await page.getByRole('button',{name:'Preview case'}).click();expect((await continuationPreviewResponse).status()).toBe(200);await expect(page.locator('.case-preview-row',{hasText:'Operational State'})).toContainText('Awaiting Return');await expect(page.locator('.case-preview-row',{hasText:'Billing Policy'})).toContainText('Tenant policy · inherited');await expect(page.locator('.case-preview-row',{hasText:'Parent Case'})).toContainText(remake.caseNumber);await expect(page.locator('.case-preview-row',{hasText:'Root Case'})).toContainText(root.caseNumber);
  await page.getByRole('button',{name:'Back to edit'}).click();await page.getByRole('button',{name:'New case'}).click();await page.getByLabel('Case relationship').selectOption('REMAKE');await expect(page.getByLabel('Previous parent case')).toBeVisible();
});
