import { expect, test } from '@playwright/test';

async function openStudio(page) {
  const errors = []; page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()); }); page.on('pageerror', (error) => errors.push(error.message)); await page.goto('/design-studio.html'); await expect(page.getByRole('heading', { name: 'Production Viewer' })).toBeVisible(); return errors;
}

async function importPreparation(page, name, content) { await page.locator('input[type=file]').setInputFiles({ name, mimeType: 'application/octet-stream', buffer: Buffer.from(content) }); await expect(page.getByText(name, { exact: true })).toBeVisible(); await page.getByText(name, { exact: true }).click(); await page.getByRole('button', { name: 'Prepare', exact: true }).click(); await expect(page.getByRole('heading', { name: 'Preparation & Margin' })).toBeVisible(); }

async function detectAndIdentify(page) {
  await page.getByRole('button', { name: 'Auto Detect Prep' }).click(); await expect(page.getByRole('status')).toContainText('Preparation detection produced', { timeout: 30_000 }); await expect(page.locator('.preparation-result')).toBeVisible(); await expect(page.getByRole('button', { name: 'Accept preparation candidate' })).toBeEnabled(); await page.getByRole('button', { name: 'Accept preparation candidate' }).click(); await expect(page.getByRole('status')).toContainText('Identified Preparation');
}

async function detectAndAcceptMargin(page) { await page.getByRole('button', { name: 'Auto Detect Margin' }).click(); await expect(page.getByRole('status')).toContainText('Margin detection retained', { timeout: 30_000 }); await expect(page.locator('.candidate-evidence')).toBeVisible(); await page.getByRole('button', { name: 'Accept candidate', exact: true }).click(); await expect(page.getByRole('status')).toContainText('Accepted candidate'); await expect(page.getByRole('heading', { name: 'Margin Editor' })).toBeVisible(); }

test('detects measured preparation and ranked margins, analyzes axis/QC, approves, locks, and persists', async ({ page }) => {
  const errors = await openStudio(page); await importPreparation(page, 'shoulder-preparation.ply', preparationPly('shoulder', 64));
  await page.evaluate(() => { window.__preparationFrameProbe = { active: true, frames: 0, maxGapMs: 0, last: performance.now() }; const tick = (time) => { const probe = window.__preparationFrameProbe; if (!probe?.active) return; probe.frames += 1; probe.maxGapMs = Math.max(probe.maxGapMs, time - probe.last); probe.last = time; requestAnimationFrame(tick); }; requestAnimationFrame(tick); });
  await detectAndIdentify(page); const probe = await page.evaluate(() => { window.__preparationFrameProbe.active = false; return window.__preparationFrameProbe; }); expect(probe.frames).toBeGreaterThan(0); console.log('PREPARATION_BROWSER_PERFORMANCE', JSON.stringify(probe));
  await page.getByRole('button', { name: 'Auto Detect Margin' }).click(); await expect(page.getByRole('status')).toContainText('Margin detection retained', { timeout: 30_000 }); await expect(page.locator('.candidate-evidence')).toContainText('Class'); await expect(page.locator('.candidate-evidence')).toContainText('shoulder'); await page.getByRole('button', { name: 'Compare candidates' }).click(); await expect(page.locator('.comparison-card')).toContainText('mean'); await page.getByRole('button', { name: 'Accept candidate', exact: true }).click();
  await expect(page.locator('.segment-table article')).toHaveCount(64); await page.getByRole('button', { name: 'Insertion Axis', exact: true }).click(); await expect(page.locator('.axis-candidates button').first()).toBeVisible({ timeout: 30_000 }); await page.getByLabel('Undercuts').check();
  await page.getByRole('button', { name: 'Margin completeness' }).click(); await expect(page.getByRole('status')).toContainText('Margin quality passed'); await page.getByRole('button', { name: 'QC', exact: true }).click(); await expect(page.locator('.qc-summary.warning')).toContainText('0 failures', { timeout: 30_000 }); await page.getByRole('button', { name: 'Approve', exact: true }).click(); await expect(page.getByRole('status')).toContainText('Margin approved'); await page.getByRole('button', { name: 'Lock', exact: true }).click(); await expect(page.getByRole('status')).toContainText('Approved margin locked'); await expect(page.getByRole('button', { name: 'Unlock', exact: true })).toBeVisible();
  await page.getByLabel('Project name').fill('Preparation Certified Case'); await page.getByRole('button', { name: 'Save', exact: true }).click(); await expect(page.getByText('Saved · Schema v6')).toBeVisible(); await page.reload(); await page.getByRole('button', { name: 'Open' }).click(); await page.getByRole('button', { name: /Preparation Certified Case/ }).click(); await page.getByRole('button', { name: 'Prepare', exact: true }).click(); await expect(page.getByRole('button', { name: 'Unlock', exact: true })).toBeVisible(); await expect(page.locator('.margin-history button')).toHaveCount(3); expect(errors).toEqual([]);
});

test('draws and edits an actual surface margin through command undo/redo and crash recovery', async ({ page }) => {
  const errors = await openStudio(page); await importPreparation(page, 'manual-preparation.ply', preparationPly('shoulder', 48)); await detectAndIdentify(page);
  await page.getByRole('button', { name: 'Fit selected', exact: true }).first().click(); await page.getByRole('button', { name: 'point by point', exact: true }).click(); const canvas = page.getByLabel('Design Studio 3D viewer'); const box = await canvas.boundingBox(); expect(box).not.toBeNull(); for (const point of [[0.45, 0.50], [0.48, 0.55], [0.53, 0.55], [0.56, 0.50], [0.53, 0.45], [0.48, 0.45]]) await canvas.click({ position: { x: box.width * point[0], y: box.height * point[1] } }); await expect(page.getByRole('button', { name: 'Confirm drawn margin' })).toBeEnabled(); await page.getByRole('button', { name: 'Confirm drawn margin' }).click(); await expect(page.getByRole('status')).toContainText('Created point-by-point model-space margin');
  await page.getByRole('button', { name: 'Reverse', exact: true }).click(); await expect(page.getByRole('status')).toContainText('Margin reverse created version'); await page.getByRole('button', { name: 'Surface reproject' }).click(); await expect(page.getByRole('status')).toContainText('Margin reproject created version'); await page.getByRole('button', { name: 'Undo' }).click(); await expect(page.getByRole('button', { name: 'Redo' })).toBeEnabled(); await page.getByRole('button', { name: 'Redo' }).click(); await expect(page.getByRole('status')).toContainText('Auto-saved', { timeout: 5_000 });
  await page.reload(); await expect(page.getByText('Recovery snapshot available')).toBeVisible(); await page.getByRole('button', { name: 'Recover' }).click(); await page.getByRole('button', { name: 'Prepare', exact: true }).click(); await expect(page.locator('.margin-history button')).toHaveCount(3); await expect(page.getByRole('heading', { name: 'Margin Editor' })).toBeVisible(); expect(errors).toEqual([]);
});

test('supports two preparations, independent axes, common bridge draw analysis, and batch QC', async ({ page }) => {
  const errors = await openStudio(page); await importPreparation(page, 'bridge-preparations.ply', bridgePly(40)); await page.getByRole('button', { name: 'Auto Detect Prep' }).click(); await expect(page.getByRole('status')).toContainText('Preparation detection produced 2', { timeout: 30_000 }); await expect(page.getByLabel('Preparation candidate').locator('option')).toHaveCount(3);
  await page.getByRole('button', { name: 'Accept preparation candidate' }).click(); await page.getByLabel('Preparation candidate').selectOption({ index: 2 }); await page.getByRole('button', { name: 'Accept preparation candidate' }).click(); await expect(page.getByLabel('Active preparation').locator('option')).toHaveCount(3);
  for (const index of [1, 2]) { await page.getByLabel('Active preparation').selectOption({ index }); await page.getByRole('button', { name: 'Auto Detect Margin' }).click(); await expect(page.getByRole('status')).toContainText('Margin detection retained', { timeout: 30_000 }); await page.getByRole('button', { name: 'Accept candidate', exact: true }).click(); await page.getByRole('button', { name: 'Insertion Axis', exact: true }).click(); await expect(page.locator('.axis-candidates button').first()).toBeVisible({ timeout: 30_000 }); }
  await page.getByRole('button', { name: 'Common bridge path' }).click(); await expect(page.getByRole('status')).toContainText(/Common bridge path|Bridge path conflict/); await page.getByRole('button', { name: 'Batch QC' }).click(); await expect(page.getByRole('status')).toContainText('Batch QC completed for 2 preparations', { timeout: 60_000 }); expect(errors).toEqual([]);
});

test('rejects mirrored geometry without fabricating a preparation or margin', async ({ page }) => {
  const errors = await openStudio(page); await importPreparation(page, 'mirrored-preparation.ply', preparationPly('chamfer', 40, true)); await page.getByRole('button', { name: 'Auto Detect Prep' }).click(); await expect(page.getByRole('status')).toContainText('Preparation detection produced', { timeout: 30_000 }); await expect(page.locator('.preparation-result')).toContainText('UNSUPPORTED'); await expect(page.locator('.preparation-result')).toContainText(/mirrored|inward-wound/); await expect(page.getByRole('button', { name: 'Accept preparation candidate' })).toBeDisabled(); await expect(page.getByRole('button', { name: 'Auto Detect Margin' })).toHaveCount(0); expect(errors).toEqual([]);
});

function preparationGeometry(kind, segments, offsetX = 0) {
  const configuration = kind === 'shoulder' ? { rings: [{ z: -2, radius: 6 }, { z: 0, radius: 5 }, { z: 0, radius: 4 }, { z: 5, radius: 3.35 }] } : { rings: [{ z: -2, radius: 6.25 }, { z: -0.2, radius: 4.5775 }, { z: 0.35, radius: 4 }, { z: 5.2, radius: 3.35 }] }; const vertices = [], faces = [];
  for (const ring of configuration.rings) for (let segment = 0; segment < segments; segment += 1) { const angle = segment / segments * Math.PI * 2; vertices.push([offsetX + Math.cos(angle) * ring.radius, Math.sin(angle) * ring.radius, ring.z]); }
  for (let ring = 0; ring < configuration.rings.length - 1; ring += 1) for (let segment = 0; segment < segments; segment += 1) { const next = (segment + 1) % segments, a = ring * segments + segment, b = ring * segments + next, c = (ring + 1) * segments + segment, d = (ring + 1) * segments + next; faces.push([a, b, d], [a, d, c]); }
  const bottom = vertices.length; vertices.push([offsetX, 0, configuration.rings[0].z]); const top = vertices.length; vertices.push([offsetX, 0, configuration.rings.at(-1).z]); const topOffset = (configuration.rings.length - 1) * segments; for (let segment = 0; segment < segments; segment += 1) { const next = (segment + 1) % segments; faces.push([bottom, next, segment], [top, topOffset + segment, topOffset + next]); }
  return { vertices, faces };
}

function preparationPly(kind, segments, mirrored = false) { const geometry = preparationGeometry(kind, segments); if (mirrored) geometry.vertices = geometry.vertices.map(([x, y, z]) => [-x, y, z]); return ply(geometry, `${kind}-${mirrored ? 'mirrored' : 'fixture'}`); }
function bridgePly(segments) { const first = preparationGeometry('chamfer', segments, -7.5), second = preparationGeometry('shoulder', segments, 7.5), offset = first.vertices.length; return ply({ vertices: [...first.vertices, ...second.vertices], faces: [...first.faces, ...second.faces.map((face) => face.map((value) => value + offset))] }, 'bridge-fixture'); }
function ply(geometry, marker) { return `ply\nformat ascii 1.0\ncomment deterministic ${marker}\nelement vertex ${geometry.vertices.length}\nproperty float x\nproperty float y\nproperty float z\nelement face ${geometry.faces.length}\nproperty list uchar int vertex_indices\nend_header\n${geometry.vertices.map((point) => point.map((value) => value.toFixed(8)).join(' ')).join('\n')}\n${geometry.faces.map((face) => `3 ${face.join(' ')}`).join('\n')}\n`; }
