import { expect, test } from '@playwright/test';
import { openAuthorizedDesignStudio } from './design-studio-access.mjs';

test.describe.configure({ timeout: 180_000 });

test.describe('production single-unit crown technician workflows', () => {
  test('completes an anterior crown from registered case through export, save, close, and reopen', async ({ page }) => {
    await completeCrown(page, { tooth: 8, label: 'Anterior Crown Case', preparationKind: 'shoulder', antagonistZ: 7.80, adjacentX: 4.445, material: 'lithium-disilicate' });
  });

  test('completes a posterior crown from registered case through export, recovery, and identical reopen', async ({ page }) => {
    await completeCrown(page, { tooth: 3, label: 'Posterior Crown Case', preparationKind: 'shoulder', antagonistZ: 8.73, mesialX: 4.79, distalX: 3.75, material: 'zirconia-monolithic', recovery: true });
  });

  test('fails closed on an infeasible posterior contact without treating the approved margin as editable support', async ({ page }) => {
    await completeCrown(page, { tooth: 3, label: 'Infeasible Posterior Crown Case', preparationKind: 'shoulder', antagonistZ: 8.73, adjacentX: 4.51, material: 'zirconia-monolithic', expectedProximalFailure: true });
  });
});

async function completeCrown(page, value) {
  const errors = []; page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()); }); page.on('pageerror', (error) => errors.push(error.message));
  await openAuthorizedDesignStudio(page);
  const prep = preparationGeometry(value.preparationKind, 48); const registrationTarget = archGeometry(17, 13); const registrationSource = inverseRigidGeometry(registrationTarget, { angle: 8, translation: [2.2, -1.1, 0.7] });
  const files = [
    { name: 'upper-arch-mm.ply', content: ply(registrationTarget, 'registration-target') }, { name: 'full-bite-mm.ply', content: ply(registrationSource, 'registration-source') },
    { name: 'crown-preparation-mm.ply', content: ply(prep, `crown-preparation-${value.tooth}`) },
    { name: 'mesial-reference-mm.ply', content: ply(box([-9, -7, -2], [-(value.mesialX ?? value.adjacentX), 7, 12]), 'mesial-adjacent') },
    { name: 'distal-reference-mm.ply', content: ply(box([value.distalX ?? value.adjacentX, -7, -2], [9, 7, 12]), 'distal-adjacent') },
    { name: 'antagonist-mm.ply', content: ply(box([-7, -7, value.antagonistZ], [7, 7, value.antagonistZ + 3]), 'static-antagonist') },
    { name: 'preop-reference-mm.ply', content: ply(referenceCrown(44, value.tooth <= 16 ? 8.1 : 7.6), 'preop-reference') },
  ];
  await page.locator('input[type=file]').setInputFiles(files.slice(0, 2).map((file) => ({ name: file.name, mimeType: 'application/octet-stream', buffer: Buffer.from(file.content) }))); await expect(page.getByText('2 objects', { exact: true })).toBeVisible();

  await page.getByRole('button', { name: 'Register', exact: true }).click(); await page.getByLabel('Registration source').selectOption({ label: 'full-bite-mm.ply' }); await page.getByLabel('Registration target').selectOption({ label: 'upper-arch-mm.ply' }); await page.getByRole('button', { name: 'Register selected pair' }).click(); await expect(page.locator('.registration-result.accepted')).toBeVisible({ timeout: 30_000 }); await page.getByRole('button', { name: 'Accept registration' }).click(); await expect(page.getByRole('status')).toContainText('Registration accepted'); await page.getByRole('button', { name: 'AUTO ASSEMBLE CASE' }).click(); await expect(page.locator('.assembly-summary.accepted')).toBeVisible({ timeout: 30_000 }); await expect(page.getByText('CADENCE_DENTAL_XYZ_V1')).toBeVisible();
  await page.locator('input[type=file]').setInputFiles(files.slice(2).map((file) => ({ name: file.name, mimeType: 'application/octet-stream', buffer: Buffer.from(file.content) }))); await expect(page.getByText('7 objects', { exact: true })).toBeVisible();

  await page.getByRole('button', { name: 'Scene', exact: true }).click(); await page.getByText('crown-preparation-mm.ply', { exact: true }).click(); await page.getByRole('button', { name: 'Prepare', exact: true }).click(); await page.getByRole('button', { name: 'Auto Detect Prep' }).click(); await expect(page.getByRole('status')).toContainText('Preparation detection produced', { timeout: 30_000 }); await page.getByRole('button', { name: 'Accept preparation candidate' }).click();
  page.once('dialog', (dialog) => dialog.accept(String(value.tooth))); await page.getByRole('button', { name: 'Assign tooth' }).click(); await page.getByRole('button', { name: 'Lock approved region' }).click(); await expect(page.getByRole('button', { name: 'Unlock region' })).toBeVisible();
  await page.getByRole('button', { name: 'Auto Detect Margin' }).click(); await expect(page.getByRole('status')).toContainText('Margin detection retained', { timeout: 30_000 }); await page.getByRole('button', { name: 'Accept candidate', exact: true }).click(); await page.getByRole('button', { name: 'Apply numeric manual axis' }).click(); await expect(page.locator('.axis-candidates button').first()).toBeVisible({ timeout: 30_000 }); await page.getByRole('button', { name: 'Lock axis' }).click(); await expect(page.getByRole('button', { name: 'Unlock axis' })).toBeVisible();
  await page.getByRole('button', { name: 'Margin completeness' }).click(); await expect(page.getByRole('status')).toContainText('Margin quality passed'); await page.getByRole('button', { name: 'QC', exact: true }).click(); await expect(page.locator('.qc-summary')).toContainText('0 failures', { timeout: 30_000 }); await page.getByRole('button', { name: 'Approve', exact: true }).click(); await page.getByRole('button', { name: 'Lock', exact: true }).click(); await expect(page.getByRole('button', { name: 'Unlock', exact: true })).toBeVisible();

  await page.getByRole('button', { name: 'Crown', exact: true }).click(); await expect(page.getByRole('heading', { name: 'Single Crown' })).toBeVisible(); await page.getByLabel('Crown tooth number').fill(String(value.tooth)); await page.getByLabel('Crown material').selectOption(value.material); await selectObject(page, 'Mesial adjacent', 'mesial-reference-mm.ply'); await selectObject(page, 'Distal adjacent', 'distal-reference-mm.ply'); await selectObject(page, 'Antagonist', 'antagonist-mm.ply'); await selectObject(page, 'Contour / morphology reference', 'preop-reference-mm.ply'); await page.getByLabel('Reference category').selectOption('pre-op'); await page.getByLabel('Reference adaptation mode').selectOption('blend'); await page.getByLabel('Reference influence').fill('0.55');
  await page.evaluate(() => { window.__crownFrameProbe = { active: true, frames: 0, maximumGapMs: 0, previous: performance.now() }; const tick = (time) => { const probe = window.__crownFrameProbe; if (!probe?.active) return; probe.frames += 1; probe.maximumGapMs = Math.max(probe.maximumGapMs, time - probe.previous); probe.previous = time; requestAnimationFrame(tick); }; requestAnimationFrame(tick); });
  await page.getByRole('button', { name: 'AUTO DESIGN CROWN' }).click(); await expect(page.locator('.crown-state')).toContainText('QC_REQUIRED', { timeout: 60_000 }); const probe = await page.evaluate(() => { window.__crownFrameProbe.active = false; return window.__crownFrameProbe; }); expect(probe.frames).toBeGreaterThan(0); console.log('CROWN_BROWSER_PERFORMANCE', JSON.stringify({ tooth: value.tooth, ...probe }));
  await expect(page.getByText('Actual intaglio surface', { exact: false })).toHaveCount(0); await page.getByLabel('Intaglio surface').check();
  await page.getByText('Restoration parameters and anatomy controls').click(); await page.getByLabel('Anatomy intensity').fill('0.78'); await page.getByRole('button', { name: 'REGENERATE CROWN FROM PARAMETERS' }).click(); await expect(page.getByRole('status')).toContainText('Generated actual crown solid', { timeout: 60_000 }); await page.getByRole('button', { name: 'Undo' }).click(); await page.getByRole('button', { name: 'Redo' }).click();
  await page.getByRole('button', { name: 'Optimize mesial contact' }).click(); await expect(page.getByRole('status')).toContainText('Optimized actual mesial contact geometry', { timeout: 30_000 }); await page.getByRole('button', { name: 'Optimize distal contact' }).click(); await expect(page.getByRole('status')).toContainText('Optimized actual distal contact geometry', { timeout: 30_000 }); await page.getByRole('button', { name: 'Optimize static occlusion' }).click(); await expect(page.getByRole('status')).toContainText('Optimized actual static occlusal geometry', { timeout: 30_000 }); await page.getByRole('button', { name: 'Joint contact + occlusion optimizer' }).click(); await expect(page.getByText(/^Optimizer (converged|best-effort|constraint-conflict)$/)).toBeVisible({ timeout: 60_000 }); await page.getByRole('button', { name: 'Auto-thicken' }).click(); await expect(page.getByRole('status')).toContainText('Applied governed actual wall-thickness correction', { timeout: 30_000 }); await page.getByLabel('Crown checkpoint name').fill('Technician review'); await page.getByRole('button', { name: 'Create checkpoint' }).click(); await expect(page.getByRole('status')).toContainText('Created checkpoint');
  await page.getByRole('button', { name: 'Run complete crown QC + export preflight' }).click(); await expect(page.locator('.roundtrip-list article')).toHaveCount(4, { timeout: 120_000 }); const failingChecks = await page.locator('.crown-qc-list article.fail').evaluateAll((items) => items.map((item) => item.textContent));
  if (value.expectedProximalFailure) { expect(failingChecks.some((check) => check?.includes('distal-contact'))).toBe(true); await expect(page.locator('.validation-summary:has(+ .crown-qc-list)')).toContainText('FAIL'); await expect(page.locator('.crown-state')).toContainText('QC_FAILED'); await expect(page.getByRole('button', { name: 'Approve for export' })).toBeDisabled(); await expect(page.getByRole('button', { name: 'Export STL / OBJ / PLY' })).toBeDisabled(); return; }
  expect(failingChecks).toEqual([]); await expect(page.locator('.validation-summary:has(+ .crown-qc-list)')).toContainText(/PASS|WARNING/); await page.getByRole('button', { name: 'Approve for export' }).click(); await expect(page.locator('.crown-state')).toContainText('APPROVED_FOR_EXPORT'); await page.getByRole('button', { name: 'Lock final' }).click(); await expect(page.locator('.crown-state')).toContainText('LOCKED');
  const downloadedNames = []; page.on('download', (download) => downloadedNames.push(download.suggestedFilename())); await page.getByRole('button', { name: 'Export STL / OBJ / PLY' }).click(); await expect.poll(() => downloadedNames.length, { timeout: 30_000 }).toBe(4); expect(new Set(downloadedNames.map((name) => name.split('.').at(-1)))).toEqual(new Set(['stl', 'obj', 'ply'])); await expect(page.locator('.crown-state')).toContainText('EXPORTED');
  await page.getByLabel('Project name').fill(value.label); await page.getByRole('button', { name: 'Save', exact: true }).click(); expect(errors).toEqual([]); await expect(page.getByText('Saved · Schema v6')).toBeVisible();
  if (value.recovery) {
    await page.getByLabel('Anatomy intensity').fill('0.80'); await page.getByRole('button', { name: 'REGENERATE CROWN FROM PARAMETERS' }).click(); await expect(page.getByRole('status')).toContainText('Locked restoration geometry cannot be modified');
    await page.getByLabel('Contact heatmap').uncheck(); await expect(page.getByRole('status')).toContainText('Updated contactOverlayVisible'); await expect(page.getByRole('status')).toContainText('Auto-saved', { timeout: 10_000 });
    await page.reload(); await expect(page.getByText('Recovery snapshot available')).toBeVisible(); await page.getByRole('button', { name: 'Recover', exact: true }).click(); await page.getByRole('button', { name: 'Crown', exact: true }).click(); await expect(page.locator('.crown-state')).toContainText('LOCKED'); await expect(page.getByLabel('Contact heatmap')).not.toBeChecked(); await page.getByRole('button', { name: 'Save', exact: true }).click(); await expect(page.getByText('Saved · Schema v6')).toBeVisible();
  }
  await page.getByRole('button', { name: 'Close' }).click(); await page.getByRole('button', { name: 'Open' }).click(); await page.getByRole('button', { name: new RegExp(value.label) }).click(); await page.getByRole('button', { name: 'Crown', exact: true }).click(); await expect(page.locator('.crown-state')).toContainText('LOCKED'); await expect(page.locator('.crown-state')).toContainText('EXPORTED'); await expect(page.locator('.version-list article').first()).toContainText('watertight true'); await expect(page.locator('.roundtrip-list article')).toHaveCount(0); expect(errors).toEqual([]);
}

function preparationGeometry(kind, segments, offsetX = 0) {
  const rings = kind === 'shoulder' ? [{ z: -2, radius: 6 }, { z: 0, radius: 5 }, { z: 0, radius: 4 }, { z: 5, radius: 3.35 }] : [{ z: -2, radius: 6.25 }, { z: -0.2, radius: 4.5775 }, { z: 0.35, radius: 4 }, { z: 5.2, radius: 3.35 }]; const vertices = [], faces = [];
  for (const ring of rings) for (let segment = 0; segment < segments; segment += 1) { const angle = segment / segments * Math.PI * 2; vertices.push([offsetX + Math.cos(angle) * ring.radius, Math.sin(angle) * ring.radius, ring.z]); }
  for (let ring = 0; ring < rings.length - 1; ring += 1) for (let segment = 0; segment < segments; segment += 1) { const next = (segment + 1) % segments, a = ring * segments + segment, b = ring * segments + next, c = (ring + 1) * segments + segment, d = (ring + 1) * segments + next; faces.push([a, b, d], [a, d, c]); }
  const bottom = vertices.length; vertices.push([offsetX, 0, rings[0].z]); const top = vertices.length; vertices.push([offsetX, 0, rings.at(-1).z]); const topOffset = (rings.length - 1) * segments; for (let segment = 0; segment < segments; segment += 1) { const next = (segment + 1) % segments; faces.push([bottom, next, segment], [top, topOffset + segment, topOffset + next]); } return { vertices, faces };
}
function box(min, max) { const vertices = [[min[0], min[1], min[2]], [max[0], min[1], min[2]], [max[0], max[1], min[2]], [min[0], max[1], min[2]], [min[0], min[1], max[2]], [max[0], min[1], max[2]], [max[0], max[1], max[2]], [min[0], max[1], max[2]]]; const faces = [[0, 2, 1], [0, 3, 2], [4, 5, 6], [4, 6, 7], [0, 1, 5], [0, 5, 4], [1, 2, 6], [1, 6, 5], [2, 3, 7], [2, 7, 6], [3, 0, 4], [3, 4, 7]]; return { vertices, faces }; }
function referenceCrown(segments, height) { const vertices = [], faces = []; const rings = [{ z: 0, radius: 4.6 }, { z: height * 0.45, radius: 5 }, { z: height, radius: 3.3 }]; for (const ring of rings) for (let index = 0; index < segments; index += 1) { const angle = index / segments * Math.PI * 2; vertices.push([Math.cos(angle) * ring.radius, Math.sin(angle) * ring.radius * 0.9, ring.z]); } for (let ring = 0; ring < rings.length - 1; ring += 1) for (let index = 0; index < segments; index += 1) { const next = (index + 1) % segments, a = ring * segments + index, b = ring * segments + next, c = (ring + 1) * segments + index, d = (ring + 1) * segments + next; faces.push([a, b, d], [a, d, c]); } return { vertices, faces }; }
function archGeometry(columns, rows) { const vertices = [], faces = []; for (let row = 0; row < rows; row += 1) for (let column = 0; column < columns; column += 1) { const x = (column - (columns - 1) / 2) * 1.35, y = row * 1.45 + 0.035 * x * x, z = 0.24 * Math.sin(column * 0.71) + 0.17 * Math.cos(row * 0.63) + 0.012 * x * row + (column === 2 && row === 2 ? 0.8 : 0); vertices.push([x, y, z]); } for (let row = 0; row < rows - 1; row += 1) for (let column = 0; column < columns - 1; column += 1) { const a = row * columns + column, b = a + 1, c = a + columns, d = c + 1; faces.push([a, b, c], [b, d, c]); } return { vertices, faces }; }
function inverseRigidGeometry(geometry, transform) { const radians = transform.angle * Math.PI / 180, cosine = Math.cos(radians), sine = Math.sin(radians); return { vertices: geometry.vertices.map(([px, py, pz]) => { const x = px - transform.translation[0], y = py - transform.translation[1]; return [cosine * x + sine * y, -sine * x + cosine * y, pz - transform.translation[2]]; }), faces: geometry.faces.map((face) => [...face]) }; }
function ply(geometry, marker) { return `ply\nformat ascii 1.0\ncomment deterministic ${marker}\nelement vertex ${geometry.vertices.length}\nproperty float x\nproperty float y\nproperty float z\nelement face ${geometry.faces.length}\nproperty list uchar int vertex_indices\nend_header\n${geometry.vertices.map((point) => point.map((value) => value.toFixed(8)).join(' ')).join('\n')}\n${geometry.faces.map((face) => `3 ${face.join(' ')}`).join('\n')}\n`; }
async function selectObject(page, label, objectName) { const select = page.getByLabel(label, { exact: true }); const option = select.locator('option').filter({ hasText: objectName }); const value = await option.getAttribute('value'); if (!value) throw new Error(`${objectName} is unavailable in ${label}`); await select.selectOption(value); }
