import { expect, test } from '@playwright/test';

const password=process.env.NORTHSTAR_UAT_PASSWORD;
if(!password)throw new Error('NORTHSTAR_UAT_PASSWORD is required.');
const roles=[
 ['Tenant Owner','tenant.owner@keramos-uat.example','Operations Overview',['Executive Command Center','Validation','Intake Administration']],
 ['Tenant Administrator','tenant.admin@keramos-uat.example','Operations Overview',['Executive Command Center','Validation','Intake Administration']],
 ['Customer Service','customer.service@keramos-uat.example','Operations Overview',['Validation','Digital Intake','Cases']],
 ['CAD Designer','cad.designer@keramos-uat.example','Production Workflow',['Validation','Cases','Production']],
 ['QC Technician','qc.technician@keramos-uat.example','Quality Control',['Validation','Production','Quality Control']],
 ['Production Technician','production.technician@keramos-uat.example','Production Workflow',['Validation','Cases','Production']],
 ['Shipping','shipping@keramos-uat.example','Shipping & Logistics',['Validation','Cases','Shipping']],
 ['Accounting','accounting@keramos-uat.example','Billing & Financial Engine',['Validation','Billing']],
 ['Sales','sales@keramos-uat.example','Operations Overview',['Validation','Practices','Doctors']],
 ['Doctor','doctor@keramos-uat.example','Case Intake',['Validation','Patients','Cases']],
 ['Office Staff','office.staff@keramos-uat.example','Case Intake',['Validation','Patients','Cases']],
 ['Sample Laboratory A Owner','owner@sample-lab-a-uat.example','Operations Overview',['Executive Command Center','Validation']]
];
async function clean(page,context){await context.clearCookies();await page.goto('/');await page.evaluate(()=>{localStorage.clear();sessionStorage.clear()});await page.reload();await expect(page.getByRole('heading',{name:'Welcome back'})).toBeVisible();}
async function waitForApplicationData(page,action){const dashboard=page.waitForResponse(response=>response.url().endsWith('/api/dashboard')&&response.request().method()==='GET');const flags=page.waitForResponse(response=>response.url().endsWith('/api/feature-flags')&&response.request().method()==='GET');await action();const[dashboardResponse,flagResponse]=await Promise.all([dashboard,flags]);expect(dashboardResponse.status()).toBe(200);expect(flagResponse.status()).toBe(200);}
async function login(page,emailValue,passwordValue=password,remember=false){await page.getByLabel('Email').fill(emailValue);await page.getByLabel('Password').fill(passwordValue);if(remember)await page.getByLabel('Remember this device').check();const pending=page.waitForResponse(response=>response.url().endsWith('/api/auth/login')&&response.request().method()==='POST');await page.getByRole('button',{name:'Sign in'}).click();const response=await pending;expect(response.status()).toBe(200);await waitForApplicationData(page,()=>page.reload());return response.json();}
async function reloadReady(page){await waitForApplicationData(page,()=>page.reload());}
async function logout(page){const pending=page.waitForResponse(response=>response.url().endsWith('/api/auth/logout')&&response.request().method()==='POST');await page.getByRole('button',{name:'Sign out'}).click();expect((await pending).status()).toBe(204);await expect(page.getByRole('heading',{name:'Welcome back'})).toBeVisible();}
function captureErrors(page){const errors=[];page.on('console',message=>{if(message.type()!=='error')return;const value=message.text();if(!/Failed to load resource: the server responded with a status of (401|403)/.test(value))errors.push(`console:${value}`)});page.on('pageerror',error=>errors.push(`page:${error.message}`));return errors;}
async function browserRequest(page,url,options={}){return page.evaluate(async({url,options})=>{const response=await fetch(url,options);let body=null;try{body=await response.json()}catch{}return{status:response.status,body}}, {url,options});}
async function clickReady(locator,testInfo,label){await expect(locator).toBeVisible();await expect(locator).toBeEnabled();await locator.scrollIntoViewIfNeeded();const evidence=await locator.evaluate(element=>{const rect=element.getBoundingClientRect();const style=getComputedStyle(element);const x=rect.left+rect.width/2,y=rect.top+rect.height/2;const hit=document.elementFromPoint(x,y);return{rect:{x:rect.x,y:rect.y,width:rect.width,height:rect.height,top:rect.top,left:rect.left,bottom:rect.bottom,right:rect.right},viewport:{width:innerWidth,height:innerHeight,scrollX,scrollY},style:{display:style.display,visibility:style.visibility,opacity:style.opacity,pointerEvents:style.pointerEvents,position:style.position,zIndex:style.zIndex},disabled:'disabled'in element?Boolean(element.disabled):false,connected:element.isConnected,hitTarget:hit?{tag:hit.tagName,text:hit.textContent?.trim().slice(0,120),className:typeof hit.className==='string'?hit.className:''}:null,animations:element.getAnimations({subtree:true}).map(animation=>({playState:animation.playState,currentTime:animation.currentTime}))};});await testInfo.attach(`click-readiness-${label.replaceAll(' ','-').toLowerCase()}`,{body:Buffer.from(JSON.stringify(evidence,null,2)),contentType:'application/json'});await locator.click({trial:true});await locator.click();}

test.describe('Sprint 13A persona certification',()=>{
 for(const [persona,email,heading,navigation] of roles){
  test(`${persona} login, landing, navigation, restoration and logout`,async({page,context},testInfo)=>{
   const errors=captureErrors(page);await clean(page,context);const payload=await login(page,email);expect(payload.user.email).toBe(email);
   await expect(page.getByRole('heading',{name:heading,level:1})).toBeVisible();
   for(const label of navigation)await expect(page.getByRole('button',{name:label}).first()).toBeVisible();
   await reloadReady(page);await expect(page.getByRole('heading',{name:heading,level:1})).toBeVisible();
   const target=page.getByRole('button',{name:navigation[0]}).first();await clickReady(target,testInfo,`${persona}-${navigation[0]}`);await expect(page.locator('.ns-context-title h1')).not.toBeEmpty();await expect(page.locator('.ns-workspace-canvas')).not.toContainText('404');
   await logout(page);expect(errors).toEqual([]);
  });
 }
});

test('Remember This Device creates an extended restorable session',async({page,context})=>{await clean(page,context);const payload=await login(page,'tenant.owner@keramos-uat.example',password,true);expect(payload.rememberMe).toBe(true);expect(new Date(payload.expiresAt).getTime()-Date.now()).toBeGreaterThan(6*24*60*60*1000);expect((await context.cookies()).find(value=>value.name==='northstar.sid')).toBeDefined();await reloadReady(page);await expect(page.getByRole('heading',{name:'Operations Overview',level:1})).toBeVisible();await logout(page);});

test('password reset is non-disclosing, one-time, revokes sessions and changes credentials',async({page,context})=>{await clean(page,context);const unknown=await browserRequest(page,'/api/auth/password-reset/request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'unknown@uat.example'})});expect(unknown).toEqual({status:202,body:{accepted:true}});const email='sales@keramos-uat.example';await login(page,email);const reset=await browserRequest(page,'/api/auth/password-reset/request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});const token=reset.body.developmentResetToken;const nextPassword=`${password}-Reset`;expect((await browserRequest(page,'/api/auth/password-reset/complete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,password:nextPassword})})).status).toBe(204);await page.reload();await expect(page.getByRole('heading',{name:'Welcome back'})).toBeVisible();await page.getByLabel('Email').fill(email);await page.getByLabel('Password').fill(password);await page.getByRole('button',{name:'Sign in'}).click();await expect(page.getByText('Incorrect email or password.')).toBeVisible();await login(page,email,nextPassword);expect((await browserRequest(page,'/api/auth/password-reset/complete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,password})})).status).toBe(400);});

test('platform administration does not receive tenant operational context',async({page,context})=>{await clean(page,context);const loginResult=await browserRequest(page,'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'platform.owner@northstar-uat.example',password})});expect(loginResult.status).toBe(200);expect((await browserRequest(page,'/api/dashboard')).status).toBe(403);expect((await browserRequest(page,'/api/patients')).status).toBe(403);await context.clearCookies();});

test('tenant-native gateway isolation permits each laboratory only its own operational records',async({page,context})=>{await clean(page,context);await login(page,'owner@sample-lab-a-uat.example');const dashboard=await browserRequest(page,'/api/dashboard');expect(dashboard.status).toBe(200);expect(dashboard.body.activePractices).toBe(0);expect((await browserRequest(page,'/api/practices')).status).toBe(200);
 const spoofBody={practiceName:'Spoofed Tenant Dental',status:'active',phone:'555-0191',email:'spoof@example.test',address:'1 Main',city:'Northridge',state:'CA',postalCode:'91324',taxExempt:false,scannerType:'',officeManager:{name:'Spoof',email:'spoof.manager@example.test',phone:'555-0191'},notes:'',tenantId:'00000000-0000-0000-0000-000000000001'};
 expect((await browserRequest(page,'/api/practices',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(spoofBody)})).status).toBe(403);expect((await browserRequest(page,'/api/practices?tenantId=00000000-0000-0000-0000-000000000001')).status).toBe(403);expect((await browserRequest(page,'/api/practices',{headers:{'X-Tenant-ID':'00000000-0000-0000-0000-000000000001'}})).status).toBe(403);
 const createdPractice=await browserRequest(page,'/api/practices',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...spoofBody,practiceName:'Sample Tenant Native Dental',tenantId:undefined})});expect(createdPractice.status).toBe(201);const practiceId=createdPractice.body.id;
 const createdDoctor=await browserRequest(page,'/api/doctors',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({practiceId,firstName:'Sample',lastName:'Doctor',specialty:'General Dentistry',email:'sample.doctor@example.test',phone:'555-0192',status:'active',notes:''})});expect(createdDoctor.status).toBe(201);
 const createdPatient=await browserRequest(page,'/api/patients',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({practiceId,doctorId:createdDoctor.body.id,patientReference:'TENANT-NATIVE-001',firstName:'Sample',lastName:'Patient',dateOfBirth:'1984-06-12',status:'active',notes:''})});expect(createdPatient.status).toBe(201);const patientId=createdPatient.body.id;
 expect((await browserRequest(page,`/api/patients/${patientId}`)).status).toBe(200);const sampleList=await browserRequest(page,'/api/patients?search=TENANT-NATIVE-001');expect(sampleList.status).toBe(200);expect(sampleList.body.map(item=>item.id)).toContain(patientId);expect((await browserRequest(page,'/api/patients/patient-1')).status).toBe(404);expect((await browserRequest(page,'/api/patients/patient-1',{method:'DELETE'})).status).toBe(404);await logout(page);
 await login(page,'tenant.owner@keramos-uat.example');const primaryList=await browserRequest(page,'/api/patients?search=TENANT-NATIVE-001');expect(primaryList.status).toBe(200);expect(primaryList.body.map(item=>item.id)).not.toContain(patientId);expect((await browserRequest(page,`/api/patients/${patientId}`)).status).toBe(404);expect((await browserRequest(page,`/api/patients/${patientId}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({practiceId:'practice-1',doctorId:'doctor-1',patientReference:'ATTEMPTED-CROSS-TENANT-UPDATE',firstName:'No',lastName:'Access',dateOfBirth:'1984-06-12',status:'active',notes:''})})).status).toBe(404);expect((await browserRequest(page,`/api/patients/${patientId}`,{method:'DELETE'})).status).toBe(404);await logout(page);
});

test('administrator loads walkthrough data, ECC and defect lifecycle',async({page,context},testInfo)=>{const errors=captureErrors(page);await clean(page,context);await login(page,'tenant.owner@keramos-uat.example');await clickReady(page.getByRole('button',{name:'Validation',exact:true}),testInfo,'open-validation-workspace');const seeded=page.waitForResponse(response=>response.url().endsWith('/api/uat/seed')&&response.request().method()==='POST');await page.getByRole('button',{name:'Load deterministic scenarios'}).click();expect((await seeded).status()).toBe(201);await expect(page.getByLabel('Validation plan')).toContainText('Release Business Walkthrough',{timeout:15000});await page.getByRole('button',{name:'Report defect'}).click();await page.getByLabel('Title').fill('Browser certification defect');await page.getByLabel('Module').fill('Validation');await page.getByLabel('Description').fill('Validates the complete defect status workflow.');const created=page.waitForResponse(response=>response.url().endsWith('/api/uat/defects')&&response.request().method()==='POST');await page.getByRole('button',{name:'Submit defect'}).click();const defect=await (await created).json();for(const state of['triaged','in-progress','ready-for-retest','verified','closed']){const result=await browserRequest(page,`/api/uat/defects/${defect.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:state})});expect(result.status).toBe(200);expect(result.body.status).toBe(state)}const ecc=page.getByRole('button',{name:'Executive Command Center'});await clickReady(ecc,testInfo,'administrator-ecc');await expect(page.getByText('Cases by department')).toBeVisible();await expect(page.getByText('AR aging preview')).toBeVisible();expect(errors).toEqual([]);});

test('tenant feature flag hides ECC without bypassing authorization',async({page,context})=>{await clean(page,context);await login(page,'tenant.owner@keramos-uat.example');for(const enabled of[false,true]){expect((await browserRequest(page,'/api/feature-flags/ecc',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled,description:'UAT navigation gate',environments:['uat','development'],roles:[]})})).status).toBe(200);await reloadReady(page);if(enabled)await expect(page.getByRole('button',{name:'Executive Command Center'})).toBeVisible();else await expect(page.getByRole('button',{name:'Executive Command Center'})).not.toBeVisible();}});

for(const viewport of[{name:'laptop',width:1280,height:800},{name:'tablet',width:768,height:1024},{name:'mobile',width:390,height:844}])test(`responsive validation workspace at ${viewport.name}`,async({page,context},testInfo)=>{await page.setViewportSize({width:viewport.width,height:viewport.height});await clean(page,context);await login(page,'tenant.owner@keramos-uat.example');await clickReady(page.getByRole('button',{name:'Open validation'}),testInfo,`responsive-${viewport.name}-validation`);await expect(page.locator('.ns-context-title h1')).toHaveCount(1);await expect(page.getByRole('button',{name:'Load deterministic scenarios'})).toBeVisible();});
