import { expect, test } from '@playwright/test';

const password=process.env.NORTHSTAR_UAT_PASSWORD;
if(!password)throw new Error('NORTHSTAR_UAT_PASSWORD is required.');
const roles=[
 ['Platform Owner','platform.owner@northstar-uat.example','Laboratory Status',['Executive Command Center','UAT Workspace','Intake Administration']],
 ['Tenant Owner','tenant.owner@keramos-uat.example','Laboratory Status',['Executive Command Center','UAT Workspace','Intake Administration']],
 ['Tenant Administrator','tenant.admin@keramos-uat.example','Laboratory Status',['Executive Command Center','UAT Workspace','Intake Administration']],
 ['Customer Service','customer.service@keramos-uat.example','Laboratory Status',['UAT Workspace','Digital Intake','Cases']],
 ['CAD Designer','cad.designer@keramos-uat.example','Production Workflow',['UAT Workspace','Cases','Production']],
 ['QC Technician','qc.technician@keramos-uat.example','Quality Control',['UAT Workspace','Production','Quality Control']],
 ['Production Technician','production.technician@keramos-uat.example','Production Workflow',['UAT Workspace','Cases','Production']],
 ['Shipping','shipping@keramos-uat.example','Shipping & Logistics',['UAT Workspace','Cases','Shipping']],
 ['Accounting','accounting@keramos-uat.example','Billing & Financial Engine',['UAT Workspace','Billing']],
 ['Sales','sales@keramos-uat.example','Laboratory Status',['UAT Workspace','Practices','Doctors']],
 ['Doctor','doctor@keramos-uat.example','Case Intake',['UAT Workspace','Patients','Cases']],
 ['Office Staff','office.staff@keramos-uat.example','Case Intake',['UAT Workspace','Patients','Cases']],
 ['Sample Laboratory A Owner','owner@sample-lab-a-uat.example','Laboratory Status',['Executive Command Center','UAT Workspace']]
];
async function clean(page,context){await context.clearCookies();await page.goto('/');await page.evaluate(()=>{localStorage.clear();sessionStorage.clear()});await page.reload();}
async function login(page,emailValue,passwordValue=password,remember=false){await page.getByLabel('Email').fill(emailValue);await page.getByLabel('Password').fill(passwordValue);if(remember)await page.getByLabel('Remember this device').check();const pending=page.waitForResponse(response=>response.url().endsWith('/api/auth/login')&&response.request().method()==='POST');await page.getByRole('button',{name:'Sign in'}).click();const response=await pending;expect(response.status()).toBe(200);return response.json();}
async function logout(page){const pending=page.waitForResponse(response=>response.url().endsWith('/api/auth/logout')&&response.request().method()==='POST');await page.getByRole('button',{name:'Sign out'}).click();expect((await pending).status()).toBe(204);await expect(page.getByRole('heading',{name:'Welcome back'})).toBeVisible();}
function captureErrors(page){const errors=[];page.on('console',message=>{if(message.type()!=='error')return;const value=message.text();if(!/Failed to load resource: the server responded with a status of (401|403)/.test(value))errors.push(`console:${value}`)});page.on('pageerror',error=>errors.push(`page:${error.message}`));return errors;}
async function browserRequest(page,url,options={}){return page.evaluate(async({url,options})=>{const response=await fetch(url,options);let body=null;try{body=await response.json()}catch{}return{status:response.status,body}}, {url,options});}

test.describe('Sprint 13A persona certification',()=>{
 for(const [persona,email,heading,navigation] of roles){
  test(`${persona} login, landing, navigation, restoration and logout`,async({page,context})=>{
   const errors=captureErrors(page);await clean(page,context);const payload=await login(page,email);expect(payload.user.email).toBe(email);
   await expect(page.getByRole('heading',{name:heading,level:1})).toBeVisible();
   for(const label of navigation)await expect(page.getByRole('button',{name:label,exact:true})).toBeVisible();
   await page.reload();await expect(page.getByRole('heading',{name:heading,level:1})).toBeVisible();
   await page.getByRole('button',{name:navigation[0],exact:true}).click();await expect(page.locator('main h1')).not.toBeEmpty();await expect(page.locator('main')).not.toContainText('404');
   await logout(page);expect(errors).toEqual([]);
  });
 }
});

test('Remember This Device creates an extended restorable session',async({page,context})=>{await clean(page,context);const payload=await login(page,'tenant.owner@keramos-uat.example',password,true);expect(payload.rememberMe).toBe(true);expect(new Date(payload.expiresAt).getTime()-Date.now()).toBeGreaterThan(6*24*60*60*1000);expect((await context.cookies()).find(value=>value.name==='northstar.sid')).toBeDefined();await page.reload();await expect(page.getByRole('heading',{name:'Laboratory Status',level:1})).toBeVisible();await logout(page);});

test('password reset is non-disclosing, one-time, revokes sessions and changes credentials',async({page,context})=>{await clean(page,context);const unknown=await browserRequest(page,'/api/auth/password-reset/request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'unknown@uat.example'})});expect(unknown).toEqual({status:202,body:{accepted:true}});const email='sales@keramos-uat.example';await login(page,email);const reset=await browserRequest(page,'/api/auth/password-reset/request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});const token=reset.body.developmentResetToken;const nextPassword=`${password}-Reset`;expect((await browserRequest(page,'/api/auth/password-reset/complete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,password:nextPassword})})).status).toBe(204);await page.reload();await expect(page.getByRole('heading',{name:'Welcome back'})).toBeVisible();await page.getByLabel('Email').fill(email);await page.getByLabel('Password').fill(password);await page.getByRole('button',{name:'Sign in'}).click();await expect(page.getByText('Incorrect email or password.')).toBeVisible();await login(page,email,nextPassword);expect((await browserRequest(page,'/api/auth/password-reset/complete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,password})})).status).toBe(400);});

test('tenant isolation denies Sample Laboratory access to Keramos operational data',async({page,context})=>{await clean(page,context);await login(page,'owner@sample-lab-a-uat.example');const dashboard=await browserRequest(page,'/api/dashboard');expect(dashboard.status).toBe(200);expect(dashboard.body.activePractices).toBe(0);expect(dashboard.body.activeDoctors).toBe(0);expect((await browserRequest(page,'/api/practices')).status).toBe(403);expect((await browserRequest(page,'/api/uat/plans')).body).toEqual([]);await logout(page);});

test('administrator loads walkthrough data, ECC and defect lifecycle',async({page,context})=>{const errors=captureErrors(page);await clean(page,context);await login(page,'tenant.owner@keramos-uat.example');await page.getByRole('button',{name:'UAT Workspace'}).click();const seeded=page.waitForResponse(response=>response.url().endsWith('/api/uat/seed')&&response.request().method()==='POST');await page.getByRole('button',{name:'Load deterministic scenarios'}).click();expect((await seeded).status()).toBe(201);await expect(page.getByLabel('Test plan')).toContainText('Sprint 13A Business Walkthrough',{timeout:15000});await page.getByRole('button',{name:'Report defect'}).click();await page.getByLabel('Title').fill('Browser certification defect');await page.getByLabel('Module').fill('UAT');await page.getByLabel('Description').fill('Validates the complete defect status workflow.');const created=page.waitForResponse(response=>response.url().endsWith('/api/uat/defects')&&response.request().method()==='POST');await page.getByRole('button',{name:'Submit defect'}).click();const defect=await (await created).json();for(const state of['triaged','in-progress','ready-for-retest','verified','closed']){const result=await browserRequest(page,`/api/uat/defects/${defect.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:state})});expect(result.status).toBe(200);expect(result.body.status).toBe(state)}await page.getByRole('button',{name:'Executive Command Center'}).click();await expect(page.getByText('Cases by department')).toBeVisible();await expect(page.getByText('AR aging preview')).toBeVisible();expect(errors).toEqual([]);});

test('tenant feature flag hides ECC without bypassing authorization',async({page,context})=>{await clean(page,context);await login(page,'tenant.owner@keramos-uat.example');for(const enabled of[false,true]){expect((await browserRequest(page,'/api/feature-flags/ecc',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled,description:'UAT navigation gate',environments:['uat','development'],roles:[]})})).status).toBe(200);await page.reload();if(enabled)await expect(page.getByRole('button',{name:'Executive Command Center'})).toBeVisible();else await expect(page.getByRole('button',{name:'Executive Command Center'})).not.toBeVisible();}});

for(const viewport of[{name:'laptop',width:1280,height:800},{name:'tablet',width:768,height:1024},{name:'mobile',width:390,height:844}])test(`responsive UAT workspace at ${viewport.name}`,async({page,context})=>{await page.setViewportSize({width:viewport.width,height:viewport.height});await clean(page,context);await login(page,'tenant.owner@keramos-uat.example');await page.getByRole('button',{name:'Execute UAT'}).evaluate(element=>element.click());await expect(page.getByRole('heading',{name:'User Acceptance Testing',level:1})).toBeVisible();await expect(page.getByRole('button',{name:'Load deterministic scenarios'})).toBeVisible();});