import { ChangeEvent, useEffect, useState } from 'react';
import { ClinicalCase } from '@northstar/shared';
type ApiError={error?:string;errors?:string[]};
async function api<T>(url:string,options?:RequestInit):Promise<T>{const response=await fetch(url,{...options,headers:{'Content-Type':'application/json',...(options?.headers??{})}});if(!response.ok){const payload=await response.json().catch(()=>({})) as ApiError;throw new Error(payload.errors?.join(' ')||payload.error||`Request failed with ${response.status}.`);}return response.status===204?undefined as T:response.json() as Promise<T>;}

type Reason={id:string;code:string;label:string;category:string;pausesTat?:boolean};
type Operations={intake?:{intakeMethod:string;lifecycleState:string;currentCalculatedDueDate?:string|null};files:Array<{id:string;displayName:string;documentCategory:string;sourceKind:string;availabilityState:string;uploadedAt:string}>;fulfillment:Array<{lineId:string;productSku:string;productName:string;fulfillmentMode?:string;vendorName?:string}>;packages:Array<{id:string;vendorName:string;packageStatus:string}>};
const methods=[['DIGITAL','Digital'],['PHYSICAL','Physical'],['HYBRID','Hybrid']] as const;
const categories=['LAB_SLIP','PDF','PHOTO','STL','OBJ','PLY','DICOM_CBCT','X_RAY','PHOTOGRAMMETRY','INSTRUCTIONS','VENDOR_DOCUMENT','SCAN','QC_RECORD','SHIPPING_DOCUMENT','OTHER'];

export function CaseOperationsPanel({cases,onChanged}:{cases:ClinicalCase[];onChanged:()=>void}){
 const [caseId,setCaseId]=useState(''),[submissionId,setSubmissionId]=useState(''),[data,setData]=useState<Operations|null>(null),[holds,setHolds]=useState<Reason[]>([]),[cancels,setCancels]=useState<Reason[]>([]),[reasonId,setReasonId]=useState(''),[note,setNote]=useState(''),[file,setFile]=useState<File|null>(null),[category,setCategory]=useState('LAB_SLIP'),[message,setMessage]=useState('');
 const selected=cases.find(item=>item.id===caseId);
 const load=async(id=caseId)=>{if(!id){setData(null);return;}try{const [operations,holdReasons,cancellationReasons]=await Promise.all([api<Operations>(`/api/cases/${id}/operations`),api<Reason[]>('/api/case-operations/hold-reasons'),api<Reason[]>('/api/case-operations/cancellation-reasons')]);setData(operations);setHolds(holdReasons);setCancels(cancellationReasons);}catch(error){setMessage(error instanceof Error?error.message:'Unable to load operational Case data.');}};
 useEffect(()=>{void load();},[caseId]);
 const mutate=async(path:string,body:unknown,method='POST')=>{try{await api(path,{method,body:JSON.stringify(body)});setMessage('Saved.');await load();onChanged();}catch(error){setMessage(error instanceof Error?error.message:'Unable to save operational Case data.');}};
 const upload=async()=>{if(!file||!caseId)return;const contentBase64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error('Unable to read the selected file.'));reader.onload=()=>resolve(String(reader.result).split(',')[1]??'');reader.readAsDataURL(file);});await mutate(`/api/cases/${caseId}/files`,{fileName:file.name,displayName:file.name,mimeType:file.type,documentCategory:category,contentBase64});setFile(null);};
 return <section className="card case-operations" aria-label="Case operations"><div className="section-heading"><div><p className="eyebrow">Operational case intake</p><h2>Case Operations</h2><p>Controlled intake, lifecycle, permanent Case Files, fulfillment, and vendor-package preparation.</p></div></div>
 <label>Existing Case<select value={caseId} onChange={event=>setCaseId(event.target.value)}><option value="">Select a Case</option>{cases.map(item=><option key={item.id} value={item.id}>{item.caseNumber} — {item.restoration}</option>)}</select></label>
 {selected&&data&&<div className="operations-grid"><div className="card"><h3>Intake & lifecycle</h3><p><strong>{data.intake?.lifecycleState?.replaceAll('_',' ')}</strong> · Due {data.intake?.currentCalculatedDueDate??'Not calculated'}</p><label>Case Intake Method<select value={data.intake?.intakeMethod??'DIGITAL'} onChange={event=>void mutate(`/api/cases/${caseId}/intake-method`,{intakeMethod:event.target.value},'PUT')}>{data.intake?.intakeMethod==='UNKNOWN'&&<option value="UNKNOWN" disabled>Unknown (historical)</option>}{methods.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Universal Intake submission<input aria-label="Universal Intake submission ID" value={submissionId} onChange={event=>setSubmissionId(event.target.value)} placeholder="Submission ID from Digital Intake Platform"/></label><button disabled={!submissionId.trim()} onClick={()=>{void mutate(`/api/cases/${caseId}/intake-submissions`,{submissionId:submissionId.trim()});setSubmissionId('')}}>Link Universal Intake</button><label>Hold reason<select value={reasonId} onChange={event=>setReasonId(event.target.value)}><option value="">Select controlled reason</option>{holds.map(reason=><option key={reason.id} value={reason.id}>{reason.code} — {reason.label}{reason.pausesTat?' (pauses TAT)':''}</option>)}</select></label><label>Operational note<textarea value={note} onChange={event=>setNote(event.target.value)} /></label><div className="actions"><button disabled={!reasonId||data.intake?.lifecycleState==='CANCELLED'} onClick={()=>void mutate(`/api/cases/${caseId}/hold`,{reasonId,notes:note})}>Place on hold</button><button disabled={data.intake?.lifecycleState!=='ON_HOLD'} onClick={()=>void mutate(`/api/cases/${caseId}/release-hold`,{note})}>Release hold</button></div><label>Cancel reason<select value={reasonId} onChange={event=>setReasonId(event.target.value)}><option value="">Select controlled reason</option>{cancels.map(reason=><option key={reason.id} value={reason.id}>{reason.code} — {reason.label}</option>)}</select></label><button className="danger" disabled={!reasonId||data.intake?.lifecycleState==='CANCELLED'} onClick={()=>{if(window.confirm('Cancel this Case? The Case, files, lineage, and snapshots will be preserved.'))void mutate(`/api/cases/${caseId}/cancel`,{reasonId,notes:note,confirmed:true});}}>Cancel Case</button></div>
 <div className="card"><h3>Case Files / Documents</h3><p>Stored in tenant-isolated durable storage. Original sources are immutable; archive retains history.</p><label>Document category<select value={category} onChange={event=>setCategory(event.target.value)}>{categories.map(value=><option key={value} value={value}>{value.replaceAll('_',' ')}</option>)}</select></label><label>File<input type="file" onChange={(event:ChangeEvent<HTMLInputElement>)=>setFile(event.target.files?.[0]??null)} /></label><button disabled={!file} onClick={()=>void upload()}>Upload Case File</button><ul className="compact-list">{data.files.map(item=><li key={item.id}><strong>{item.displayName}</strong> <small>{item.documentCategory.replaceAll('_',' ')} · {item.sourceKind} · {item.availabilityState}</small>{item.documentCategory==='PHOTO'&&<small>Shade photo: Attached</small>}<a href={`/api/cases/${caseId}/files/${item.id}/download`}>Download</a></li>)}</ul></div>
 <div className="card"><h3>Fulfillment & Vendor Package</h3><p>Packages remain READY until a configured secure provider workflow sends them.</p>{data.fulfillment.map(line=><div className="inline-row" key={line.lineId}><span>{line.productSku} — {line.productName}</span><select defaultValue={line.fulfillmentMode??'IN_HOUSE'} onChange={event=>void mutate(`/api/cases/${caseId}/product-lines/${line.lineId}/fulfillment`,{fulfillmentMode:event.target.value,vendorName:event.target.value==='IN_HOUSE'?'':window.prompt('Vendor name')??''},'PUT')}><option value="IN_HOUSE">In-house</option><option value="OUTSOURCED">Outsourced</option><option value="SPLIT_HYBRID">Split / Hybrid</option></select></div>)}<button disabled={!data.fulfillment.length} onClick={()=>void mutate(`/api/cases/${caseId}/vendor-packages`,{vendorName:window.prompt('Vendor name')??'',deliveryChannel:'VENDOR_PORTAL',productLineIds:data.fulfillment.map(line=>line.lineId),fileIds:data.files.filter(file=>file.availabilityState==='AVAILABLE').map(file=>file.id)})}>Prepare Vendor Package</button><ul className="compact-list">{data.packages.map(item=><li key={item.id}>{item.vendorName} — {item.packageStatus}</li>)}</ul></div></div>}
 {message&&<p role="status">{message}</p>}</section>;
}
