import { ChangeEvent, FormEvent, useEffect, useState } from 'react';

type EntityType='practice'|'doctor'|'patient'|'case'|'shipment'|'invoice';
type EventType='phone-call'|'email'|'internal-note'|'doctor-message'|'laboratory-message'|'production-update'|'qc-comment'|'shipping-event'|'billing-event'|'attachment'|'system-event';
type TimelineEvent={id:string;eventType:EventType;content:string;actorName:string;actorRole:string;occurredAt:string;attachments:Array<{id:string;fileName:string;mimeType:string;size:number}>};
type Attachment={fileName:string;mimeType:string;kind:'stl'|'obj'|'ply'|'dicom'|'clinical-photo'|'rx-pdf'|'shipping-document'|'invoice-pdf';contentBase64:string};
const kinds:Record<string,Attachment['kind']>={stl:'stl',obj:'obj',ply:'ply',dcm:'dicom',dicom:'dicom',jpg:'clinical-photo',jpeg:'clinical-photo',png:'clinical-photo',webp:'clinical-photo',pdf:'rx-pdf'};

async function fileInput(file:File):Promise<Attachment>{const contentBase64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]??'');reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)});const extension=file.name.split('.').pop()?.toLowerCase()??'';return{fileName:file.name,mimeType:file.type||'application/octet-stream',kind:kinds[extension]??'clinical-photo',contentBase64}}

export function CommunicationTimeline({entityType,entityId,title='Communication timeline'}:{entityType:EntityType;entityId:string;title?:string}){
 const[events,setEvents]=useState<TimelineEvent[]>([]),[content,setContent]=useState(''),[eventType,setEventType]=useState<EventType>('internal-note'),[attachment,setAttachment]=useState<Attachment|null>(null),[error,setError]=useState(''),[saving,setSaving]=useState(false),[open,setOpen]=useState(false);
 const load=async()=>{const response=await fetch(`/api/communications/timeline?entityType=${entityType}&entityId=${encodeURIComponent(entityId)}`);if(!response.ok)throw new Error('Unable to load communication timeline.');setEvents(await response.json() as TimelineEvent[])};
 useEffect(()=>{if(open)void load().catch(error=>setError(error instanceof Error?error.message:'Unable to load communications.'))},[open,entityType,entityId]);
 const submit=async(event:FormEvent)=>{event.preventDefault();if(!content.trim())return;setSaving(true);setError('');try{const response=await fetch('/api/communications/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({entityType,entityId,eventType,content,attachments:attachment?[attachment]:[]})});if(!response.ok){const payload=await response.json().catch(()=>({})) as{error?:string};throw new Error(payload.error||'Unable to record communication.')}setContent('');setAttachment(null);await load()}catch(error){setError(error instanceof Error?error.message:'Unable to record communication.')}finally{setSaving(false)}};
 const choose=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(file)setAttachment(await fileInput(file));event.target.value=''};
 return <section className="communications-platform"><button type="button" onClick={()=>setOpen(value=>!value)} aria-expanded={open}>{open?'Hide':'View'} {title}</button>{open&&<><form onSubmit={submit} className="communications"><label>Event type<select aria-label={`${entityType} communication type`} value={eventType} onChange={e=>setEventType(e.target.value as EventType)}><option value="internal-note">Internal note</option><option value="phone-call">Phone call</option><option value="email">Email</option><option value="doctor-message">Doctor message</option><option value="laboratory-message">Laboratory message</option><option value="production-update">Production update</option><option value="qc-comment">QC comment</option><option value="shipping-event">Shipping event</option><option value="billing-event">Billing event</option></select></label><label>Communication<textarea aria-label={`${entityType} communication`} value={content} onChange={e=>setContent(e.target.value)} required/></label><label>Attachment<input aria-label={`${entityType} communication attachment`} type="file" onChange={choose}/></label>{attachment&&<small>{attachment.fileName}</small>}<button type="submit" disabled={saving}>{saving?'Recording…':'Record communication'}</button></form>{error&&<p className="error" role="alert">{error}</p>}<div className="communication-timeline" aria-label={`${entityType} communication timeline`}>{events.length===0?<p className="note">No communication history.</p>:events.map(item=><article key={item.id} className="audit-row"><strong>{item.eventType.replaceAll('-',' ')}</strong><p>{item.content}</p><small>{new Date(item.occurredAt).toLocaleString()} · {item.actorName} · {item.actorRole}</small>{item.attachments.map(file=><small key={file.id}>{file.fileName} · {Math.ceil(file.size/1024)} KB</small>)}</article>)}</div></>}</section>
}
