import { FormEvent, useEffect, useMemo, useState } from 'react';
import type { CommunicationEntry, Doctor, DoctorInput, EntityStatus, Practice, PracticeInput } from '@northstar/shared';

type Props = { onCountsChanged: () => void };
type ApiError = { error?: string; errors?: string[] };

async function api<T>(url: string, options?: RequestInit): Promise<T> {
  const response = await fetch(url, { ...options, headers: { 'Content-Type': 'application/json', ...(options?.headers ?? {}) } });
  if (!response.ok) {
    const payload = await response.json().catch(() => ({})) as ApiError;
    throw new Error(payload.errors?.join(' ') || payload.error || `Request failed with ${response.status}.`);
  }
  return response.status === 204 ? undefined as T : response.json() as Promise<T>;
}

const emptyManager = { name: '', email: '', phone: '' };
const emptyPractice: PracticeInput = { practiceName: '', status: 'active', phone: '', email: '', address: '', city: '', state: 'CA', postalCode: '', taxExempt: false, scannerType: '', officeManager: emptyManager, notes: '' };
const emptyDoctor = (practiceId = ''): DoctorInput => ({ practiceId, firstName: '', lastName: '', specialty: 'General Dentistry', email: '', phone: '', status: 'active', notes: '' });

function StatusFilter({ value, onChange }:{ value:string; onChange:(value:string)=>void }) {
  return <select aria-label="Status filter" value={value} onChange={event=>onChange(event.target.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select>;
}

function Communications({ entries, onAdd }:{ entries:CommunicationEntry[]; onAdd:(summary:string)=>Promise<void> }) {
  const [summary,setSummary]=useState(''); const [saving,setSaving]=useState(false);
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!summary.trim())return;setSaving(true);try{await onAdd(summary);setSummary('')}finally{setSaving(false)}};
  return <div className="communications"><form onSubmit={submit}><label>Communication note<input aria-label="Communication note" value={summary} onChange={event=>setSummary(event.target.value)} required/></label><button type="submit" disabled={saving}>{saving?'Saving…':'Add communication'}</button></form>{entries.length===0?<p className="note">No communication history.</p>:entries.map(entry=><div className="audit-row" key={entry.id}><strong>{entry.type}</strong> — {entry.summary}<small>{new Date(entry.occurredAt).toLocaleString()} · {entry.createdBy}</small></div>)}</div>;
}

export function PracticeManagement({ onCountsChanged }:Props) {
  const [items,setItems]=useState<Practice[]>([]); const [query,setQuery]=useState(''); const [status,setStatus]=useState('all'); const [editing,setEditing]=useState<Practice|null>(null); const [form,setForm]=useState<PracticeInput>(emptyPractice); const [error,setError]=useState(''); const [loading,setLoading]=useState(true);
  const load=async()=>{setLoading(true);try{setItems(await api<Practice[]>(`/api/practices?search=${encodeURIComponent(query)}&status=${status}`));setError('')}catch(error){setError(error instanceof Error?error.message:'Unable to load practices.')}finally{setLoading(false)}};
  useEffect(()=>{void load()},[query,status]);
  const startNew=()=>{setEditing(null);setForm(emptyPractice)};
  const startEdit=(item:Practice)=>{setEditing(item);setForm({ practiceName:item.practiceName,status:item.status,phone:item.phone,email:item.email,address:item.address,city:item.city,state:item.state,postalCode:item.postalCode,taxExempt:item.taxExempt,scannerType:item.scannerType,officeManager:item.officeManager,notes:item.notes })};
  const save=async(event:FormEvent)=>{event.preventDefault();try{await api<Practice>(editing?`/api/practices/${editing.id}`:'/api/practices',{method:editing?'PUT':'POST',body:JSON.stringify(form)});startNew();await load();onCountsChanged();setError('')}catch(error){setError(error instanceof Error?error.message:'Unable to save practice.')}};
  const remove=async(item:Practice)=>{if(!confirm(`Delete ${item.practiceName}?`))return;try{await api<void>(`/api/practices/${item.id}`,{method:'DELETE'});await load();onCountsChanged()}catch(error){setError(error instanceof Error?error.message:'Unable to delete practice.')}};
  const addCommunication=async(item:Practice,summary:string)=>{await api(`/api/practices/${item.id}/communications`,{method:'POST',body:JSON.stringify({type:'note',summary})});await load()};
  return <section className="panel"><div className="panel-heading"><div><p className="eyebrow">PRACTICE CRM</p><h2>Practice Management</h2></div><button className="primary" onClick={startNew}>New practice</button></div><div className="filters"><input aria-label="Search practices" className="search" placeholder="Search by account, practice, email, or manager" value={query} onChange={event=>setQuery(event.target.value)}/><StatusFilter value={status} onChange={setStatus}/></div>{error&&<p className="error" role="alert">{error}</p>}
  <form className="form-grid" onSubmit={save}><label>Practice name<input aria-label="Practice name" value={form.practiceName} onChange={e=>setForm({...form,practiceName:e.target.value})} required/></label><label>Status<select aria-label="Practice status" value={form.status} onChange={e=>setForm({...form,status:e.target.value as EntityStatus})}><option value="active">Active</option><option value="inactive">Inactive</option></select></label><label>Phone<input aria-label="Practice phone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} required/></label><label>Email<input aria-label="Practice email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label><label>Address<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label>City<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>State<input value={form.state} onChange={e=>setForm({...form,state:e.target.value})}/></label><label>Postal code<input value={form.postalCode} onChange={e=>setForm({...form,postalCode:e.target.value})}/></label><label>Scanner type<input value={form.scannerType} onChange={e=>setForm({...form,scannerType:e.target.value})}/></label><label>Office manager name<input aria-label="Office manager name" value={form.officeManager.name} onChange={e=>setForm({...form,officeManager:{...form.officeManager,name:e.target.value}})} required/></label><label>Office manager email<input aria-label="Office manager email" type="email" value={form.officeManager.email} onChange={e=>setForm({...form,officeManager:{...form.officeManager,email:e.target.value}})} required/></label><label>Office manager phone<input value={form.officeManager.phone} onChange={e=>setForm({...form,officeManager:{...form.officeManager,phone:e.target.value}})}/></label><label className="checkbox"><input type="checkbox" checked={form.taxExempt} onChange={e=>setForm({...form,taxExempt:e.target.checked})}/>Tax exempt</label><label>Notes<textarea aria-label="Practice notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="primary" type="submit">{editing?'Update practice':'Create practice'}</button></form>
  {loading?<p>Loading practices…</p>:<div className="table"><div className="table-head"><span>Account</span><span>Practice</span><span>Manager</span><span>Status</span><span>Actions</span></div>{items.map(item=><div className="table-row" key={item.id}><span>{item.accountNumber}</span><strong>{item.practiceName}<small>{item.email}</small></strong><span>{item.officeManager.name}<small>{item.officeManager.email}</small></span><span className="badge">{item.status}</span><span className="actions"><button onClick={()=>startEdit(item)}>Edit</button><button className="danger" onClick={()=>void remove(item)}>Delete</button></span><Communications entries={item.communicationHistory} onAdd={summary=>addCommunication(item,summary)}/></div>)}</div>}</section>;
}

export function DoctorManagement({ onCountsChanged }:Props) {
  const [practices,setPractices]=useState<Practice[]>([]); const [items,setItems]=useState<Doctor[]>([]); const [query,setQuery]=useState(''); const [status,setStatus]=useState('all'); const [practiceId,setPracticeId]=useState(''); const [editing,setEditing]=useState<Doctor|null>(null); const [form,setForm]=useState<DoctorInput>(emptyDoctor()); const [error,setError]=useState('');
  const load=async()=>{try{const [practiceRows,doctorRows]=await Promise.all([api<Practice[]>('/api/practices'),api<Doctor[]>(`/api/doctors?search=${encodeURIComponent(query)}&status=${status}&practiceId=${practiceId}`)]);setPractices(practiceRows);setItems(doctorRows);setForm(current=>current.practiceId?current:{...current,practiceId:practiceRows[0]?.id??''});setError('')}catch(error){setError(error instanceof Error?error.message:'Unable to load doctors.')}};
  useEffect(()=>{void load()},[query,status,practiceId]);
  const startNew=()=>{setEditing(null);setForm(emptyDoctor(practices[0]?.id??''))};
  const startEdit=(item:Doctor)=>{setEditing(item);setForm({practiceId:item.practiceId,firstName:item.firstName,lastName:item.lastName,specialty:item.specialty,email:item.email,phone:item.phone,status:item.status,notes:item.notes})};
  const save=async(event:FormEvent)=>{event.preventDefault();try{await api<Doctor>(editing?`/api/doctors/${editing.id}`:'/api/doctors',{method:editing?'PUT':'POST',body:JSON.stringify(form)});startNew();await load();onCountsChanged();setError('')}catch(error){setError(error instanceof Error?error.message:'Unable to save doctor.')}};
  const remove=async(item:Doctor)=>{if(!confirm(`Delete Dr. ${item.lastName}?`))return;try{await api<void>(`/api/doctors/${item.id}`,{method:'DELETE'});await load();onCountsChanged()}catch(error){setError(error instanceof Error?error.message:'Unable to delete doctor.')}};
  const addCommunication=async(item:Doctor,summary:string)=>{await api(`/api/doctors/${item.id}/communications`,{method:'POST',body:JSON.stringify({type:'note',summary})});await load()};
  const practiceName=(id:string)=>practices.find(item=>item.id===id)?.practiceName??'Unknown practice';
  return <section className="panel"><div className="panel-heading"><div><p className="eyebrow">DOCTOR CRM</p><h2>Doctor Management</h2></div><button className="primary" onClick={startNew}>New doctor</button></div><div className="filters"><input aria-label="Search doctors" className="search" placeholder="Search doctors" value={query} onChange={event=>setQuery(event.target.value)}/><StatusFilter value={status} onChange={setStatus}/><select aria-label="Practice filter" value={practiceId} onChange={event=>setPracticeId(event.target.value)}><option value="">All practices</option>{practices.map(item=><option value={item.id} key={item.id}>{item.practiceName}</option>)}</select></div>{error&&<p className="error" role="alert">{error}</p>}
  <form className="form-grid" onSubmit={save}><label>Practice<select aria-label="Doctor practice" value={form.practiceId} onChange={e=>setForm({...form,practiceId:e.target.value})} required>{practices.map(item=><option value={item.id} key={item.id}>{item.practiceName}</option>)}</select></label><label>First name<input aria-label="Doctor first name" value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})} required/></label><label>Last name<input aria-label="Doctor last name" value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})} required/></label><label>Specialty<input value={form.specialty} onChange={e=>setForm({...form,specialty:e.target.value})}/></label><label>Email<input aria-label="Doctor email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Status<select aria-label="Doctor status" value={form.status} onChange={e=>setForm({...form,status:e.target.value as EntityStatus})}><option value="active">Active</option><option value="inactive">Inactive</option></select></label><label>Notes<textarea aria-label="Doctor notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="primary" type="submit">{editing?'Update doctor':'Create doctor'}</button></form>
  <div className="table"><div className="table-head"><span>Doctor</span><span>Practice</span><span>Specialty</span><span>Status</span><span>Actions</span></div>{items.map(item=><div className="table-row" key={item.id}><strong>Dr. {item.firstName} {item.lastName}<small>{item.email}</small></strong><span>{practiceName(item.practiceId)}</span><span>{item.specialty}</span><span className="badge">{item.status}</span><span className="actions"><button onClick={()=>startEdit(item)}>Edit</button><button className="danger" onClick={()=>void remove(item)}>Delete</button></span><Communications entries={item.communicationHistory} onAdd={summary=>addCommunication(item,summary)}/></div>)}</div></section>;
}
