import { FormEvent, useEffect, useState } from 'react';
import type { Doctor, Practice } from '@northstar/shared';

type Route='internal'|'outsourced'|'hybrid'|'manual-review';
type DoctorPreference={id:string;doctor_id:string;practice_id:string;defaults:Record<string,unknown>;preferred_route:Route|null;preferred_outsource_partner:string|null;version:number;active:boolean};
type PracticeRouting={id:string;practice_id:string;preferred_route:Route;preferred_outsource_partner:string|null;active:boolean};
type TenantRouting={preferred_route:Route;preferred_outsource_partner:string|null}|null;
type PricingSchedule={id:string;schedule_type:string;name:string;practice_id:string|null;priority:number;active:boolean};
const routes:Route[]=['internal','outsourced','hybrid','manual-review'];
async function api<T>(url:string,options?:RequestInit):Promise<T>{const response=await fetch(url,{...options,headers:{'Content-Type':'application/json',...(options?.headers??{})}});const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.error??`Request failed with ${response.status}.`);return body as T}

export function IntakeAdministration(){
 const[practices,setPractices]=useState<Practice[]>([]),[doctors,setDoctors]=useState<Doctor[]>([]),[preferences,setPreferences]=useState<DoctorPreference[]>([]),[practiceRoutes,setPracticeRoutes]=useState<PracticeRouting[]>([]),[tenantRoute,setTenantRoute]=useState<TenantRouting>(null),[schedules,setSchedules]=useState<PricingSchedule[]>([]),[error,setError]=useState('');
 const load=async()=>{try{const[p,d,dp,pr,tr,ps]=await Promise.all([api<Practice[]>('/api/practices'),api<Doctor[]>('/api/doctors'),api<DoctorPreference[]>('/api/intake/admin/doctor-preferences'),api<PracticeRouting[]>('/api/intake/admin/practice-routing'),api<TenantRouting>('/api/intake/admin/tenant-routing'),api<PricingSchedule[]>('/api/intake/admin/pricing-schedules')]);setPractices(p);setDoctors(d);setPreferences(dp);setPracticeRoutes(pr);setTenantRoute(tr);setSchedules(ps);setError('')}catch(value){setError(value instanceof Error?value.message:'Unable to load intake administration.')}};
 useEffect(()=>{void load()},[]);
 const saveDoctor=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);await api('/api/intake/admin/doctor-preferences',{method:'POST',body:JSON.stringify({doctorId:data.get('doctorId'),practiceId:data.get('practiceId'),preferredRoute:data.get('preferredRoute'),preferredOutsourcePartner:data.get('partner'),defaults:{material:data.get('material'),marginDesign:data.get('marginDesign'),contacts:data.get('contacts'),occlusion:data.get('occlusion'),productionPreferences:data.get('productionPreferences')}})});event.currentTarget.reset();await load()};
 const savePractice=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget),practiceId=String(data.get('practiceId'));await api(`/api/intake/admin/practice-routing/${practiceId}`,{method:'PUT',body:JSON.stringify({preferredRoute:data.get('preferredRoute'),preferredOutsourcePartner:data.get('partner')})});await load()};
 const saveTenant=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);await api('/api/intake/admin/tenant-routing',{method:'PUT',body:JSON.stringify({preferredRoute:data.get('preferredRoute'),preferredOutsourcePartner:data.get('partner')})});await load()};
 const createSchedule=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);await api('/api/intake/admin/pricing-schedules',{method:'POST',body:JSON.stringify({scheduleType:data.get('scheduleType'),name:data.get('name'),practiceId:data.get('practiceId')||null,priority:Number(data.get('priority')||100)})});event.currentTarget.reset();await load()};
 return <section className="panel"><div className="panel-heading"><div><p className="eyebrow">DIGITAL INTAKE ADMINISTRATION</p><h2>Preferences, routing, and pricing foundations</h2></div></div>{error&&<p className="error" role="alert">{error}</p>}
 <div className="form-grid"><form onSubmit={saveDoctor}><h3>Doctor Preference Profile</h3><label>Practice<select name="practiceId" aria-label="Preference practice" required>{practices.map(item=><option key={item.id} value={item.id}>{item.practiceName}</option>)}</select></label><label>Doctor<select name="doctorId" aria-label="Preference doctor" required>{doctors.map(item=><option key={item.id} value={item.id}>Dr. {item.firstName} {item.lastName}</option>)}</select></label><label>Preferred material<input name="material" aria-label="Preferred material"/></label><label>Preferred margin<input name="marginDesign" aria-label="Preferred margin"/></label><label>Contacts<input name="contacts" aria-label="Preferred contacts"/></label><label>Occlusion<input name="occlusion" aria-label="Preferred occlusion"/></label><label>Production preferences<textarea name="productionPreferences" aria-label="Production preferences"/></label><label>Preferred route<select name="preferredRoute" aria-label="Doctor preferred route">{routes.map(value=><option key={value}>{value}</option>)}</select></label><label>Preferred outsourcing partner<input name="partner" aria-label="Doctor outsourcing partner"/></label><button className="primary" type="submit">Save Doctor preferences</button></form>
 <form onSubmit={savePractice}><h3>Practice Routing Profile</h3><label>Practice<select name="practiceId" aria-label="Routing practice" required>{practices.map(item=><option key={item.id} value={item.id}>{item.practiceName}</option>)}</select></label><label>Preferred route<select name="preferredRoute" aria-label="Practice preferred route">{routes.map(value=><option key={value}>{value}</option>)}</select></label><label>Outsourcing partner<input name="partner" aria-label="Practice outsourcing partner"/></label><button className="primary" type="submit">Save Practice routing</button></form>
 <form onSubmit={saveTenant}><h3>Tenant Routing Default</h3><label>Default route<select name="preferredRoute" aria-label="Tenant preferred route" defaultValue={tenantRoute?.preferred_route??'internal'}>{routes.map(value=><option key={value}>{value}</option>)}</select></label><label>Default outsourcing partner<input name="partner" aria-label="Tenant outsourcing partner" defaultValue={tenantRoute?.preferred_outsource_partner??''}/></label><button className="primary" type="submit">Save tenant default</button></form>
 <form onSubmit={createSchedule}><h3>Pricing Schedule Foundation</h3><p className="note">Schedules are managed here; pricing calculation remains owned by Billing.</p><label>Schedule type<select name="scheduleType" aria-label="Pricing schedule type"><option value="standard">Standard</option><option value="contract">Contract</option><option value="promotion">Promotion</option><option value="customer-override">Customer override</option></select></label><label>Name<input name="name" aria-label="Pricing schedule name" required/></label><label>Practice<select name="practiceId" aria-label="Pricing schedule practice"><option value="">Tenant-wide</option>{practices.map(item=><option key={item.id} value={item.id}>{item.practiceName}</option>)}</select></label><label>Priority<input name="priority" aria-label="Pricing schedule priority" type="number" defaultValue="100"/></label><button className="primary" type="submit">Create pricing schedule</button></form></div>
 <h3>Active configuration</h3><div className="table"><div className="table-head"><span>Type</span><span>Owner</span><span>Route / Schedule</span><span>Version / Priority</span></div>{preferences.filter(item=>item.active).map(item=><div className="table-row" key={item.id}><strong>Doctor preference</strong><span>{doctors.find(doctor=>doctor.id===item.doctor_id)?.lastName??item.doctor_id}</span><span>{item.preferred_route??'No route override'}</span><span>v{item.version}</span></div>)}{practiceRoutes.filter(item=>item.active).map(item=><div className="table-row" key={item.id}><strong>Practice routing</strong><span>{practices.find(practice=>practice.id===item.practice_id)?.practiceName??item.practice_id}</span><span>{item.preferred_route}</span><span>Active</span></div>)}{schedules.map(item=><div className="table-row" key={item.id}><strong>{item.schedule_type}</strong><span>{item.practice_id?practices.find(practice=>practice.id===item.practice_id)?.practiceName:'Tenant-wide'}</span><span>{item.name}</span><span>{item.priority}</span></div>)}</div></section>
}
