import { FormEvent, useEffect, useMemo, useState } from 'react';

type Category='FIX'|'REM'|'IMP'|'ORT'|'SLP'|'DIA'|'SPL'|'AUX';
type PricingBasis='PER_UNIT'|'PER_TOOTH'|'PER_PRODUCT'|'PER_ARCH'|'PER_CASE'|'PER_COMPONENT'|'PER_STAGE'|'QUANTITY_BASED';
type Product={id:string;sku:string;productName:string;description:string;categoryCode:Category;familyCode:string;pricingBasis:PricingBasis;defaultTurnaroundBusinessDays:number|null;configuration:Record<string,unknown>;active:boolean;archivedAt:string|null};
type Price={id:string;practice_id:string|null;pricing_basis:PricingBasis;amount:string;effective_from:string;effective_until:string|null;active:boolean;version_note:string};
const categories:Record<Category,string>={FIX:'Fixed Restorations',REM:'Removable Restorations',IMP:'Implant Restorations',ORT:'Orthodontics',SLP:'Sleep Appliances',DIA:'Diagnostics & Digital',SPL:'Splints',AUX:'Auxiliaries'};
const bases:PricingBasis[]=['PER_UNIT','PER_TOOTH','PER_PRODUCT','PER_ARCH','PER_CASE','PER_COMPONENT','PER_STAGE','QUANTITY_BASED'];
async function api<T>(url:string,options?:RequestInit):Promise<T>{const response=await fetch(url,{...options,headers:{'Content-Type':'application/json',...(options?.headers??{})}});const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.error??`Request failed with ${response.status}.`);return body as T;}
const money=(value:string|number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(value));

export function ProductPricingAdministration(){
 const [items,setItems]=useState<Product[]>([]),[selectedCategory,setSelectedCategory]=useState<Category>('FIX'),[selected,setSelected]=useState<Product|null>(null),[prices,setPrices]=useState<Price[]>([]),[error,setError]=useState(''),[showInactive,setShowInactive]=useState(false),[search,setSearch]=useState(''),[saving,setSaving]=useState(false),[editing,setEditing]=useState(false),[newFamilyCode,setNewFamilyCode]=useState('');
 const load=async()=>{try{const result=await api<Product[]>(`/api/products?category=${selectedCategory}${showInactive?'&includeInactive=true':''}${search?`&search=${encodeURIComponent(search)}`:''}`);setItems(result);setSelected(previous=>result.find(item=>item.id===previous?.id)??result[0]??null);setError('');}catch(value){setError(value instanceof Error?value.message:'Unable to load product catalog.');}};
 useEffect(()=>{void load()},[selectedCategory,showInactive,search]);
 useEffect(()=>{if(!selected){setPrices([]);return;}api<Price[]>(`/api/products/${selected.id}/prices`).then(setPrices).catch(value=>setError(value instanceof Error?value.message:'Unable to load price history.'));},[selected]);
 const activeCount=useMemo(()=>items.filter(item=>item.active).length,[items]);
 const familySuggestions=useMemo(()=>[...new Set(items.map(item=>item.familyCode))].sort(),[items]);
 const changeCategory=(value:Category)=>{setSelectedCategory(value);setSelected(null);setEditing(false);setNewFamilyCode('');};
 const addCustom=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);setSaving(true);try{await api('/api/products',{method:'POST',body:JSON.stringify({sku:data.get('sku'),productName:data.get('productName'),description:data.get('description'),categoryCode:selectedCategory,familyCode:data.get('familyCode'),pricingBasis:data.get('pricingBasis'),defaultTurnaroundBusinessDays:data.get('turnaround')?Number(data.get('turnaround')):undefined,configuration:{selection:data.get('selection')}})});event.currentTarget.reset();setNewFamilyCode('');await load();}catch(value){setError(value instanceof Error?value.message:'Unable to create product.');}finally{setSaving(false);}};
 const setLifecycle=async(product:Product,active:boolean)=>{setSaving(true);try{await api(`/api/products/${product.id}/lifecycle`,{method:'POST',body:JSON.stringify({active})});await load();}catch(value){setError(value instanceof Error?value.message:'Unable to update product lifecycle.');}finally{setSaving(false);}};
 const saveEdit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!selected)return;const data=new FormData(event.currentTarget);setSaving(true);try{const updated=await api<Product>(`/api/products/${selected.id}`,{method:'PUT',body:JSON.stringify({productName:data.get('productName'),description:data.get('description'),familyCode:data.get('familyCode'),defaultTurnaroundBusinessDays:data.get('turnaround')?Number(data.get('turnaround')):undefined})});setSelected(updated);setEditing(false);await load();}catch(value){setError(value instanceof Error?value.message:'Unable to update product.');}finally{setSaving(false);}};
 const addPrice=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!selected)return;const data=new FormData(event.currentTarget);setSaving(true);try{await api(`/api/products/${selected.id}/prices`,{method:'POST',body:JSON.stringify({pricingBasis:selected.pricingBasis,amount:Number(data.get('amount')),effectiveFrom:new Date(`${String(data.get('effectiveFrom'))}T00:00:00Z`).toISOString(),effectiveUntil:data.get('effectiveUntil')?new Date(`${String(data.get('effectiveUntil'))}T00:00:00Z`).toISOString():null,versionNote:data.get('versionNote')})});event.currentTarget.reset();setPrices(await api<Price[]>(`/api/products/${selected.id}/prices`));}catch(value){setError(value instanceof Error?value.message:'Unable to save price version.');}finally{setSaving(false);}};
 return <section className="panel"><div className="panel-heading"><div><p className="eyebrow">PRODUCT & PRICING FOUNDATION</p><h2>Tenant Product Catalog</h2><p className="note">Products, lifecycle, effective-dated price versions, and case-line pricing remain tenant-owned and server-enforced.</p></div><span className="badge">{activeCount} active</span></div>{error&&<p className="error" role="alert">{error}</p>}
 <div className="filters"><label>Restoration category<select aria-label="Product category" value={selectedCategory} onChange={event=>changeCategory(event.target.value as Category)}>{Object.entries(categories).map(([code,label])=><option key={code} value={code}>{code} — {label}</option>)}</select></label><label>Search catalog<input aria-label="Search product catalog" value={search} onChange={event=>setSearch(event.target.value)} placeholder="SKU or product name"/></label><label className="checkbox"><input type="checkbox" checked={showInactive} onChange={event=>setShowInactive(event.target.checked)}/>Show inactive / archived</label></div>
 <div className="content-grid"><article className="panel"><h3>{categories[selectedCategory]} catalog</h3><div className="table"><div className="table-head"><span>SKU</span><span>Product</span><span>Basis</span><span>Lifecycle</span></div>{items.map(item=><button className={`table-row product-row ${selected?.id===item.id?'active':''}`} type="button" key={item.id} onClick={()=>setSelected(item)}><strong>{item.sku}<small>{item.familyCode}</small></strong><span>{item.productName}<small>{item.defaultTurnaroundBusinessDays?`${item.defaultTurnaroundBusinessDays} business days`:'Turnaround configured later'}</small></span><span>{item.pricingBasis.replaceAll('_',' ')}</span><span className="badge">{item.active?'active':'inactive'}</span></button>)}</div></article>
 <article className="panel"><h3>Catalog administration</h3><form className="form-grid" onSubmit={addCustom}><p className="note">Add a tenant-specific product only in the active category. Family codes must use the active {selectedCategory}-… namespace; owner-approved template records remain separate.</p><label>SKU<input name="sku" aria-label="Custom product SKU" required/></label><label>Product name<input name="productName" aria-label="Custom product name" required/></label><label>Family code<input name="familyCode" aria-label="Custom product family code" value={newFamilyCode} onChange={event=>setNewFamilyCode(event.target.value.toUpperCase())} placeholder={`${selectedCategory}-CUSTOM`} list="category-family-codes" pattern={`${selectedCategory}-[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*`} required/><datalist id="category-family-codes">{familySuggestions.map(code=><option key={code} value={code}/>)}</datalist></label><label>Pricing basis<select name="pricingBasis" aria-label="Custom product pricing basis" defaultValue="PER_PRODUCT">{bases.map(value=><option key={value}>{value}</option>)}</select></label><label>Configuration<select name="selection" aria-label="Custom product configuration" defaultValue="NONE"><option>NONE</option><option>SINGLE_TOOTH</option><option>MULTIPLE_TEETH</option><option>PARTIAL_ARCH</option><option>FULL_ARCH</option><option>STAGE_COUNT</option><option>COMPONENT_COUNT</option></select></label><label>Turnaround business days<input name="turnaround" aria-label="Custom product turnaround" type="number" min="1"/></label><label>Owner description<textarea name="description" aria-label="Custom product description" required/></label><button className="primary" disabled={saving} type="submit">Add tenant product</button></form></article></div>
 {selected&&<section className="content-grid"><article className="panel"><p className="eyebrow">SELECTED PRODUCT</p><h3>{selected.sku} — {selected.productName}</h3><p>{selected.description}</p><div className="department-row"><strong>Category</strong><span>{selected.categoryCode} · {categories[selected.categoryCode]}</span></div><div className="department-row"><strong>Configuration</strong><span>{String(selected.configuration.selection??'NONE').replaceAll('_',' ')}</span></div>{editing&&<form className="form-grid" onSubmit={saveEdit}><label>Product name<input name="productName" aria-label="Edit product name" defaultValue={selected.productName} required/></label><label>Family code<input name="familyCode" aria-label="Edit product family code" defaultValue={selected.familyCode}/></label><label>Turnaround business days<input name="turnaround" aria-label="Edit product turnaround" type="number" min="1" defaultValue={selected.defaultTurnaroundBusinessDays??''}/></label><label>Owner description<textarea name="description" aria-label="Edit product description" defaultValue={selected.description} required/></label><div className="settings-actions"><button className="primary" disabled={saving} type="submit">Save product changes</button><button type="button" disabled={saving} onClick={()=>setEditing(false)}>Cancel edit</button></div></form>}<div className="settings-actions"><button disabled={saving} onClick={()=>setEditing(true)}>Edit product</button><button className={selected.active?'danger':'primary'} disabled={saving} onClick={()=>void setLifecycle(selected,!selected.active)}>{selected.active?'Deactivate / archive':'Activate product'}</button></div></article><article className="panel"><p className="eyebrow">EFFECTIVE-DATED PRICING</p><h3>Price version history</h3><form className="form-grid" onSubmit={addPrice}><label>Base amount<input name="amount" aria-label="Product base amount" type="number" min="0" step="0.01" required/></label><label>Effective from<input name="effectiveFrom" aria-label="Product price effective from" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></label><label>Effective until<input name="effectiveUntil" aria-label="Product price effective until" type="date"/></label><label>Version note<input name="versionNote" aria-label="Product price version note"/></label><button className="primary" disabled={saving||!selected.active} type="submit">Add price version</button></form><div className="table"><div className="table-head"><span>Amount</span><span>Basis</span><span>Effective period</span><span>Note</span></div>{prices.map(price=><div className="table-row" key={price.id}><strong>{money(price.amount)}</strong><span>{price.pricing_basis.replaceAll('_',' ')}</span><span>{price.effective_from.slice(0,10)} → {price.effective_until?.slice(0,10)??'open'}</span><span>{price.version_note||'—'}</span></div>)}</div></article></section>}</section>;
}
