import { FormEvent, useEffect, useState } from 'react';
import type { FinancialDashboardSnapshot, User } from '@northstar/shared';
import { DoctorManagement, PracticeManagement } from './DirectoryManagement';
import { CaseManagement, PatientManagement } from './PatientCaseManagement';
import { ProductionManagement } from './ProductionManagement';
import { QCManagement } from './QCManagement';
import { ShippingManagement } from './ShippingManagement';
import { BillingManagement } from './BillingManagement';

type View='dashboard'|'practices'|'doctors'|'patients'|'cases'|'production'|'qc'|'shipping'|'billing';type AuthResponse={user:User};const sessionKey='northstar.session';const email='dorianhabet@yahoo.com';function readSession(){try{const value=localStorage.getItem(sessionKey);return value?JSON.parse(value) as User:null}catch{return null}}
export function Sprint8App(){const[session,setSession]=useState<User|null>(readSession);const[view,setView]=useState<View>('dashboard');const[snapshot,setSnapshot]=useState<FinancialDashboardSnapshot|null>(null);const[revision,setRevision]=useState(0);const[error,setError]=useState('');useEffect(()=>{if(!session){setSnapshot(null);return}fetch('/api/dashboard').then(async response=>{if(!response.ok)throw new Error();return response.json() as Promise<FinancialDashboardSnapshot>}).then(value=>{setSnapshot(value);setError('')}).catch(()=>setError('Dashboard data is temporarily unavailable.'))},[session,revision]);const login=(user:User)=>{localStorage.setItem(sessionKey,JSON.stringify(user));setSession(user)};const logout=()=>{localStorage.removeItem(sessionKey);setSession(null);setView('dashboard')};if(!session)return <Login onLogin={login}/>;const title:Record<View,string>={dashboard:'Laboratory Status',practices:'Practice Management',doctors:'Doctor Management',patients:'Patient Management',cases:'Case Intake',production:'Production Workflow',qc:'Quality Control',shipping:'Shipping & Logistics',billing:'Billing & Financial Engine'};const refresh=()=>setRevision(value=>value+1);return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">NS</span><div><strong>CADence</strong><span>NorthStar</span></div></div><nav>{([['dashboard','Laboratory'],['practices','Practices'],['doctors','Doctors'],['patients','Patients'],['cases','Cases'],['production','Production'],['qc','Quality Control'],['shipping','Shipping'],['billing','Billing']] as Array<[View,string]>).map(([id,label])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}>{label}</button>)}</nav><div className="sidebar-footer"><span>Sprint 8 Billing & Financial Engine</span><button onClick={logout}>Sign out</button></div></aside><main><header><div><p className="eyebrow">KERAMOS DIGITAL TWIN</p><h1>{title[view]}</h1><p className="subtitle">Authenticated clinical, production, logistics, and financial operations.</p></div><div className="user-card"><span className="user-avatar">DH</span><div><strong>{session.name}</strong><span>{session.role}</span></div></div></header>{error&&<p className="error" role="alert">{error}</p>}{view==='dashboard'&&<Dashboard snapshot={snapshot}/>} {view==='practices'&&<PracticeManagement onCountsChanged={refresh}/>} {view==='doctors'&&<DoctorManagement onCountsChanged={refresh}/>} {view==='patients'&&<PatientManagement onCountsChanged={refresh}/>} {view==='cases'&&<CaseManagement onCountsChanged={refresh}/>} {view==='production'&&<ProductionManagement onCountsChanged={refresh}/>} {view==='qc'&&<QCManagement onMetricsChanged={refresh}/>} {view==='shipping'&&<ShippingManagement onMetricsChanged={refresh}/>} {view==='billing'&&<BillingManagement onMetricsChanged={refresh}/>}</main></div>}
function Login({onLogin}:{onLogin:(user:User)=>void}){const[value,setEmail]=useState(email);const[password,setPassword]=useState('NorthStar!2026');const[error,setError]=useState('');const submit=async(event:FormEvent)=>{event.preventDefault();const response=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:value,password})});if(!response.ok){setError('Incorrect email or password.');return}onLogin((await response.json() as AuthResponse).user)};return <div className="login-page"><form className="login-card" onSubmit={submit}><h1>Welcome back</h1><label>Email<input value={value} onChange={event=>setEmail(event.target.value)} type="email"/></label><label>Password<input value={password} onChange={event=>setPassword(event.target.value)} type="password"/></label>{error&&<p className="error">{error}</p>}<button className="primary" type="submit">Sign in</button></form></div>}
function Dashboard({snapshot}:{snapshot:FinancialDashboardSnapshot|null}){const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'});const metrics=[['Open cases',snapshot?.openCases??0],['Delivered',snapshot?.logistics.delivered??0],['Invoiced',money.format(snapshot?.financial.invoicedTotal??0)],['Collected',money.format(snapshot?.financial.collectedTotal??0)],['Outstanding AR',money.format(snapshot?.financial.outstandingAR??0)],['Overdue AR',money.format(snapshot?.financial.overdueAR??0)]];return <><section className="metrics">{metrics.map(([label,value])=><article className="metric" key={label}><span>{label}</span><strong>{value}</strong></article>)}</section><section className="panel"><p className="eyebrow">FINANCIAL PERFORMANCE</p><h2>Accounts receivable</h2><div className="department-row"><strong>Invoices</strong><span>{snapshot?.financial.invoiceCount??0}</span></div><div className="department-row"><strong>Paid invoices</strong><span>{snapshot?.financial.paidInvoiceCount??0}</span></div><div className="department-row"><strong>Average days to pay</strong><span>{snapshot?.financial.averageDaysToPay??0}</span></div></section></>}
