import { FormEvent, useEffect, useState } from 'react';
import type { DashboardSnapshot, User } from '@northstar/shared';
import { DoctorManagement, PracticeManagement } from './DirectoryManagement';
import { CaseManagement, PatientManagement } from './PatientCaseManagement';
import { ProductionManagement } from './ProductionManagement';
import { QCManagement } from './QCManagement';

type View='dashboard'|'practices'|'doctors'|'patients'|'cases'|'production'|'qc';type AuthResponse={user:User};const sessionKey='northstar.session';const developmentEmail='dorianhabet@yahoo.com';function readSession(){try{const value=localStorage.getItem(sessionKey);return value?JSON.parse(value) as User:null}catch{return null}}
export function Sprint6App(){const[session,setSession]=useState<User|null>(readSession);const[view,setView]=useState<View>('dashboard');const[snapshot,setSnapshot]=useState<DashboardSnapshot|null>(null);const[revision,setRevision]=useState(0);const[error,setError]=useState('');useEffect(()=>{if(!session){setSnapshot(null);return}fetch('/api/dashboard').then(async response=>{if(!response.ok)throw new Error();return response.json() as Promise<DashboardSnapshot>}).then(value=>{setSnapshot(value);setError('')}).catch(()=>setError('Dashboard data is temporarily unavailable.'))},[session,revision]);const login=(user:User)=>{localStorage.setItem(sessionKey,JSON.stringify(user));setSession(user)};const logout=()=>{localStorage.removeItem(sessionKey);setSession(null);setView('dashboard')};if(!session)return <Login onLogin={login}/>;const title:Record<View,string>={dashboard:'Laboratory Status',practices:'Practice Management',doctors:'Doctor Management',patients:'Patient Management',cases:'Case Intake',production:'Production Workflow',qc:'Quality Control'};const refresh=()=>setRevision(value=>value+1);return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">NS</span><div><strong>CADence</strong><span>NorthStar</span></div></div><nav>{([['dashboard','Laboratory'],['practices','Practices'],['doctors','Doctors'],['patients','Patients'],['cases','Cases'],['production','Production'],['qc','Quality Control']] as Array<[View,string]>).map(([id,label])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}>{label}</button>)}</nav><div className="sidebar-footer"><span>Sprint 6 Quality Control</span><button onClick={logout}>Sign out</button></div></aside><main><header><div><p className="eyebrow">KERAMOS DIGITAL TWIN</p><h1>{title[view]}</h1><p className="subtitle">Authenticated clinical, production, and quality-control operations.</p></div><div className="user-card"><span className="user-avatar">DH</span><div><strong>{session.name}</strong><span>{session.role}</span></div></div></header>{error&&<p className="error" role="alert">{error}</p>}{view==='dashboard'&&<Dashboard snapshot={snapshot}/>} {view==='practices'&&<PracticeManagement onCountsChanged={refresh}/>} {view==='doctors'&&<DoctorManagement onCountsChanged={refresh}/>} {view==='patients'&&<PatientManagement onCountsChanged={refresh}/>} {view==='cases'&&<CaseManagement onCountsChanged={refresh}/>} {view==='production'&&<ProductionManagement onCountsChanged={refresh}/>} {view==='qc'&&<QCManagement onMetricsChanged={refresh}/>}</main></div>}
function Login({onLogin}:{onLogin:(user:User)=>void}){const[email,setEmail]=useState(developmentEmail);const[password,setPassword]=useState('NorthStar!2026');const[error,setError]=useState('');const[loading,setLoading]=useState(false);const submit=async(event:FormEvent)=>{event.preventDefault();setLoading(true);setError('');try{const response=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});if(!response.ok){setError('Incorrect email or password.');return}const payload=await response.json() as AuthResponse;onLogin(payload.user)}catch{setError('Unable to reach the authentication service.')}finally{setLoading(false)}};return <div className="login-page"><form className="login-card" onSubmit={submit}><div className="brand login-brand"><span className="brand-mark">NS</span><div><strong>CADence</strong><span>NorthStar</span></div></div><p className="eyebrow">KERAMOS DIGITAL TWIN</p><h1>Welcome back</h1><label>Email<input value={email} onChange={event=>setEmail(event.target.value)} type="email" required/></label><label>Password<input value={password} onChange={event=>setPassword(event.target.value)} type="password" required/></label>{error&&<p className="error">{error}</p>}<button className="primary" type="submit" disabled={loading}>{loading?'Signing in…':'Sign in'}</button></form></div>}
function Dashboard({snapshot}:{snapshot:DashboardSnapshot|null}){const metrics=[['Active practices',snapshot?.activePractices??0],['Open cases',snapshot?.openCases??0],['Production in progress',snapshot?.productionInProgress??0],['QC pass rate',`${snapshot?.qcPassRate??0}%`],['QC rework rate',`${snapshot?.qcReworkRate??0}%`],['QC remake rate',`${snapshot?.qcRemakeRate??0}%`],['First-pass yield',`${snapshot?.qcFirstPassYield??0}%`]];return <><section className="metrics">{metrics.map(([label,value])=><article className="metric" key={label}><span>{label}</span><strong>{value}</strong></article>)}</section><section className="panel"><p className="eyebrow">DEFECT TRENDS</p><h2>Quality trends</h2>{snapshot?.qcDefectTrends.length?snapshot.qcDefectTrends.map(item=><div className="department-row" key={item.category}><strong>{item.category.replace('-',' ')}</strong><span>{item.count} defects</span></div>):<p>No QC defects recorded.</p>}</section></>}
