import { FormEvent, useEffect, useState } from 'react';
import type { FinancialDashboardSnapshot, User } from '@northstar/shared';
import { DoctorManagement, PracticeManagement } from './DirectoryManagement';
import { CaseManagement, PatientManagement } from './PatientCaseManagement';
import { ProductionManagement } from './ProductionManagement';
import { QCManagement } from './QCManagement';
import { ShippingManagement } from './ShippingManagement';
import { BillingManagement } from './BillingManagement';
import { Notifications } from './Notifications';
import { DigitalIntakeWorkspace } from './DigitalIntakeWorkspace';
import { setCsrfToken } from './security-client';

type View='dashboard'|'intake'|'practices'|'doctors'|'patients'|'cases'|'production'|'qc'|'shipping'|'billing';
type AuthResponse={user:User;csrfToken:string};
const email='dorianhabet@yahoo.com';

export function Sprint8App(){
 const[session,setSession]=useState<User|null>(null);const[checkingSession,setCheckingSession]=useState(true);const[view,setView]=useState<View>('dashboard');const[snapshot,setSnapshot]=useState<FinancialDashboardSnapshot|null>(null);const[revision,setRevision]=useState(0);const[error,setError]=useState('');
 useEffect(()=>{let active=true;fetch('/api/auth/session').then(async response=>{if(!response.ok)throw new Error();return response.json() as Promise<AuthResponse>}).then(value=>{if(active){setCsrfToken(value.csrfToken);setSession(value.user)}}).catch(()=>{if(active){setCsrfToken(null);setSession(null)}}).finally(()=>{if(active)setCheckingSession(false)});const expired=()=>{setSession(null);setSnapshot(null);setView('dashboard')};window.addEventListener('northstar:session-expired',expired);return()=>{active=false;window.removeEventListener('northstar:session-expired',expired)}},[]);
 useEffect(()=>{if(!session){setSnapshot(null);return}fetch('/api/dashboard').then(async response=>{if(!response.ok)throw new Error();return response.json() as Promise<FinancialDashboardSnapshot>}).then(value=>{setSnapshot(value);setError('')}).catch(()=>setError('Dashboard data is temporarily unavailable.'))},[session,revision]);
 const login=(user:User,csrfToken:string)=>{setCsrfToken(csrfToken);setSession(user)};
 const logout=async()=>{try{await fetch('/api/auth/logout',{method:'POST'})}finally{setCsrfToken(null);setSession(null);setView('dashboard')}};
 if(checkingSession)return <div className="login-page"><div className="login-card"><h1>CADence NorthStar</h1><p>Securing your session…</p></div></div>;
 if(!session)return <Login onLogin={login}/>;
 const title:Record<View,string>={dashboard:'Laboratory Status',intake:'Digital Intake Platform',practices:'Practice Management',doctors:'Doctor Management',patients:'Patient Management',cases:'Case Intake',production:'Production Workflow',qc:'Quality Control',shipping:'Shipping & Logistics',billing:'Billing & Financial Engine'};const refresh=()=>setRevision(value=>value+1);
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">NS</span><div><strong>CADence</strong><span>NorthStar</span></div></div><nav>{([['dashboard','Laboratory'],['intake','Digital Intake'],['practices','Practices'],['doctors','Doctors'],['patients','Patients'],['cases','Cases'],['production','Production'],['qc','Quality Control'],['shipping','Shipping'],['billing','Billing']] as Array<[View,string]>).map(([id,label])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}>{label}</button>)}</nav><div className="sidebar-footer"><span>Community Preview 2 · Digital Intake Foundation</span><button onClick={()=>void logout()}>Sign out</button></div></aside><main><header><div><p className="eyebrow">KERAMOS DIGITAL TWIN</p><h1>{title[view]}</h1><p className="subtitle">Authenticated intake, clinical, production, logistics, financial, and communication operations.</p></div><Notifications/><div className="user-card"><span className="user-avatar">DH</span><div><strong>{session.name}</strong><span>{session.role}</span></div></div></header>{error&&<p className="error" role="alert">{error}</p>}{view==='dashboard'&&<Dashboard snapshot={snapshot}/>} {view==='intake'&&<DigitalIntakeWorkspace/>} {view==='practices'&&<PracticeManagement onCountsChanged={refresh}/>} {view==='doctors'&&<DoctorManagement onCountsChanged={refresh}/>} {view==='patients'&&<PatientManagement onCountsChanged={refresh}/>} {view==='cases'&&<CaseManagement onCountsChanged={refresh}/>} {view==='production'&&<ProductionManagement onCountsChanged={refresh}/>} {view==='qc'&&<QCManagement onMetricsChanged={refresh}/>} {view==='shipping'&&<ShippingManagement onMetricsChanged={refresh}/>} {view==='billing'&&<BillingManagement onMetricsChanged={refresh}/>}</main></div>
}

function Login({onLogin}:{onLogin:(user:User,csrfToken:string)=>void}){const[value,setEmail]=useState(email);const[password,setPassword]=useState('NorthStar!2026');const[error,setError]=useState('');const[loading,setLoading]=useState(false);const submit=async(event:FormEvent)=>{event.preventDefault();setLoading(true);setError('');try{const response=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:value,password})});if(!response.ok){setError(response.status===423?'Account temporarily locked. Try again later.':'Incorrect email or password.');return}const payload=await response.json() as AuthResponse;onLogin(payload.user,payload.csrfToken)}catch{setError('Unable to reach the authentication service.')}finally{setLoading(false)}};return <div className="login-page"><form className="login-card" onSubmit={submit}><h1>Welcome back</h1><label>Email<input value={value} onChange={event=>setEmail(event.target.value)} type="email" autoComplete="username" required/></label><label>Password<input value={password} onChange={event=>setPassword(event.target.value)} type="password" autoComplete="current-password" required/></label>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" type="submit" disabled={loading}>{loading?'Signing in…':'Sign in'}</button></form></div>}
function Dashboard({snapshot}:{snapshot:FinancialDashboardSnapshot|null}){const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'});const metrics=[['Open cases',snapshot?.openCases??0],['Delivered',snapshot?.logistics.delivered??0],['Invoiced',money.format(snapshot?.financial.invoicedTotal??0)],['Collected',money.format(snapshot?.financial.collectedTotal??0)],['Outstanding AR',money.format(snapshot?.financial.outstandingAR??0)],['Overdue AR',money.format(snapshot?.financial.overdueAR??0)]];return <><section className="metrics">{metrics.map(([label,value])=><article className="metric" key={label}><span>{label}</span><strong>{value}</strong></article>)}</section><section className="panel"><p className="eyebrow">FINANCIAL PERFORMANCE</p><h2>Accounts receivable</h2><div className="department-row"><strong>Invoices</strong><span>{snapshot?.financial.invoiceCount??0}</span></div><div className="department-row"><strong>Paid invoices</strong><span>{snapshot?.financial.paidInvoiceCount??0}</span></div><div className="department-row"><strong>Average days to pay</strong><span>{snapshot?.financial.averageDaysToPay??0}</span></div></section></>}
