import { FormEvent, useEffect, useMemo, useState } from 'react';

type Plan={id:string;name:string;module:string;status:string;caseCount:number;passedCount:number;failedCount:number};
type TestCase={id:string;title:string;category:string;expected_result:string;priority:string;severity:string;executionStatus?:string;actualResult?:string;executionNotes?:string};
type Defect={id:string;defect_number:string;title:string;module:string;severity:string;priority:string;status:string;description:string};
type Readiness={total:number;passed:number;blockers:number;ready:boolean;buildVersion:string;gitCommit:string;environment:string};

const ownerFacing=(value:string)=>value
 .replace(/\bKeramos(?:\s+Dental\s+Laboratory)?\b/gi,'another laboratory')
 .replace(/\bSprint(?:\s+\d+[A-Za-z]?)?\b/gi,'Release')
 .replace(/\bUAT\b/gi,'Validation');

export function UatWorkspace({canAdmin}:{canAdmin:boolean}){
 const[plans,setPlans]=useState<Plan[]>([]);const[selected,setSelected]=useState('');const[cases,setCases]=useState<TestCase[]>([]);const[defects,setDefects]=useState<Defect[]>([]);const[readiness,setReadiness]=useState<Readiness|null>(null);const[error,setError]=useState('');const[loading,setLoading]=useState(true);
 const refresh=async()=>{setLoading(true);try{const[planResponse,defectResponse,readyResponse]=await Promise.all([fetch('/api/uat/plans'),fetch('/api/uat/defects'),fetch('/api/uat/readiness')]);if(!planResponse.ok||!defectResponse.ok||!readyResponse.ok)throw new Error();const nextPlans=await planResponse.json() as Plan[];setPlans(nextPlans);setDefects(await defectResponse.json() as Defect[]);setReadiness(await readyResponse.json() as Readiness);setSelected(current=>current||nextPlans[0]?.id||'');setError('')}catch{setError('Validation data is temporarily unavailable.')}finally{setLoading(false)}};
 useEffect(()=>{void refresh()},[]);useEffect(()=>{if(!selected){setCases([]);return}fetch(`/api/uat/plans/${selected}/cases`).then(async response=>{if(!response.ok)throw new Error();return response.json() as Promise<TestCase[]>}).then(setCases).catch(()=>setError('Unable to load validation cases.'))},[selected]);
 const complete=useMemo(()=>plans.reduce((sum,plan)=>sum+Number(plan.passedCount||0),0),[plans]);
 const execute=async(item:TestCase,status:'pass'|'fail'|'blocked')=>{const actualResult=prompt(`Actual result for ${ownerFacing(item.title)}`,item.actualResult||'')??'';const notes=prompt('Execution notes',item.executionNotes||'')??'';const response=await fetch(`/api/uat/cases/${item.id}/execute`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,actualResult,notes})});if(!response.ok){setError('Unable to record execution.');return}await refresh();setSelected(selected)};
 const seed=async()=>{const response=await fetch('/api/uat/seed',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(!response.ok){setError('Seed data is unavailable or not authorized.');return}await refresh()};
 return <><section className="metrics"><article className="metric"><span>Validation plans</span><strong>{plans.length}</strong></article><article className="metric"><span>Checks passed</span><strong>{complete}</strong></article><article className="metric"><span>Open defects</span><strong>{defects.filter(item=>!['verified','closed'].includes(item.status)).length}</strong></article><article className={`metric ${readiness?.blockers?'emphasis':''}`}><span>Blocking defects</span><strong>{readiness?.blockers??0}</strong></article><article className="metric"><span>Build</span><strong>{readiness?.buildVersion??'—'}</strong></article><article className="metric"><span>Readiness</span><strong>{readiness?.ready?'Ready':'In progress'}</strong></article></section>{error&&<p className="error" role="alert">{error}</p>}<section className="content-grid"><article className="panel"><div className="panel-heading"><div><p className="eyebrow">OPERATIONAL VALIDATION</p><h2>Assigned validation plans</h2></div>{canAdmin&&<button className="secondary" onClick={()=>void seed()}>Load deterministic scenarios</button>}</div>{loading?<p>Loading validation workspace…</p>:<><label>Validation plan<select value={selected} onChange={event=>setSelected(event.target.value)}>{plans.map(plan=><option key={plan.id} value={plan.id}>{ownerFacing(plan.name)} · {ownerFacing(plan.module)}</option>)}</select></label>{cases.map(item=><div className="priority" key={item.id}><div><strong>{ownerFacing(item.title)}</strong><span>{item.executionStatus||'not-run'}</span></div><p>{ownerFacing(item.expected_result)}</p><small>{ownerFacing(item.category)} · {item.priority} priority</small><div className="actions"><button onClick={()=>void execute(item,'pass')}>Pass</button><button onClick={()=>void execute(item,'blocked')}>Blocked</button><button className="danger" onClick={()=>void execute(item,'fail')}>Fail</button></div></div>)}{!cases.length&&<p className="empty">No validation cases are assigned yet.</p>}</>}</article><Defects defects={defects} onChanged={refresh}/></section></>;
}

function Defects({defects,onChanged}:{defects:Defect[];onChanged:()=>Promise<void>}){const[open,setOpen]=useState(false);const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget;const data=new FormData(form);const response=await fetch('/api/uat/defects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:data.get('title'),description:data.get('description'),module:data.get('module'),severity:data.get('severity'),priority:data.get('priority')})});if(response.ok){form.reset();setOpen(false);await onChanged()}};const change=async(id:string,status:string)=>{await fetch(`/api/uat/defects/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});await onChanged()};return <article className="panel"><div className="panel-heading"><div><p className="eyebrow">DEFECT CONTROL</p><h2>Defects</h2></div><button className="primary" onClick={()=>setOpen(value=>!value)}>{open?'Close':'Report defect'}</button></div>{open&&<form className="form-grid" onSubmit={submit}><label>Title<input name="title" required/></label><label>Module<input name="module" required/></label><label>Severity<select name="severity"><option>medium</option><option>high</option><option>critical</option><option>low</option></select></label><label>Priority<select name="priority"><option>medium</option><option>high</option><option>critical</option><option>low</option></select></label><label>Description<textarea name="description" required/></label><button className="primary" type="submit">Submit defect</button></form>}{defects.map(item=><div className="priority" key={item.id}><div><strong>{item.defect_number} · {ownerFacing(item.title)}</strong><span>{item.status}</span></div><p>{ownerFacing(item.description)}</p><small>{ownerFacing(item.module)} · {item.severity} severity</small><select aria-label={`Status for ${item.defect_number}`} value={item.status} onChange={event=>void change(item.id,event.target.value)}>{['new','triaged','in-progress','ready-for-retest','verified','closed'].map(status=><option key={status}>{status}</option>)}</select></div>)}{!defects.length&&<p className="empty">No defects reported.</p>}</article>}
