import { describe, it } from 'node:test';
import { ArtifactManager, createProject, ProjectStore, SceneManager } from '../src/core';
import { CommandBus } from '../src/commands';
import { CrownApprovalCommand, CrownGeometryCommand, CrownProposalCommand, CrownQcCommand } from '../src/restoration-commands';
import { RestorationStateManager } from '../src/restoration-state';
import { runCrownQc } from '../src/crown-qc';
import { validateAllCrownExports } from '../src/crown-export';
import { indexedMesh, meshData } from '../src/editing-geometry';
import { goldenCrown } from './golden-crowns';
import { expect } from './test-helpers';

describe('crown command history, immutable versions, persistence, and recovery', () => {
  it('creates a derived crown artifact without mutating the preparation source and supports undo/redo', async () => {
    const runtime = setup(); const source = structuredClone(runtime.fixture.preparation.artifact); await runtime.bus.execute(proposalCommand(runtime)); const state = runtime.restorations.get(); const record = state.restorations[0]; expect(runtime.artifacts.get(source.id)).toEqual(source); expect(runtime.artifacts.list()).toHaveLength(2); expect(record.approvalState).toBe('QC_REQUIRED'); expect(record.versionIds).toHaveLength(1); expect(runtime.scene.get(record.sceneObjectId!)?.type).toBe('restoration');
    await runtime.bus.undo(); expect(runtime.artifacts.list()).toEqual([source]); expect(runtime.restorations.get().restorations).toHaveLength(0); await runtime.bus.redo(); expect(runtime.artifacts.list()).toHaveLength(2); expect(runtime.restorations.get().restorations).toHaveLength(1);
  });

  it('creates immutable edited versions and restores exact state through undo and redo', async () => {
    const runtime = setup(); await runtime.bus.execute(proposalCommand(runtime)); const record = runtime.restorations.get().restorations[0]; const parentArtifact = runtime.artifacts.get(record.artifactId!)!; const source = parentArtifact.mesh.sourceTopology!; const positions = [...source.positions]; const outer = record.topologyMap!.outerVertexIds.find((id) => record.topologyMap!.regions[id] === 'axial')!; positions[outer * 3] += 0.02; const edited = meshData({ positions: triples(positions), faces: triplets(source.indices) });
    await runtime.bus.execute(new CrownGeometryCommand(runtime, record.id, { mesh: edited, operation: 'test-local-sculpt', label: 'Test actual local crown edit', parameters: { displacementMm: 0.02 } })); const after = runtime.restorations.get().restorations[0]; expect(after.versionIds).toHaveLength(2); expect(after.approvalState).toBe('QC_REQUIRED'); expect(runtime.artifacts.get(parentArtifact.id)).toEqual(parentArtifact); expect(runtime.artifacts.list()).toHaveLength(3); const editedArtifactId = after.artifactId;
    await runtime.bus.undo(); expect(runtime.restorations.get().restorations[0].artifactId).toBe(parentArtifact.id); expect(runtime.artifacts.list()).toHaveLength(2); await runtime.bus.redo(); expect(runtime.restorations.get().restorations[0].artifactId).toBe(editedArtifactId); expect(runtime.artifacts.list()).toHaveLength(3);
  });

  it('guards approval transitions with complete active QC evidence and locks final geometry', async () => {
    const runtime = setup(); await runtime.bus.execute(proposalCommand(runtime)); let record = runtime.restorations.get().restorations[0]; await expect(runtime.bus.execute(new CrownApprovalCommand(runtime, record.id, 'APPROVED_FOR_EXPORT', 'technician-1'))).rejects.toThrow(/cannot transition|QC/i);
    const outputs = await validateAllCrownExports(runtime.artifacts.get(record.artifactId!)!.mesh); const qc = runCrownQc(record, runtime.artifacts.get(record.artifactId!)!.mesh, outputs.map((output) => output.roundTrip)); await runtime.bus.execute(new CrownQcCommand(runtime.restorations, record.id, qc)); record = runtime.restorations.get().restorations[0]; expect(record.approvalState).toBe('REVIEW_REQUIRED'); await runtime.bus.execute(new CrownApprovalCommand(runtime, record.id, 'APPROVED_FOR_EXPORT', 'technician-1')); expect(runtime.restorations.get().restorations[0].approvedBy).toBe('technician-1'); await runtime.bus.execute(new CrownApprovalCommand(runtime, record.id, 'LOCKED', 'technician-1')); record = runtime.restorations.get().restorations[0]; expect(record.approvalState).toBe('LOCKED'); expect(Object.values(record.locks).every(Boolean)).toBe(true); expect(runtime.scene.get(record.sceneObjectId!)?.locked).toBe(true);
  });

  it('persists and recovers the exact crown, versions, analysis, QC, and approval state', async () => {
    Object.defineProperty(globalThis, 'localStorage', { configurable: true, value: new MemoryStorage() }); const runtime = setup(); await runtime.bus.execute(proposalCommand(runtime)); let record = runtime.restorations.get().restorations[0]; const editable = record.topologyMap!.outerVertexIds.filter((id) => !record.topologyMap!.marginOuterVertexIds.includes(id)).slice(0, 6); const stateWithRegions = runtime.restorations.get(); runtime.restorations.replace({ ...stateWithRegions, restorations: stateWithRegions.restorations.map((value) => value.id === record.id ? { ...value, sculptMaskVertexIds: editable.slice(0, 3), lockedAnatomyVertexIds: editable.slice(3), locks: { ...value.locks, selectedAnatomy: true }, contourReferenceObjectIds: { ...value.contourReferenceObjectIds, contralateral: ['contralateral-object'], arch: ['arch-object'] } } : value) }); record = runtime.restorations.get().restorations[0]; const outputs = await validateAllCrownExports(runtime.artifacts.get(record.artifactId!)!.mesh); const qc = runCrownQc(record, runtime.artifacts.get(record.artifactId!)!.mesh, outputs.map((output) => output.roundTrip)); await runtime.bus.execute(new CrownQcCommand(runtime.restorations, record.id, qc));
    const project = createProject('Golden crown persistence'); project.scene = runtime.scene.list(); project.artifacts = runtime.artifacts.list(); project.restoration = runtime.restorations.get(); const store = new ProjectStore(); const saved = store.save(project); const opened = store.open(saved.id); expect(opened.schemaVersion).toBe(6); expect(opened.restoration).toEqual(project.restoration); expect(opened.artifacts).toEqual(project.artifacts); store.autoSave(opened); const recovered = store.recover(); expect(recovered?.restoration).toEqual(project.restoration); expect(recovered?.artifacts).toEqual(project.artifacts);
  });

  it('losslessly persists immutable crown histories that exceed the browser quota as expanded JSON', () => {
    const fixture = goldenCrown('maxillary-first-molar'); const project = createProject('Quota-safe crown history'); const crownArtifacts = Array.from({ length: 14 }, (_, index) => ({ ...structuredClone(fixture.preparation.artifact), id: `crown-version-${index + 1}`, sourceName: `Crown version ${index + 1}`, mesh: structuredClone(fixture.result.mesh) })); project.artifacts = [structuredClone(fixture.preparation.artifact), ...crownArtifacts]; const quotaBytes = 5 * 1024 * 1024; const expandedBytes = new TextEncoder().encode(JSON.stringify(project)).byteLength; expect(expandedBytes > quotaBytes).toBe(true);
    const storage = new QuotaStorage(quotaBytes); Object.defineProperty(globalThis, 'localStorage', { configurable: true, value: storage }); const store = new ProjectStore(); const saved = store.save(project); const stored = storage.getItem(`cadence.design-studio.project.${saved.id}`)!; expect(new TextEncoder().encode(stored).byteLength < quotaBytes).toBe(true); const opened = store.open(saved.id); expect(opened.artifacts).toEqual(project.artifacts); store.autoSave(opened); expect(store.recover()?.artifacts).toEqual(project.artifacts);
  });
});

function setup() { const fixture = goldenCrown('maxillary-first-molar'); const artifacts = new ArtifactManager([fixture.preparation.artifact]); const scene = new SceneManager([fixture.preparation.object]); const restorations = new RestorationStateManager(); const bus = new CommandBus(); return { fixture, artifacts, scene, restorations, bus }; }
function proposalCommand(runtime: ReturnType<typeof setup>) { return new CrownProposalCommand(runtime, runtime.fixture.input, runtime.fixture.result, { preparationVersionId: 'segmentation-v1', approvedMarginVersionId: 'margin-v1', insertionAxisAnalysisId: 'axis-v1' }); }
function triples(values: number[]): Array<[number, number, number]> { const output: Array<[number, number, number]> = []; for (let index = 0; index < values.length; index += 3) output.push([values[index], values[index + 1], values[index + 2]]); return output; }
function triplets(values: number[]): Array<[number, number, number]> { return triples(values); }
class MemoryStorage implements Storage { private values = new Map<string, string>(); get length() { return this.values.size; } clear() { this.values.clear(); } getItem(key: string) { return this.values.get(key) ?? null; } key(index: number) { return [...this.values.keys()][index] ?? null; } removeItem(key: string) { this.values.delete(key); } setItem(key: string, value: string) { this.values.set(key, value); } }
class QuotaStorage implements Storage { private values = new Map<string, string>(); constructor(private readonly quotaBytes: number) {} get length() { return this.values.size; } clear() { this.values.clear(); } getItem(key: string) { return this.values.get(key) ?? null; } key(index: number) { return [...this.values.keys()][index] ?? null; } removeItem(key: string) { this.values.delete(key); } setItem(key: string, value: string) { const next = new Map(this.values); next.set(key, value); const bytes = [...next].reduce((total, [itemKey, itemValue]) => total + new TextEncoder().encode(itemKey).byteLength + new TextEncoder().encode(itemValue).byteLength, 0); if (bytes > this.quotaBytes) throw new DOMException('Storage quota exceeded', 'QuotaExceededError'); this.values = next; } }
