import { describe, it } from 'node:test';
import { ArtifactManager, SceneManager } from '../src/core';
import { CommandBus } from '../src/commands';
import { analyzeContour, correctContour } from '../src/crown-analysis';
import { createCrownExportRecords, validateAllCrownExports } from '../src/crown-export';
import { CROWN_MATERIAL_PROFILES, defaultCrownParameters, validateCrownParameters } from '../src/morphology-core';
import { CrownBranchCommand, CrownCheckpointCommand, CrownGeometryCommand, CrownProposalCommand, CrownRestoreVersionCommand, compareRestorationVersions } from '../src/restoration-commands';
import { RestorationStateManager } from '../src/restoration-state';
import { indexedMesh, meshData } from '../src/editing-geometry';
import type { CrownLocks, CrownMaterialId } from '../src/restoration-types';
import { goldenCrown } from './golden-crowns';
import { expect } from './test-helpers';

const MATERIALS: CrownMaterialId[] = ['zirconia-monolithic', 'zirconia-high-translucency', 'lithium-disilicate', 'pmma-provisional', 'full-cast-metal', 'pfm-coping', 'hybrid-ceramic'];
const unlocked: CrownLocks = { margin: true, intaglio: false, mesialContact: false, distalContact: false, occlusion: false, facialContour: false, lingualContour: false, selectedAnatomy: false, anatomy: false };

describe('governed crown materials, contour references and immutable history', () => {
  for (const materialId of MATERIALS) {
    it(`${materialId} owns complete governed configuration and generates valid actual geometry`, () => {
      const profile = CROWN_MATERIAL_PROFILES[materialId]; const parameters = defaultCrownParameters(8, materialId); expect(validateCrownParameters(parameters, materialId)).toHaveLength(0); expect(profile.validationRules.length).toBeGreaterThanOrEqual(6); expect(profile.compatibility.restorationTypes).toEqual(['single-unit-tooth-supported-crown']); expect(profile.governance.clinicalApprovalClaimed).toBe(false);
      const fixture = goldenCrown('maxillary-central-incisor', materialId, { radialSegments: 24, surfaceRings: 6 }); expect(fixture.result.inspection.watertight).toBe(true); expect(fixture.result.thickness.failingVertexIds).toHaveLength(0); expect(fixture.result.cementSpace.status).toBe('pass');
    });
  }

  it('rejects radius and manufacturing-access parameters outside the selected profile', () => {
    const profile = CROWN_MATERIAL_PROFILES['lithium-disilicate']; const value = defaultCrownParameters(8, profile.id); expect(validateCrownParameters({ ...value, internalRadiusMm: profile.minimumInternalRadiusMm - 0.01 }, profile.id).join(' ')).toMatch(/Internal radius/); expect(validateCrownParameters({ ...value, millingToolDiameterMm: (profile.minimumMillingToolDiameterMm ?? 0) - 0.01 }, profile.id).join(' ')).toMatch(/Milling-tool/);
  });

  it('persists a changed material profile and reference snapshot on the derived regeneration version', async () => {
    const initial = goldenCrown('maxillary-central-incisor', 'zirconia-monolithic', { radialSegments: 24, surfaceRings: 6 }); const regenerated = goldenCrown('maxillary-central-incisor', 'zirconia-high-translucency', { radialSegments: 24, surfaceRings: 6 }); const artifacts = new ArtifactManager([initial.preparation.artifact]); const scene = new SceneManager([initial.preparation.object]); const restorations = new RestorationStateManager(); const bus = new CommandBus(); const context = { artifacts, scene, restorations }; await bus.execute(new CrownProposalCommand(context, initial.input, initial.result, { preparationVersionId: 'seg-v1', approvedMarginVersionId: 'margin-v1', insertionAxisAnalysisId: 'axis-v1' })); const record = restorations.get().restorations[0]; const profile = CROWN_MATERIAL_PROFILES['zirconia-high-translucency'];
    await bus.execute(new CrownGeometryCommand(context, record.id, { mesh: regenerated.result.mesh, operation: 'profile-regeneration', label: 'Regenerate with governed high-translucency profile', analyses: { materialProfileId: profile.id, materialProfileVersion: profile.version, materialProfileSnapshot: profile, parameters: regenerated.input.parameters, referenceAdaptation: { mode: 'preserve-selected-region', influence: 0.5, selectedRegion: { centerX: 0, centerY: 0, radius: 0.5 } }, contourReferenceObjectIds: { contralateral: ['contralateral-object'] }, topologyMap: regenerated.result.topologyMap, thickness: regenerated.result.thickness, cementSpace: regenerated.result.cementSpace, seating: regenerated.result.seating, mesialContact: regenerated.result.mesialContact, distalContact: regenerated.result.distalContact, occlusion: regenerated.result.occlusion, contour: regenerated.result.contour } })); const next = restorations.get(); const changed = next.restorations[0]; const version = next.versions.find((value) => value.id === changed.activeVersionId)!; expect(changed.materialProfileId).toBe(profile.id); expect(changed.materialProfileSnapshot).toEqual(profile); expect(changed.referenceAdaptation.mode).toBe('preserve-selected-region'); expect(changed.contourReferenceObjectIds?.contralateral).toEqual(['contralateral-object']); expect(version.materialProfileId).toBe(profile.id); expect(version.materialProfileVersion).toBe(profile.version); await bus.undo(); expect(restorations.get().restorations[0].materialProfileId).toBe('zirconia-monolithic'); await bus.redo(); expect(restorations.get().restorations[0].materialProfileId).toBe(profile.id);
  });

  it('reports every assigned contour reference and applies bounded local model-space correction', () => {
    const fixture = goldenCrown('maxillary-first-molar'); const references = [...fixture.input.contourReferences, { objectId: 'preparation', kind: 'preparation' as const, mesh: fixture.preparation.artifact.mesh }, { objectId: 'contralateral', kind: 'contralateral' as const, mesh: fixture.reference.mesh }, { objectId: 'arch', kind: 'arch' as const, mesh: fixture.antagonist.mesh }]; const before = analyzeContour(fixture.result.mesh, fixture.result.topologyMap, references); expect(before.references.map((value) => value.kind)).toEqual(['adjacent', 'adjacent', 'pre-op', 'preparation', 'contralateral', 'arch']); expect(Object.keys(before.regions)).toEqual(['facial', 'lingual', 'cervical', 'proximal']); const corrected = correctContour(fixture.result.mesh, fixture.result.topologyMap, references, 'both', 0.05, unlocked); expect(indexedMesh(corrected).positions).not.toEqual(indexedMesh(fixture.result.mesh).positions); expect(indexedMesh(corrected).faces).toEqual(indexedMesh(fixture.result.mesh).faces);
  });

  it('creates named checkpoints, compares, restores, duplicates and branches through commands', async () => {
    const fixture = goldenCrown('maxillary-first-molar'); const artifacts = new ArtifactManager([fixture.preparation.artifact]); const scene = new SceneManager([fixture.preparation.object]); const restorations = new RestorationStateManager(); const bus = new CommandBus(); const context = { artifacts, scene, restorations };
    await bus.execute(new CrownProposalCommand(context, fixture.input, fixture.result, { preparationVersionId: 'seg-v1', approvedMarginVersionId: 'margin-v1', insertionAxisAnalysisId: 'axis-v1' })); let record = restorations.get().restorations[0]; await bus.execute(new CrownCheckpointCommand(restorations, record.id, 'Initial proposal'));
    const source = indexedMesh(artifacts.get(record.artifactId!)!.mesh); const positions = source.positions.map((point) => [...point] as [number, number, number]); const vertexId = record.topologyMap!.outerVertexIds.find((id) => record.topologyMap!.regions[id] === 'axial')!; positions[vertexId][0] += 0.02; await bus.execute(new CrownGeometryCommand(context, record.id, { mesh: meshData({ positions, faces: source.faces }), operation: 'history-test', label: 'History test edit', parameters: { displacementMm: 0.02 } }));
    const state = restorations.get(); record = state.restorations[0]; const comparison = compareRestorationVersions(state.versions[0], state.versions[1]); expect(comparison.toVersion).toBe(2); expect(Object.keys(comparison.parameterChanges)).toContain('displacementMm'); await bus.execute(new CrownRestoreVersionCommand(context, record.id, state.versions[0].id)); expect(restorations.get().restorations[0].activeVersionId).toBe(state.versions[0].id); await bus.undo(); expect(restorations.get().restorations[0].activeVersionId).toBe(state.versions[1].id);
    await bus.execute(new CrownBranchCommand(context, record.id, 'duplicate', 'Candidate B')); const duplicate = restorations.get().restorations[1]; expect(restorations.get().restorations).toHaveLength(2); expect(duplicate.sceneObjectId).not.toBe(record.sceneObjectId); expect(duplicate.activeVersionId).not.toBe(record.activeVersionId); expect(restorations.get().versions.find((value) => value.id === duplicate.activeVersionId)?.restorationId).toBe(duplicate.id); expect(scene.get(duplicate.sceneObjectId!)?.artifactId).toBe(record.artifactId); await bus.undo(); expect(restorations.get().restorations).toHaveLength(1); expect(scene.get(duplicate.sceneObjectId!)).toBe(undefined); await bus.execute(new CrownBranchCommand(context, record.id, 'branch', 'Occlusal alternative')); expect(restorations.get().restorations[1].activeBranchId).not.toBe(record.activeBranchId); expect(restorations.get().historyEvents.length).toBeGreaterThanOrEqual(3);
  });

  it('emits complete immutable manufacturing metadata from exact round-trip output', async () => {
    const fixture = goldenCrown('maxillary-central-incisor'); const outputs = await validateAllCrownExports(fixture.result.mesh); const profile = CROWN_MATERIAL_PROFILES[fixture.input.materialProfileId]; const now = new Date(0).toISOString(); const record = {
      id: 'restoration', caseId: fixture.input.caseId, numberingSystem: 'UNIVERSAL' as const, arch: fixture.input.arch, restorationType: 'SINGLE_UNIT_TOOTH_SUPPORTED_CROWN' as const, preparationId: fixture.input.preparationId, preparationVersionId: 'seg-v1', approvedMarginVersionId: 'margin-v1', insertionAxisAnalysisId: 'axis-v1', toothNumber: String(fixture.toothNumber), morphologyId: fixture.input.parameters.morphologyId, morphologyVersion: 'CADENCE-MORPHOLOGY-1.0.0', materialProfileId: fixture.input.materialProfileId, materialProfileVersion: profile.version, materialProfileSnapshot: profile, adjacentObjectIds: { mesial: null, distal: null }, opposingObjectId: null, preOpObjectId: null, referenceAdaptation: fixture.input.referenceAdaptation, designVersion: 4, manufacturingState: 'READY_FOR_EXPORT' as const, geometryLineageRootArtifactId: fixture.preparation.artifact.id, activeBranchId: 'main', artifactId: 'crown', sceneObjectId: 'object', parameters: fixture.input.parameters, locks: unlocked, topologyMap: fixture.result.topologyMap, thickness: fixture.result.thickness, cementSpace: fixture.result.cementSpace, seating: fixture.result.seating, mesialContact: fixture.result.mesialContact, distalContact: fixture.result.distalContact, occlusion: fixture.result.occlusion, contour: fixture.result.contour, optimization: null, sculptMaskVertexIds: [], lockedAnatomyVertexIds: [], qcResultIds: ['qc'], activeQcResultId: 'qc', versionIds: ['v4'], activeVersionId: 'v4', exportRecordIds: [], historyEventIds: [], checkpointIds: [], approvalState: 'APPROVED_FOR_EXPORT' as const, approvedAt: now, approvedBy: 'technician', createdAt: now, updatedAt: now,
    }; const records = createCrownExportRecords(record, outputs, now); expect(records).toHaveLength(4); expect(records.every((value) => value.metadata.caseId === fixture.input.caseId && value.metadata.designVersion === 4 && value.metadata.geometryHash === value.roundTrip.checksum && value.metadata.units === 'mm')).toBe(true);
  });
});
