import { describe, it } from 'node:test';
import { buildCrownSolid, resampleClosedMargin, scaleCrownAnatomy, sculptCrownSurface } from '../src/crown-geometry';
import { generateCrownProposal } from '../src/crown-engine';
import { simulateSeating } from '../src/crown-analysis';
import { validateAllCrownExports } from '../src/crown-export';
import { defaultCrownParameters } from '../src/morphology-core';
import { CROWN_TOOL_COVERAGE_REGISTRY } from '../src/crown-tool-registry';
import { UNIVERSAL_TOOL_COVERAGE_REGISTRY } from '../src/tool-registry';
import { boxMesh, goldenCrown } from './golden-crowns';
import { goldenPreparation } from './golden-preparations';
import { expect } from './test-helpers';

describe('crown failure corpus rejects unsupported or corrupt input', () => {
  it('rejects invalid tooth numbers and morphology mismatches', () => { const fixture = goldenPreparation('chamfer-crown', 32); const base = input(fixture); expect(() => buildCrownSolid({ ...base, toothNumber: '0' })).toThrow(/morphology|tooth/i); expect(() => buildCrownSolid({ ...base, toothNumber: '3' })).toThrow(/not governed/i); });
  it('rejects insufficient, non-enclosing, and non-finite margins', () => { const fixture = goldenPreparation('chamfer-crown', 32); const base = input(fixture); expect(() => buildCrownSolid({ ...base, marginPoints: fixture.trueMargins[0].slice(0, 4) })).toThrow(/eight/i); expect(() => resampleClosedMargin(Array.from({ length: 8 }, () => [0, 0, 0]), 32)).toThrow(/perimeter|eight/i); const invalid = structuredClone(fixture.trueMargins[0]); invalid[0][0] = Number.NaN; expect(() => buildCrownSolid({ ...base, marginPoints: invalid })).toThrow(/eight|finite/i); });
  it('rejects zero insertion axes and governed parameter violations', () => { const fixture = goldenPreparation('chamfer-crown', 32); const base = input(fixture); expect(() => buildCrownSolid({ ...base, insertionAxis: [0, 0, 0] })).toThrow(/axis/i); expect(() => buildCrownSolid({ ...base, parameters: { ...base.parameters, cementGapMm: 2 } })).toThrow(/cementGapMm/); expect(() => buildCrownSolid({ ...base, parameters: { ...base.parameters, radialSegments: 7 } })).toThrow(/Radial segments/); });
  it('detects an impossible seating path against actual blocking geometry', () => { const fixture = goldenCrown('maxillary-central-incisor'); const bounds = fixture.result.mesh.bounds; const blocker = boxMesh([bounds.min[0] - 2, bounds.min[1] - 2, bounds.min[2] - 2], [bounds.max[0] + 2, bounds.max[1] + 2, bounds.max[2] + 2]); const solid = buildCrownSolid(fixture.input); const seating = simulateSeating(solid, { ...fixture.input, preparationMesh: blocker }); expect(seating.status).toBe('fail'); expect(seating.blockingVertexIds.length).toBeGreaterThan(0); });
  it('rejects locked sculpting/morphing and brush misses', () => { const fixture = goldenCrown('maxillary-central-incisor'); expect(() => sculptCrownSurface(fixture.result.mesh, fixture.result.topologyMap, { center: [0, 0, 0], radiusMm: 1, strengthMm: 0.1, mode: 'add' }, { margin: true, intaglio: false, anatomy: true })).toThrow(/lock/i); expect(() => sculptCrownSurface(fixture.result.mesh, fixture.result.topologyMap, { center: [1000, 1000, 1000], radiusMm: 1, strengthMm: 0.1, mode: 'add' }, { margin: true, intaglio: false, anatomy: false })).toThrow(/does not intersect/i); expect(() => scaleCrownAnatomy(fixture.result.mesh, fixture.result.topologyMap, [0, 0, 0], [2, 1, 1], { margin: true, intaglio: false, anatomy: false })).toThrow(/0.7 and 1.3/); });
  it('reports complete tool coverage evidence and no inactive crown tool', () => { expect(CROWN_TOOL_COVERAGE_REGISTRY).toHaveLength(30); expect(new Set(CROWN_TOOL_COVERAGE_REGISTRY.map((value) => value.toolId)).size).toBe(30); expect(CROWN_TOOL_COVERAGE_REGISTRY.every((value) => value.undoRedo && value.persistence && value.recovery && value.geometryAlgorithm.length > 20 && value.failClosedConditions.length > 5)).toBe(true); expect(UNIVERSAL_TOOL_COVERAGE_REGISTRY.length).toBeGreaterThan(CROWN_TOOL_COVERAGE_REGISTRY.length); });
});

describe('measured crown performance and deterministic stability', () => {
  for (const value of [{ label: 'small', radialSegments: 24, surfaceRings: 6 }, { label: 'medium', radialSegments: 48, surfaceRings: 12 }, { label: 'large', radialSegments: 96, surfaceRings: 20 }]) {
    it(`measures ${value.label} crown proposal and four-format round trip`, async () => {
      const heap = process.memoryUsage().heapUsed; const started = performance.now(); const fixture = goldenCrown('maxillary-first-molar', 'zirconia-monolithic', value); const proposalDurationMs = performance.now() - started; const exportStart = performance.now(); const exports = await validateAllCrownExports(fixture.result.mesh); const exportDurationMs = performance.now() - exportStart; const measurement = { case: value.label, vertices: fixture.result.inspection.vertexCount, triangles: fixture.result.inspection.triangleCount, proposalDurationMs, analysisDurationMs: fixture.result.durationMs, exportDurationMs, heapDeltaBytes: process.memoryUsage().heapUsed - heap, maximumRoundTripDeviationMm: Math.max(...exports.map((output) => output.roundTrip.maximumSurfaceDeviationMm)), watertight: fixture.result.inspection.watertight, selfIntersections: fixture.result.inspection.selfIntersectionCount };
      console.info(`CROWN_PERFORMANCE ${JSON.stringify(measurement)}`); expect(Object.values(measurement).filter((item) => typeof item === 'number').every(Number.isFinite)).toBe(true); expect(measurement.watertight).toBe(true); expect(measurement.selfIntersections).toBe(0); expect(measurement.maximumRoundTripDeviationMm).toBeLessThanOrEqual(0.001); expect(exports.every((output) => output.roundTrip.passed)).toBe(true);
    });
  }
  it('measures four simultaneously generated crowns and preserves byte-identical reruns', () => { const started = performance.now(); const families = ['maxillary-central-incisor', 'maxillary-first-premolar', 'maxillary-first-molar', 'mandibular-first-molar'] as const; const first = families.map((family) => goldenCrown(family)); const durationMs = performance.now() - started; const rerun = first.map((fixture) => generateCrownProposal({ ...fixture.input, requestId: `${fixture.input.requestId}-multi-rerun` })); console.info(`CROWN_MULTI_PERFORMANCE ${JSON.stringify({ meshes: first.length, triangles: first.reduce((sum, fixture) => sum + fixture.result.inspection.triangleCount, 0), durationMs, heapBytes: process.memoryUsage().heapUsed })}`); expect(rerun.map((value) => value.mesh.sourceTopology)).toEqual(first.map((value) => value.result.mesh.sourceTopology)); });
});

function input(fixture: ReturnType<typeof goldenPreparation>) { return { requestId: 'failure', preparationId: 'prep', preparationArtifactId: fixture.artifact.id, preparationMesh: fixture.artifact.mesh, marginPoints: fixture.trueMargins[0], insertionAxis: [0, 0, 1] as [number, number, number], toothNumber: '8', materialProfileId: 'zirconia-monolithic' as const, parameters: { ...defaultCrownParameters(8), radialSegments: 32, surfaceRings: 8 }, adjacentMeshes: [] }; }
