import type { Express, Request, Response } from 'express';
import type { CaseJourneyResponsibility, CaseRelationship, CaseResponsibility, ClinicalCase, ClinicalCaseInput, ContinuationBillingPolicyType, ContinuationOperationalState } from '@northstar/shared';
import type { Pool, PoolClient } from 'pg';
import type { RepositoryContext } from './infrastructure/contracts.js';

type JourneyInput=Pick<ClinicalCaseInput,'caseRelationship'|'parentCaseId'|'remakeRepairReasonId'|'continuationStageId'|'continuationOperationalState'|'continuationBillingPolicyId'|'responsibility'>;
type PreparedJourney={caseRelationship:CaseRelationship;rootCaseId:string;parentCaseId:string|null;remakeRepairReasonId:string|null;continuationStageId:string|null;continuationOperationalState:ContinuationOperationalState|null;continuationBillingPolicyId:string|null;responsibility:CaseJourneyResponsibility|null;};
const relationships=new Set<CaseRelationship>(['NEW','REMAKE','REPAIR','CONTINUATION']);
const responsibilityKinds=new Set<CaseResponsibility>(['LABORATORY','DOCTOR_PRACTICE','SHARED','PATIENT_EXTERNAL','OTHER_REQUIRES_REVIEW']);
const continuationStates=new Set<ContinuationOperationalState>(['AWAITING_CLINICAL_TRY_IN','AWAITING_RETURN','CONTINUATION_RECEIVED','WORK_RESUMED']);
const policyTypes=new Set<ContinuationBillingPolicyType>(['BILL_AT_FINAL_COMPLETION','BILL_BY_MILESTONE','BILL_EVERY_CONTINUATION','HYBRID']);
const text=(value:unknown)=>typeof value==='string'?value.trim():'';
const asRelationship=(value:unknown):CaseRelationship=>relationships.has(value as CaseRelationship)?value as CaseRelationship:'NEW';
const percentage=(value:unknown)=>{const raw=text(value);if(!/^\d{1,3}(\.\d{1,2})?$/.test(raw))return null;const hundredths=Math.round(Number(raw)*100);return hundredths>=0&&hundredths<=10000?hundredths:null;};
const asPercent=(hundredths:number)=>String((hundredths/100).toFixed(2));

async function ensureCaseJourneyDefaults(pool:Pool,tenantId:string){
  await pool.query(`INSERT INTO tenant_case_journey_reasons(tenant_id,code,category,label) VALUES
    ($1,'OTHER_REVIEW','OTHER','Other / requires review'),($1,'LAB_FABRICATION','LAB_FABRICATION','Laboratory fabrication issue'),($1,'CLINICAL_PRACTICE','CLINICAL_PRACTICE','Clinical / practice issue'),($1,'REQUESTED_CHANGE','REQUESTED_CHANGE','Requested change') ON CONFLICT(tenant_id,code) DO NOTHING`,[tenantId]);
  await pool.query(`INSERT INTO tenant_continuation_stages(tenant_id,code,label) VALUES
    ($1,'OTHER_CONTINUATION','Other Continuation'),($1,'CLINICAL_ADJUSTMENT_RETURN','Clinical Adjustment Return') ON CONFLICT(tenant_id,code) DO NOTHING`,[tenantId]);
  await pool.query(`INSERT INTO tenant_continuation_billing_policies(tenant_id,policy_type,label,is_default,created_by) VALUES
    ($1,'BILL_AT_FINAL_COMPLETION','Bill at final completion',true,'system'),($1,'BILL_BY_MILESTONE','Bill by milestone',false,'system'),($1,'BILL_EVERY_CONTINUATION','Bill every continuation',false,'system'),($1,'HYBRID','Hybrid continuation billing',false,'system') ON CONFLICT DO NOTHING`,[tenantId]);
}

export async function prepareCaseJourney(pool:Pool,context:RepositoryContext,caseId:string,body:Partial<ClinicalCaseInput>):Promise<PreparedJourney>{
  await ensureCaseJourneyDefaults(pool,context.tenantId);
  const suppliedRelationship=text(body.caseRelationship);if(suppliedRelationship&&!relationships.has(suppliedRelationship as CaseRelationship))throw new Error('Unsupported case relationship.');
  const relationship=asRelationship(body.caseRelationship);
  if(relationship==='NEW'){if(text(body.parentCaseId))throw new Error('A new case cannot include a parent case.');return{caseRelationship:'NEW',rootCaseId:caseId,parentCaseId:null,remakeRepairReasonId:null,continuationStageId:null,continuationOperationalState:null,continuationBillingPolicyId:null,responsibility:null};}
  const parentId=text(body.parentCaseId);
  if(!parentId)throw new Error('Previous / Parent Case is required for a linked case.');
  if(parentId===caseId)throw new Error('A case cannot be its own parent.');
  const parent=await pool.query<{root_case_id:string;patient_id:string;practice_id:string;doctor_id:string}>('SELECT root_case_id,patient_id,practice_id,doctor_id FROM case_journey_cases WHERE tenant_id=$1 AND case_id=$2',[context.tenantId,parentId]);
  if(!parent.rowCount)throw new Error('Previous / Parent Case is not available in this tenant.');
  if(parent.rows[0]!.patient_id!==text(body.patientId))throw new Error('Parent case must belong to the selected patient.');
  if(parent.rows[0]!.practice_id!==text(body.practiceId)||parent.rows[0]!.doctor_id!==text(body.doctorId))throw new Error('Parent case must belong to the selected practice and doctor.');
  const rootCaseId=parent.rows[0]!.root_case_id;
  let reasonId:string|null=null,stageId:string|null=null,state:ContinuationOperationalState|null=null,policyId:string|null=null,responsibility:CaseJourneyResponsibility|null=null;
  if(relationship==='REMAKE'||relationship==='REPAIR'){
    reasonId=text(body.remakeRepairReasonId);if(!reasonId)throw new Error('A controlled remake/repair reason is required.');
    const reason=await pool.query('SELECT 1 FROM tenant_case_journey_reasons WHERE tenant_id=$1 AND id=$2 AND active=true',[context.tenantId,reasonId]);if(!reason.rowCount)throw new Error('Selected remake/repair reason is unavailable.');
    const input=body.responsibility;if(!input||!responsibilityKinds.has(input.responsibilityCategory))throw new Error('An explicit responsibility decision is required.');
    const clinic=percentage(input.clinicPercentage),lab=percentage(input.labPercentage);if(clinic===null||lab===null||clinic+lab!==10000)throw new Error('Clinic and laboratory responsibility must total exactly 100%.');
    responsibility={responsibilityCategory:input.responsibilityCategory,clinicPercentage:asPercent(clinic),labPercentage:asPercent(lab),confirmedBy:context.actorName,confirmedAt:new Date().toISOString(),notes:text(input.notes),evidenceReferences:Array.isArray(input.evidenceReferences)?input.evidenceReferences.filter(value=>typeof value==='string').map(value=>value.trim()).filter(Boolean):[]};
  }else{
    stageId=text(body.continuationStageId);if(!stageId)throw new Error('A continuation stage is required.');
    const stage=await pool.query('SELECT 1 FROM tenant_continuation_stages WHERE tenant_id=$1 AND id=$2 AND active=true',[context.tenantId,stageId]);if(!stage.rowCount)throw new Error('Selected continuation stage is unavailable.');
    const supplied=text(body.continuationOperationalState);if(!continuationStates.has(supplied as ContinuationOperationalState))throw new Error('A continuation operational state is required.');state=supplied as ContinuationOperationalState;
    const defaultPolicy=await pool.query<{id:string}>('SELECT id FROM tenant_continuation_billing_policies WHERE tenant_id=$1 AND active=true AND is_default=true LIMIT 1',[context.tenantId]);policyId=defaultPolicy.rows[0]?.id??'';
    if(!policyId)throw new Error('Tenant continuation billing policy is not configured.');
  }
  return{caseRelationship:relationship,rootCaseId,parentCaseId:parentId,remakeRepairReasonId:reasonId,continuationStageId:stageId,continuationOperationalState:state,continuationBillingPolicyId:policyId||null,responsibility};
}

export async function saveCaseJourneyWithClient(client:PoolClient,context:RepositoryContext,item:ClinicalCase,journey:PreparedJourney){
  await client.query(`INSERT INTO case_journey_cases(tenant_id,case_id,case_relationship,root_case_id,parent_case_id,patient_id,practice_id,doctor_id,continuation_operational_state,continuation_billing_policy_id,remake_repair_reason_id,continuation_stage_id,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`,[context.tenantId,item.id,journey.caseRelationship,journey.rootCaseId,journey.parentCaseId,item.patientId,item.practiceId,item.doctorId,journey.continuationOperationalState,journey.continuationBillingPolicyId,journey.remakeRepairReasonId,journey.continuationStageId,context.actorId]);
  if(journey.responsibility)await client.query(`INSERT INTO case_journey_responsibilities(tenant_id,case_id,responsibility_category,clinic_percentage,lab_percentage,confirmed_by,confirmed_at,notes,evidence_references) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb)`,[context.tenantId,item.id,journey.responsibility.responsibilityCategory,journey.responsibility.clinicPercentage,journey.responsibility.labPercentage,journey.responsibility.confirmedBy,journey.responsibility.confirmedAt,journey.responsibility.notes,JSON.stringify(journey.responsibility.evidenceReferences)]);
}
export async function saveCaseJourney(pool:Pool,context:RepositoryContext,item:ClinicalCase,journey:PreparedJourney){
  const client=await pool.connect();try{await client.query('BEGIN');await saveCaseJourneyWithClient(client,context,item,journey);await client.query('COMMIT');}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}
}

export async function journeyForCase(pool:Pool,context:RepositoryContext,caseId:string){
  const result=await pool.query(`SELECT c.case_relationship,c.root_case_id,c.parent_case_id,c.remake_repair_reason_id,c.continuation_stage_id,c.continuation_operational_state,c.continuation_billing_policy_id,r.responsibility_category,r.clinic_percentage::text,r.lab_percentage::text,r.confirmed_by,r.confirmed_at,r.notes,r.evidence_references FROM case_journey_cases c LEFT JOIN case_journey_responsibilities r ON r.tenant_id=c.tenant_id AND r.case_id=c.case_id WHERE c.tenant_id=$1 AND c.case_id=$2`,[context.tenantId,caseId]);const row=result.rows[0];if(!row)return null;return{caseRelationship:row.case_relationship as CaseRelationship,rootCaseId:row.root_case_id,parentCaseId:row.parent_case_id,remakeRepairReasonId:row.remake_repair_reason_id,continuationStageId:row.continuation_stage_id,continuationOperationalState:row.continuation_operational_state as ContinuationOperationalState|null,continuationBillingPolicyId:row.continuation_billing_policy_id,responsibility:row.responsibility_category?{responsibilityCategory:row.responsibility_category as CaseResponsibility,clinicPercentage:row.clinic_percentage,labPercentage:row.lab_percentage,confirmedBy:row.confirmed_by,confirmedAt:row.confirmed_at,notes:row.notes,evidenceReferences:row.evidence_references??[]}:null};
}

export function installCaseJourneyAdministration(app:Express,pool:Pool,context:RepositoryContext){
  app.use('/api/case-journey',async(_req,_res,next)=>{try{await ensureCaseJourneyDefaults(pool,context.tenantId);next();}catch(error){next(error)}});
  app.get('/api/case-journey/reasons',async(_req,res)=>res.json((await pool.query('SELECT id,code,category,label,active,suggested_responsibility AS "suggestedResponsibility" FROM tenant_case_journey_reasons WHERE tenant_id=$1 ORDER BY category,label',[context.tenantId])).rows));
  app.post('/api/case-journey/reasons',async(req:Request,res:Response)=>{const code=text(req.body?.code).toUpperCase(),category=text(req.body?.category),label=text(req.body?.label);if(!code||!['LAB_FABRICATION','CLINICAL_PRACTICE','REQUESTED_CHANGE','OTHER'].includes(category)||!label)return res.status(400).json({error:'Code, supported category, and label are required.'});const value=await pool.query(`INSERT INTO tenant_case_journey_reasons(tenant_id,code,category,label,suggested_responsibility) VALUES($1,$2,$3,$4,$5) RETURNING id,code,category,label,active,suggested_responsibility`,[context.tenantId,code,category,label,responsibilityKinds.has(req.body?.suggestedResponsibility)?req.body.suggestedResponsibility:null]);return res.status(201).json(value.rows[0]);});
  app.put('/api/case-journey/reasons/:id',async(req,res)=>{const value=await pool.query('UPDATE tenant_case_journey_reasons SET active=$3,label=COALESCE(NULLIF($4,\'\'),label),updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING id,code,category,label,active,suggested_responsibility',[context.tenantId,req.params.id,req.body?.active!==false,text(req.body?.label)]);return value.rowCount?res.json(value.rows[0]):res.status(404).json({error:'Reason not found.'});});
  app.get('/api/case-journey/stages',async(_req,res)=>res.json((await pool.query('SELECT id,code,label,active FROM tenant_continuation_stages WHERE tenant_id=$1 ORDER BY label',[context.tenantId])).rows));
  app.post('/api/case-journey/stages',async(req,res)=>{const code=text(req.body?.code).toUpperCase(),label=text(req.body?.label);if(!code||!label)return res.status(400).json({error:'Code and label are required.'});const value=await pool.query('INSERT INTO tenant_continuation_stages(tenant_id,code,label) VALUES($1,$2,$3) RETURNING id,code,label,active',[context.tenantId,code,label]);return res.status(201).json(value.rows[0]);});
  app.put('/api/case-journey/stages/:id',async(req,res)=>{const value=await pool.query('UPDATE tenant_continuation_stages SET active=$3,label=COALESCE(NULLIF($4,\'\'),label),updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING id,code,label,active',[context.tenantId,req.params.id,req.body?.active!==false,text(req.body?.label)]);return value.rowCount?res.json(value.rows[0]):res.status(404).json({error:'Continuation stage not found.'});});
  app.get('/api/case-journey/billing-policies',async(_req,res)=>res.json((await pool.query('SELECT id,policy_type AS "policyType",label,active,is_default AS "isDefault",metadata FROM tenant_continuation_billing_policies WHERE tenant_id=$1 ORDER BY is_default DESC,label',[context.tenantId])).rows));
  app.post('/api/case-journey/billing-policies',async(req,res)=>{const policyType=text(req.body?.policyType) as ContinuationBillingPolicyType,label=text(req.body?.label);if(!policyTypes.has(policyType)||!label)return res.status(400).json({error:'Supported policy type and label are required.'});const value=await pool.query('INSERT INTO tenant_continuation_billing_policies(tenant_id,policy_type,label,metadata,created_by) VALUES($1,$2,$3,$4::jsonb,$5) RETURNING id,policy_type AS "policyType",label,active,is_default AS "isDefault",metadata',[context.tenantId,policyType,label,JSON.stringify(req.body?.metadata&&typeof req.body.metadata==='object'?req.body.metadata:{}),context.actorId]);return res.status(201).json(value.rows[0]);});
  app.put('/api/case-journey/billing-policies/:id',async(req,res)=>{const value=await pool.query('UPDATE tenant_continuation_billing_policies SET active=$3,label=COALESCE(NULLIF($4,\'\'),label),metadata=COALESCE($5::jsonb,metadata),updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING id,policy_type AS "policyType",label,active,is_default AS "isDefault",metadata',[context.tenantId,req.params.id,req.body?.active!==false,text(req.body?.label),req.body?.metadata&&typeof req.body.metadata==='object'?JSON.stringify(req.body.metadata):null]);return value.rowCount?res.json(value.rows[0]):res.status(404).json({error:'Continuation billing policy not found.'});});
  app.put('/api/case-journey/billing-policies/:id/default',async(req,res)=>{const type=text(req.body?.policyType);if(type&&!policyTypes.has(type as ContinuationBillingPolicyType))return res.status(400).json({error:'Unsupported continuation billing policy.'});const client=await pool.connect();try{await client.query('BEGIN');await client.query('UPDATE tenant_continuation_billing_policies SET is_default=false,updated_at=now() WHERE tenant_id=$1',[context.tenantId]);const value=await client.query('UPDATE tenant_continuation_billing_policies SET is_default=true,updated_at=now() WHERE tenant_id=$1 AND id=$2 AND active=true RETURNING id,policy_type,label,active,is_default,metadata',[context.tenantId,req.params.id]);if(!value.rowCount)throw new Error('Policy not found.');await client.query('COMMIT');return res.json(value.rows[0]);}catch(error){await client.query('ROLLBACK');return res.status(404).json({error:error instanceof Error?error.message:'Policy not found.'});}finally{client.release();}});
  app.get('/api/cases/:id/journey',async(req,res)=>{const current=await journeyForCase(pool,context,req.params.id);if(!current)return res.status(404).json({error:'Case journey not found.'});const rows=await pool.query(`SELECT item.case_id,item.case_relationship,item.parent_case_id,item.root_case_id,item.continuation_operational_state,doc.payload->>'caseNumber' AS case_number,doc.payload->>'restoration' AS restoration,doc.payload->>'material' AS material,doc.payload->>'status' AS status,reason.label AS reason_label,stage.label AS stage_label FROM case_journey_cases item JOIN repository_documents doc ON doc.tenant_id=item.tenant_id AND doc.entity_type='case' AND doc.entity_id=item.case_id LEFT JOIN tenant_case_journey_reasons reason ON reason.tenant_id=item.tenant_id AND reason.id=item.remake_repair_reason_id LEFT JOIN tenant_continuation_stages stage ON stage.tenant_id=item.tenant_id AND stage.id=item.continuation_stage_id WHERE item.tenant_id=$1 AND item.root_case_id=$2 ORDER BY item.created_at`,[context.tenantId,current.rootCaseId]);res.json({current,items:rows.rows});});
}
