import { randomUUID } from 'node:crypto';
import type { Express, Request, Response } from 'express';
import type { Pool, PoolClient } from 'pg';
import type { ObjectStorage, StoredObjectKind } from './infrastructure/object-storage.js';
import type { RepositoryContext } from './infrastructure/contracts.js';
import { calendarDate, loadTenantClosureDates } from './case-builder.js';

type Db=Pool|PoolClient;
type IntakeMethod='DIGITAL'|'PHYSICAL'|'HYBRID';
const intakeMethods=new Set<IntakeMethod>(['DIGITAL','PHYSICAL','HYBRID']);
const text=(value:unknown)=>typeof value==='string'?value.trim():'';
const object=(value:unknown)=>value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{};
const list=(value:unknown)=>Array.isArray(value)?value.filter(value=>typeof value==='string').map(value=>value.trim()).filter(Boolean):[];
const dateKey=(value:Date)=>value.toISOString().slice(0,10);
const current=()=>new Date();
const iso=()=>current().toISOString();
const fileKinds:Record<string,StoredObjectKind>={LAB_SLIP:'intake-document',PRESCRIPTION:'prescription-pdf',PDF:'rx-pdf',PHOTO:'clinical-photo',SHADE_PHOTO:'shade-photo',STL:'stl',OBJ:'obj',PLY:'ply',DICOM_CBCT:'dicom',X_RAY:'xray',XRAY:'xray',PHOTOGRAMMETRY:'intake-document',INSTRUCTIONS:'intake-document',SCAN:'intake-document',QC_RECORD:'qc-photo',QC:'qc-photo',VENDOR_DOCUMENT:'shipping-document',SHIPPING_DOCUMENT:'shipping-document',OTHER:'intake-document'};

export function intakeMethod(value:unknown,fallback: IntakeMethod='DIGITAL'):IntakeMethod{
  const candidate=text(value).toUpperCase();
  if(!candidate)return fallback;
  if(!intakeMethods.has(candidate as IntakeMethod))throw new Error('Select Digital, Physical, or Hybrid case intake.');
  return candidate as IntakeMethod;
}

export async function initializeCaseOperationsWithClient(client:PoolClient,context:RepositoryContext,caseId:string,method:unknown,calculatedDueDate:unknown){
  const due=text(calculatedDueDate);
  await client.query(`INSERT INTO case_intake_profiles(tenant_id,case_entity_type,case_id,intake_method,lifecycle_state,original_calculated_due_date,current_calculated_due_date,created_by)
    VALUES($1,'case',$2,$3,'ACTIVE',$4::date,$4::date,$5) ON CONFLICT(tenant_id,case_entity_type,case_id) DO NOTHING`,[context.tenantId,caseId,intakeMethod(method),due||null,context.actorId]);
  await event(client,context,caseId,'CASE_INTAKE_METHOD_RECORDED',null,{intakeMethod:intakeMethod(method)});
}

async function event(db:Db,context:RepositoryContext,caseId:string,eventType:string,lineId:string|null,metadata:Record<string,unknown>={}){
  await db.query(`INSERT INTO case_operational_events(tenant_id,case_entity_type,case_id,case_product_line_id,event_type,actor_id,actor_name,metadata)
    VALUES($1,'case',$2,$3,$4,$5,$6,$7::jsonb)`,[context.tenantId,caseId,lineId,eventType,context.actorId,context.actorName,JSON.stringify(metadata)]);
}
async function caseExists(db:Db,context:RepositoryContext,caseId:string){return Boolean((await db.query(`SELECT 1 FROM repository_documents WHERE tenant_id=$1 AND entity_type='case' AND entity_id=$2 AND deleted_at IS NULL`,[context.tenantId,caseId])).rowCount);}
async function profile(db:Db,context:RepositoryContext,caseId:string){
  const result=await db.query(`SELECT intake_method AS "intakeMethod",lifecycle_state AS "lifecycleState",original_calculated_due_date::text AS "originalCalculatedDueDate",current_calculated_due_date::text AS "currentCalculatedDueDate",created_at AS "createdAt",updated_at AS "updatedAt" FROM case_intake_profiles WHERE tenant_id=$1 AND case_entity_type='case' AND case_id=$2`,[context.tenantId,caseId]);
  return result.rows[0]??null;
}
function businessDays(start:Date,end:Date,closures:Set<string>){let cursor=new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth(),start.getUTCDate(),12)),count=0;while(cursor<end){cursor.setUTCDate(cursor.getUTCDate()+1);if(cursor<=end&&cursor.getUTCDay()!==0&&cursor.getUTCDay()!==6&&!closures.has(dateKey(cursor)))count++;}return count;}
function addBusinessDays(start:string,days:number,closures:Set<string>){const cursor=new Date(`${calendarDate(start,'due date')}T12:00:00Z`);let remaining=days;while(remaining>0){cursor.setUTCDate(cursor.getUTCDate()+1);if(cursor.getUTCDay()!==0&&cursor.getUTCDay()!==6&&!closures.has(dateKey(cursor)))remaining--;}return dateKey(cursor);}

async function serialCase(db:Db,context:RepositoryContext,caseId:string){
  const value=await db.query<{payload:Record<string,unknown>}>(`SELECT payload FROM repository_documents WHERE tenant_id=$1 AND entity_type='case' AND entity_id=$2 AND deleted_at IS NULL`,[context.tenantId,caseId]);
  return value.rows[0]?.payload??null;
}
async function requireCase(db:Db,context:RepositoryContext,caseId:string,res:Response){if(await caseExists(db,context,caseId))return true;res.status(404).json({error:'Case not found.'});return false;}

export function installCaseOperations(app:Express,pool:Pool,objects:ObjectStorage,context:RepositoryContext){
  app.get('/api/case-operations/hold-reasons',async(_req,res)=>res.json((await pool.query(`SELECT id,code,category,label,pauses_tat AS "pausesTat",active,display_order AS "displayOrder" FROM tenant_case_hold_reasons WHERE tenant_id=$1 ORDER BY category,display_order,label`,[context.tenantId])).rows));
  app.get('/api/case-operations/cancellation-reasons',async(_req,res)=>res.json((await pool.query(`SELECT id,code,category,label,active,display_order AS "displayOrder" FROM tenant_case_cancellation_reasons WHERE tenant_id=$1 ORDER BY category,display_order,label`,[context.tenantId])).rows));
  app.get('/api/cases/:caseId/operations',async(req,res)=>{
    if(!await requireCase(pool,context,req.params.caseId,res))return;
    const [intake,holds,cancellation,files,fulfillment,packages]=await Promise.all([
      profile(pool,context,req.params.caseId),
      pool.query(`SELECT hold.id,reason.code AS "reasonCode",reason.label AS "reasonLabel",hold.notes,hold.placed_by AS "placedBy",hold.hold_start AS "holdStart",hold.pauses_tat AS "pausesTat",hold.released_by AS "releasedBy",hold.released_at AS "releasedAt",hold.release_note AS "releaseNote",hold.paused_business_duration AS "pausedBusinessDuration",hold.recalculated_due_date::text AS "recalculatedDueDate" FROM case_hold_events hold JOIN tenant_case_hold_reasons reason ON reason.tenant_id=hold.tenant_id AND reason.id=hold.reason_id WHERE hold.tenant_id=$1 AND hold.case_id=$2 ORDER BY hold.hold_start DESC`,[context.tenantId,req.params.caseId]),
      pool.query(`SELECT cancellation.id,reason.code AS "reasonCode",reason.label AS "reasonLabel",cancellation.notes,cancellation.cancelled_by AS "cancelledBy",cancellation.cancelled_at AS "cancelledAt",cancellation.prior_lifecycle_state AS "priorLifecycleState" FROM case_cancellations cancellation JOIN tenant_case_cancellation_reasons reason ON reason.tenant_id=cancellation.tenant_id AND reason.id=cancellation.reason_id WHERE cancellation.tenant_id=$1 AND cancellation.case_id=$2`,[context.tenantId,req.params.caseId]),
      pool.query(`SELECT file.id,file.display_name AS "displayName",file.original_file_name AS "originalFileName",file.document_category AS "documentCategory",file.description,file.source_kind AS "sourceKind",file.parent_file_id AS "parentFileId",file.availability_state AS "availabilityState",file.uploaded_by AS "uploadedBy",file.uploaded_at AS "uploadedAt",record.mime_type AS "mimeType",record.size_bytes::text AS "sizeBytes",record.checksum_sha256 AS "checksumSha256" FROM case_files file JOIN object_records record ON record.id=file.object_id AND record.tenant_id=file.tenant_id WHERE file.tenant_id=$1 AND file.case_id=$2 ORDER BY file.uploaded_at DESC`,[context.tenantId,req.params.caseId]),
      pool.query(`SELECT line.id AS "lineId",line.product_sku_snapshot AS "productSku",line.product_name_snapshot AS "productName",fulfillment.fulfillment_mode AS "fulfillmentMode",fulfillment.vendor_name AS "vendorName",fulfillment.notes FROM case_product_lines line LEFT JOIN case_product_line_fulfillment fulfillment ON fulfillment.tenant_id=line.tenant_id AND fulfillment.case_product_line_id=line.id WHERE line.tenant_id=$1 AND line.case_id=$2 AND line.state<>'CANCELLED' ORDER BY line.line_number`,[context.tenantId,req.params.caseId]),
      pool.query(`SELECT id,vendor_name AS "vendorName",package_status AS "packageStatus",delivery_channel AS "deliveryChannel",tracking_reference AS "trackingReference",prepared_by AS "preparedBy",prepared_at AS "preparedAt",sent_at AS "sentAt" FROM vendor_case_packages WHERE tenant_id=$1 AND case_id=$2 ORDER BY prepared_at DESC`,[context.tenantId,req.params.caseId])
    ]);
    res.json({intake,holds:holds.rows,cancellation:cancellation.rows[0]??null,files:files.rows,fulfillment:fulfillment.rows,packages:packages.rows,storage:{provider:'postgres',durable:true,publicUrls:false}});
  });
  app.put('/api/cases/:caseId/intake-method',async(req,res)=>{
    if(!await requireCase(pool,context,req.params.caseId,res))return;try{const method=intakeMethod(req.body?.intakeMethod);await pool.query(`UPDATE case_intake_profiles SET intake_method=$3,updated_at=now() WHERE tenant_id=$1 AND case_id=$2`,[context.tenantId,req.params.caseId,method]);await event(pool,context,req.params.caseId,'CASE_INTAKE_METHOD_UPDATED',null,{intakeMethod:method});res.json(await profile(pool,context,req.params.caseId));}catch(error){res.status(400).json({error:error instanceof Error?error.message:'Unable to update intake method.'})}
  });
  app.get('/api/cases/:caseId/intake-routing',async(req,res)=>{
    if(!await requireCase(pool,context,req.params.caseId,res))return;const value=await profile(pool,context,req.params.caseId);if(!value)return res.status(409).json({error:'Case intake profile is unavailable.'});
    const lines=await pool.query<{configuration:Record<string,unknown>;category_code:string;family_code_snapshot:string}>(`SELECT configuration,category_code,family_code_snapshot FROM case_product_lines WHERE tenant_id=$1 AND case_id=$2 AND state<>'CANCELLED'`,[context.tenantId,req.params.caseId]);
    const status=(key:string)=>lines.rows.some(line=>Boolean(object(line.configuration)[key]))?'CONFIGURED':'REQUIRED';
    const digital=['Lab Slip / Prescription','Prep Scan','Opposing Scan','Bite',...(lines.rows.some(line=>line.category_code==='IMP')?['Implant scan data']:[])].map(label=>({label,status:label==='Prep Scan'?status('prepProvided'):label==='Opposing Scan'?status('opposingProvided'):label==='Bite'?status('biteProvided'):'REQUIRED'}));
    const physical=['Physical Lab Slip','Impressions / models','Received components','Screws / jigs / analogs','Fit-to items','Enclosures','Condition received','Physical logistics status'].map(label=>({label,status:'REQUIRED'}));
    res.json({intakeMethod:value.intakeMethod,digital:value.intakeMethod==='PHYSICAL'?[]:digital,physical:value.intakeMethod==='DIGITAL'?[]:physical});
  });
  app.post('/api/cases/:caseId/hold',async(req,res)=>{
    if(!await requireCase(pool,context,req.params.caseId,res))return;const reasonId=text(req.body?.reasonId),notes=text(req.body?.notes),client=await pool.connect();try{await client.query('BEGIN');const intake=await profile(client,context,req.params.caseId);if(!intake)throw new Error('Case intake profile is unavailable.');if(intake.lifecycleState==='CANCELLED')throw new Error('Cancelled cases cannot be placed on hold.');if(intake.lifecycleState==='ON_HOLD')throw new Error('Case is already on hold.');const reason=await client.query<{pauses_tat:boolean}>(`SELECT pauses_tat FROM tenant_case_hold_reasons WHERE tenant_id=$1 AND id=$2 AND active`,[context.tenantId,reasonId]);if(!reason.rowCount)throw new Error('Select an active controlled hold reason.');await client.query(`INSERT INTO case_hold_events(tenant_id,case_id,reason_id,notes,placed_by,workflow_state_before,original_calculated_due_date,pauses_tat) VALUES($1,$2,$3,$4,$5,$6,$7::date,$8)`,[context.tenantId,req.params.caseId,reasonId,notes,context.actorName,intake.lifecycleState,intake.currentCalculatedDueDate,reason.rows[0]!.pauses_tat]);await client.query(`UPDATE case_intake_profiles SET lifecycle_state='ON_HOLD',updated_at=now() WHERE tenant_id=$1 AND case_id=$2`,[context.tenantId,req.params.caseId]);await event(client,context,req.params.caseId,'CASE_PLACED_ON_HOLD',null,{reasonId,pausesTat:reason.rows[0]!.pauses_tat,notes});await client.query('COMMIT');res.status(201).json(await profile(pool,context,req.params.caseId));}catch(error){await client.query('ROLLBACK');res.status(409).json({error:error instanceof Error?error.message:'Unable to place Case on hold.'});}finally{client.release();}
  });
  app.post('/api/cases/:caseId/release-hold',async(req,res)=>{
    if(!await requireCase(pool,context,req.params.caseId,res))return;const note=text(req.body?.note),client=await pool.connect();try{await client.query('BEGIN');const hold=(await client.query<{id:string;hold_start:Date;pauses_tat:boolean;original_calculated_due_date:string|null}>(`SELECT id,hold_start,pauses_tat,original_calculated_due_date::text FROM case_hold_events WHERE tenant_id=$1 AND case_id=$2 AND released_at IS NULL FOR UPDATE`,[context.tenantId,req.params.caseId])).rows[0];if(!hold)throw new Error('There is no active hold to release.');const intake=await profile(client,context,req.params.caseId);if(!intake)throw new Error('Case intake profile is unavailable.');const closures=new Set(await loadTenantClosureDates(client,context.tenantId)),paused=hold.pauses_tat?businessDays(hold.hold_start,current(),closures):0,base=hold.original_calculated_due_date??intake.currentCalculatedDueDate,recalculated=base&&paused?addBusinessDays(base,paused,closures):base;await client.query(`UPDATE case_hold_events SET released_by=$3,released_at=now(),release_note=$4,resumed_state='RELEASED',paused_business_duration=$5,recalculated_due_date=$6::date WHERE tenant_id=$1 AND id=$2`,[context.tenantId,hold.id,context.actorName,note,paused,recalculated??null]);await client.query(`UPDATE case_intake_profiles SET lifecycle_state='RELEASED',current_calculated_due_date=$3::date,updated_at=now() WHERE tenant_id=$1 AND case_id=$2`,[context.tenantId,req.params.caseId,recalculated??null]);await event(client,context,req.params.caseId,'CASE_HOLD_RELEASED',null,{pausedBusinessDuration:paused,recalculatedDueDate:recalculated??null,note});await client.query('COMMIT');res.json(await profile(pool,context,req.params.caseId));}catch(error){await client.query('ROLLBACK');res.status(409).json({error:error instanceof Error?error.message:'Unable to release Case hold.'});}finally{client.release();}
  });
  app.post('/api/cases/:caseId/cancel',async(req,res)=>{
    if(!await requireCase(pool,context,req.params.caseId,res))return;const reasonId=text(req.body?.reasonId),notes=text(req.body?.notes);if(req.body?.confirmed!==true)return res.status(400).json({error:'Cancellation confirmation is required.'});const client=await pool.connect();try{await client.query('BEGIN');const intake=await profile(client,context,req.params.caseId);if(!intake)throw new Error('Case intake profile is unavailable.');if(intake.lifecycleState==='CANCELLED')throw new Error('Case is already cancelled.');const reason=await client.query('SELECT 1 FROM tenant_case_cancellation_reasons WHERE tenant_id=$1 AND id=$2 AND active',[context.tenantId,reasonId]);if(!reason.rowCount)throw new Error('Select an active controlled cancellation reason.');await client.query(`INSERT INTO case_cancellations(tenant_id,case_id,reason_id,notes,cancelled_by,prior_lifecycle_state) VALUES($1,$2,$3,$4,$5,$6)`,[context.tenantId,req.params.caseId,reasonId,notes,context.actorName,intake.lifecycleState]);await client.query(`UPDATE case_intake_profiles SET lifecycle_state='CANCELLED',updated_at=now() WHERE tenant_id=$1 AND case_id=$2`,[context.tenantId,req.params.caseId]);await event(client,context,req.params.caseId,'CASE_CANCELLED',null,{reasonId,notes,priorLifecycleState:intake.lifecycleState});await client.query('COMMIT');res.status(201).json(await profile(pool,context,req.params.caseId));}catch(error){await client.query('ROLLBACK');res.status(409).json({error:error instanceof Error?error.message:'Unable to cancel Case.'});}finally{client.release();}
  });
  app.post('/api/cases/:caseId/files',async(req,res)=>{
    if(!await requireCase(pool,context,req.params.caseId,res))return;const body=object(req.body),fileName=text(body.fileName),mimeType=text(body.mimeType)||'application/octet-stream',category=text(body.documentCategory).toUpperCase(),encoded=text(body.contentBase64);if(!fileName||!category||!encoded||!fileKinds[category])return res.status(400).json({error:'Document category, filename, and binary content are required.'});const bytes=Buffer.from(encoded,'base64');if(!bytes.length||bytes.byteLength>20*1024*1024)return res.status(400).json({error:'A non-empty Case File no larger than 20 MB is required.'});const sourceKind=text(body.sourceKind).toUpperCase()==='DERIVED'?'DERIVED':'ORIGINAL',parentFileId=text(body.parentFileId)||null;if(sourceKind==='DERIVED'&&!parentFileId)return res.status(400).json({error:'A derived Case File requires its parent source file.'});try{if(parentFileId){const parent=await pool.query('SELECT 1 FROM case_files WHERE tenant_id=$1 AND case_id=$2 AND id=$3',[context.tenantId,req.params.caseId,parentFileId]);if(!parent.rowCount)throw new Error('Parent Case File is unavailable in this tenant.');}const stored=await objects.put({tenantId:context.tenantId,ownerType:'case-file',ownerId:req.params.caseId,kind:fileKinds[category]!,fileName,mimeType,bytes});const created=await pool.query(`INSERT INTO case_files(tenant_id,case_id,object_id,original_file_name,display_name,document_category,description,source_kind,parent_file_id,uploaded_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id,display_name AS "displayName",document_category AS "documentCategory",source_kind AS "sourceKind",uploaded_at AS "uploadedAt"`,[context.tenantId,req.params.caseId,stored.id,fileName,text(body.displayName)||fileName,category,text(body.description),sourceKind,parentFileId,context.actorName]);for(const lineId of list(body.productLineIds)){const line=await pool.query('SELECT 1 FROM case_product_lines WHERE tenant_id=$1 AND case_id=$2 AND id=$3',[context.tenantId,req.params.caseId,lineId]);if(line.rowCount)await pool.query(`INSERT INTO case_file_product_line_links(tenant_id,case_file_id,case_product_line_id) VALUES($1,$2,$3) ON CONFLICT DO NOTHING`,[context.tenantId,created.rows[0]!.id,lineId]);}await event(pool,context,req.params.caseId,'CASE_FILE_UPLOADED',null,{caseFileId:created.rows[0]!.id,category,sourceKind,objectId:stored.id});res.status(201).json(created.rows[0]);}catch(error){res.status(400).json({error:error instanceof Error?error.message:'Unable to store Case File.'})}
  });
  app.get('/api/cases/:caseId/files/:fileId/download',async(req,res)=>{
    const record=await pool.query<{object_key:string;mime_type:string;display_name:string}>(`SELECT object.object_key,object.mime_type,file.display_name FROM case_files file JOIN object_records object ON object.id=file.object_id AND object.tenant_id=file.tenant_id AND object.deleted_at IS NULL WHERE file.tenant_id=$1 AND file.case_id=$2 AND file.id=$3 AND file.availability_state='AVAILABLE'`,[context.tenantId,req.params.caseId,req.params.fileId]);const row=record.rows[0];if(!row)return res.status(404).json({error:'Case File is not available.'});const bytes=await objects.get(row.object_key);if(!bytes)return res.status(410).json({error:'Case File binary is unavailable.'});res.setHeader('Content-Type',row.mime_type);res.setHeader('Content-Disposition',`attachment; filename="${row.display_name.replaceAll('"','')}"`);res.send(Buffer.from(bytes));
  });
  app.patch('/api/cases/:caseId/files/:fileId',async(req,res)=>{const body=object(req.body);const result=await pool.query(`UPDATE case_files SET display_name=COALESCE(NULLIF($4,''),display_name),description=COALESCE($5,description),document_category=COALESCE(NULLIF($6,''),document_category),updated_at=now() WHERE tenant_id=$1 AND case_id=$2 AND id=$3 RETURNING id,display_name AS "displayName",description,document_category AS "documentCategory"`,[context.tenantId,req.params.caseId,req.params.fileId,text(body.displayName),typeof body.description==='string'?body.description:null,text(body.documentCategory).toUpperCase()]);if(!result.rowCount)return res.status(404).json({error:'Case File not found.'});await event(pool,context,req.params.caseId,'CASE_FILE_METADATA_UPDATED',null,{caseFileId:req.params.fileId});res.json(result.rows[0]);});
  app.post('/api/cases/:caseId/files/:fileId/archive',async(req,res)=>{const result=await pool.query(`UPDATE case_files SET availability_state='ARCHIVED',archived_by=$4,archived_at=now(),updated_at=now() WHERE tenant_id=$1 AND case_id=$2 AND id=$3 AND availability_state<>'ARCHIVED' RETURNING id`,[context.tenantId,req.params.caseId,req.params.fileId,context.actorName]);if(!result.rowCount)return res.status(404).json({error:'Available Case File not found.'});await event(pool,context,req.params.caseId,'CASE_FILE_ARCHIVED',null,{caseFileId:req.params.fileId});res.status(204).send();});
  app.put('/api/cases/:caseId/product-lines/:lineId/fulfillment',async(req,res)=>{const mode=text(req.body?.fulfillmentMode).toUpperCase(),vendorName=text(req.body?.vendorName);if(!['IN_HOUSE','OUTSOURCED','SPLIT_HYBRID'].includes(mode)||((mode==='OUTSOURCED'||mode==='SPLIT_HYBRID')&&!vendorName))return res.status(400).json({error:'Fulfillment mode and vendor when outsourced are required.'});const line=await pool.query('SELECT 1 FROM case_product_lines WHERE tenant_id=$1 AND case_id=$2 AND id=$3',[context.tenantId,req.params.caseId,req.params.lineId]);if(!line.rowCount)return res.status(404).json({error:'Case Product Line not found.'});await pool.query(`INSERT INTO case_product_line_fulfillment(tenant_id,case_product_line_id,fulfillment_mode,vendor_name,notes,updated_by) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(tenant_id,case_product_line_id) DO UPDATE SET fulfillment_mode=EXCLUDED.fulfillment_mode,vendor_name=EXCLUDED.vendor_name,notes=EXCLUDED.notes,updated_by=EXCLUDED.updated_by,updated_at=now()`,[context.tenantId,req.params.lineId,mode,vendorName||null,text(req.body?.notes),context.actorName]);await event(pool,context,req.params.caseId,'PRODUCT_LINE_FULFILLMENT_UPDATED',req.params.lineId,{fulfillmentMode:mode,vendorName:vendorName||null});res.status(204).send();});
  app.post('/api/cases/:caseId/vendor-packages',async(req,res)=>{if(!await requireCase(pool,context,req.params.caseId,res))return;const vendorName=text(req.body?.vendorName),channel=text(req.body?.deliveryChannel).toUpperCase(),lineIds=list(req.body?.productLineIds),fileIds=list(req.body?.fileIds);if(!vendorName||!['SECURE_EMAIL','DROPBOX_INTEGRATION','VENDOR_PORTAL','PHYSICAL_SHIPMENT'].includes(channel)||!lineIds.length)return res.status(400).json({error:'Vendor, delivery channel, and selected Case Product Lines are required.'});const client=await pool.connect();try{await client.query('BEGIN');const created=await client.query<{id:string}>(`INSERT INTO vendor_case_packages(tenant_id,case_id,vendor_name,delivery_channel,prepared_by,tracking_reference) VALUES($1,$2,$3,$4,$5,$6) RETURNING id`,[context.tenantId,req.params.caseId,vendorName,channel,context.actorName,text(req.body?.trackingReference)||null]);const id=created.rows[0]!.id;for(const lineId of lineIds){const valid=await client.query('SELECT 1 FROM case_product_lines WHERE tenant_id=$1 AND case_id=$2 AND id=$3',[context.tenantId,req.params.caseId,lineId]);if(!valid.rowCount)throw new Error('Selected Product Line is unavailable.');await client.query(`INSERT INTO vendor_case_package_product_lines(tenant_id,package_id,case_product_line_id) VALUES($1,$2,$3)`,[context.tenantId,id,lineId]);}for(const fileId of fileIds){const valid=await client.query(`SELECT 1 FROM case_files WHERE tenant_id=$1 AND case_id=$2 AND id=$3 AND availability_state='AVAILABLE'`,[context.tenantId,req.params.caseId,fileId]);if(!valid.rowCount)throw new Error('Selected Case File is unavailable.');await client.query(`INSERT INTO vendor_case_package_files(tenant_id,package_id,case_file_id) VALUES($1,$2,$3)`,[context.tenantId,id,fileId]);}await event(client,context,req.params.caseId,'VENDOR_PACKAGE_PREPARED',null,{packageId:id,vendorName,deliveryChannel:channel,lineCount:lineIds.length,fileCount:fileIds.length});await client.query('COMMIT');res.status(201).json({id,packageStatus:'READY',deliveryConfigured:false,message:'Package is prepared. No external provider was invoked.'});}catch(error){await client.query('ROLLBACK');res.status(409).json({error:error instanceof Error?error.message:'Unable to prepare Vendor Package.'});}finally{client.release();}});
  app.get('/api/operations/kpi',async(req,res)=>{
    const rank=Number(text(req.query.rank).replace('TOP_',''))||10,limit=[10,25,50,75,100].includes(rank)?rank:10,group=text(req.query.groupBy)||'PRODUCT';
    const timeframe=text(req.query.timeframe).toUpperCase(),customStart=text(req.query.startDate);const nowDate=current();const start=timeframe==='DAY'?new Date(Date.UTC(nowDate.getUTCFullYear(),nowDate.getUTCMonth(),nowDate.getUTCDate())):timeframe==='WEEK'?new Date(Date.UTC(nowDate.getUTCFullYear(),nowDate.getUTCMonth(),nowDate.getUTCDate()-nowDate.getUTCDay())):timeframe==='MONTH'?new Date(Date.UTC(nowDate.getUTCFullYear(),nowDate.getUTCMonth(),1)):timeframe==='QUARTER'?new Date(Date.UTC(nowDate.getUTCFullYear(),Math.floor(nowDate.getUTCMonth()/3)*3,1)):timeframe==='YEAR'?new Date(Date.UTC(nowDate.getUTCFullYear(),0,1)):timeframe==='CUSTOM'&&/^\d{4}-\d{2}-\d{2}$/.test(customStart)?new Date(`${customStart}T00:00:00Z`):null;
    const groups:Record<string,string>={PRACTICE:`document.payload->>'practiceId'`,DOCTOR:`document.payload->>'doctorId'`,CATEGORY:`line.category_code`,SUBTYPE:`line.options->'restorationSubtype'->>'label'`,PRODUCT:`line.product_sku_snapshot`,MATERIAL:`line.description_snapshot`,INTAKE_METHOD:`profile.intake_method`,FULFILLMENT:`COALESCE(fulfillment.fulfillment_mode,'IN_HOUSE')`};
    const expression=groups[group]??groups.PRODUCT!;
    const rows=await pool.query(`SELECT ${expression} AS "group",count(DISTINCT document.entity_id)::int AS "caseCount",COALESCE(sum(line.quantity),0)::numeric::text AS "unitQuantity",count(*) FILTER (WHERE profile.lifecycle_state='ON_HOLD')::int AS "holdCount",count(*) FILTER (WHERE profile.lifecycle_state='CANCELLED')::int AS "cancellationCount",count(*) FILTER (WHERE journey.case_relationship='REMAKE')::int AS "remakeCount",count(*) FILTER (WHERE journey.case_relationship='REPAIR')::int AS "repairCount" FROM repository_documents document JOIN case_intake_profiles profile ON profile.tenant_id=document.tenant_id AND profile.case_id=document.entity_id LEFT JOIN case_product_lines line ON line.tenant_id=document.tenant_id AND line.case_id=document.entity_id AND line.state<>'CANCELLED' LEFT JOIN case_product_line_fulfillment fulfillment ON fulfillment.tenant_id=line.tenant_id AND fulfillment.case_product_line_id=line.id LEFT JOIN case_journey_cases journey ON journey.tenant_id=document.tenant_id AND journey.case_id=document.entity_id WHERE document.tenant_id=$1 AND document.entity_type='case' AND document.deleted_at IS NULL AND ($3::timestamptz IS NULL OR document.created_at >= $3::timestamptz) GROUP BY ${expression} ORDER BY count(DISTINCT document.entity_id) DESC,${expression} NULLS LAST LIMIT $2`,[context.tenantId,limit,start?.toISOString()??null]);
    const total=rows.rows.reduce((sum,row)=>sum+Number(row.caseCount),0);res.json({groupBy:group,rank:limit,timeframe:timeframe||'ALL',rows:rows.rows.map((row,index)=>({...row,rank:index+1,sharePercent:total?Math.round(Number(row.caseCount)*10000/total)/100:0})),financialAuthority:{available:false,message:'PP-1C invoice lines and approved costing data are required for revenue and margin analytics.'}});
  });
}
