import { randomUUID } from 'node:crypto';
import type { Express, Response } from 'express';
import type { Pool, PoolClient } from 'pg';
import type { ObjectStorage, StoredObjectKind } from './infrastructure/object-storage.js';
import type { SecurityRequest } from './security.js';

type EntityType='practice'|'doctor'|'patient'|'case'|'shipment'|'invoice';
type EventType='phone-call'|'email'|'internal-note'|'doctor-message'|'laboratory-message'|'production-update'|'qc-comment'|'shipping-event'|'billing-event'|'attachment'|'system-event';
type Priority='low'|'normal'|'high'|'urgent';

type EventInput={entityType:EntityType;entityId:string;threadId?:string;eventType:EventType;content:string;versionOf?:string;attachmentObjectIds?:string[];attachments?:Array<{fileName:string;mimeType:string;kind:StoredObjectKind;contentBase64:string}>;notify?:Array<{userId:string;priority?:Priority;category?:string}>};
type SearchQuery={entityType?:string;entityId?:string;actorId?:string;eventType?:string;from?:string;to?:string;q?:string};

function identity(req:SecurityRequest){if(!req.identity)throw new Error('Authenticated identity required.');return req.identity}
function text(value:unknown){return typeof value==='string'?value.trim():''}
function rowEvent(row:Record<string,unknown>){return{id:row.id,tenantId:row.tenant_id,threadId:row.thread_id,entityType:row.entity_type,entityId:row.entity_id,eventType:row.event_type,content:row.content,actorId:row.actor_id,actorName:row.actor_name,actorRole:row.actor_role,versionOf:row.version_of,occurredAt:row.occurred_at,attachments:row.attachments??[]}}

async function insertEvent(client:PoolClient,pool:Pool,objects:ObjectStorage,req:SecurityRequest,input:EventInput){
 const actor=identity(req);const id=randomUUID();
 await client.query(`INSERT INTO communication_events(id,tenant_id,thread_id,entity_type,entity_id,event_type,content,actor_id,actor_name,actor_role,version_of) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[id,actor.tenantId,input.threadId??null,input.entityType,input.entityId,input.eventType,text(input.content),actor.userId,actor.name,actor.role,input.versionOf??null]);
 const objectIds=[...(input.attachmentObjectIds??[])];
 for(const attachment of input.attachments??[]){const stored=await objects.put({tenantId:actor.tenantId,ownerType:'communication-event',ownerId:id,kind:attachment.kind,fileName:attachment.fileName,mimeType:attachment.mimeType,bytes:Buffer.from(attachment.contentBase64,'base64'),metadata:{entityType:input.entityType,entityId:input.entityId}});objectIds.push(stored.id)}
 for(const objectId of objectIds){const exists=await pool.query('SELECT 1 FROM object_records WHERE id=$1 AND tenant_id=$2 AND deleted_at IS NULL',[objectId,actor.tenantId]);if(!exists.rowCount)throw new Error(`Attachment object ${objectId} was not found.`);await client.query('INSERT INTO communication_attachments(tenant_id,event_id,object_id) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[actor.tenantId,id,objectId])}
 for(const notice of input.notify??[]){await client.query(`INSERT INTO communication_notifications(tenant_id,event_id,recipient_user_id,priority,category) VALUES($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING`,[actor.tenantId,id,notice.userId,notice.priority??'normal',notice.category??input.eventType])}
 const result=await client.query(`SELECT e.*,COALESCE(jsonb_agg(jsonb_build_object('id',o.id,'fileName',o.file_name,'mimeType',o.mime_type,'size',o.size_bytes,'objectKey',o.object_key)) FILTER(WHERE o.id IS NOT NULL),'[]'::jsonb) attachments FROM communication_events e LEFT JOIN communication_attachments a ON a.event_id=e.id LEFT JOIN object_records o ON o.id=a.object_id WHERE e.id=$1 GROUP BY e.id`,[id]);return rowEvent(result.rows[0] as Record<string,unknown>)
}

export function installCommunications(app:Express,pool:Pool,objects:ObjectStorage){
 app.get('/api/communications/timeline',async(req:SecurityRequest,res:Response)=>{const actor=identity(req);const entityType=text(req.query.entityType),entityId=text(req.query.entityId);if(!entityType||!entityId)return res.status(400).json({error:'entityType and entityId are required.'});const result=await pool.query(`SELECT e.*,COALESCE(jsonb_agg(jsonb_build_object('id',o.id,'fileName',o.file_name,'mimeType',o.mime_type,'size',o.size_bytes,'objectKey',o.object_key)) FILTER(WHERE o.id IS NOT NULL),'[]'::jsonb) attachments FROM communication_events e LEFT JOIN communication_attachments a ON a.event_id=e.id LEFT JOIN object_records o ON o.id=a.object_id WHERE e.tenant_id=$1 AND e.entity_type=$2 AND e.entity_id=$3 GROUP BY e.id ORDER BY e.occurred_at ASC,e.id ASC`,[actor.tenantId,entityType,entityId]);return res.json(result.rows.map(row=>rowEvent(row as Record<string,unknown>)))});
 app.post('/api/communications/events',async(req:SecurityRequest,res:Response)=>{const input=req.body as EventInput;if(!input?.entityType||!input.entityId||!input.eventType||!text(input.content))return res.status(400).json({error:'entityType, entityId, eventType, and content are required.'});const client=await pool.connect();try{await client.query('BEGIN');const event=await insertEvent(client,pool,objects,req,input);await client.query('COMMIT');return res.status(201).json(event)}catch(error){await client.query('ROLLBACK');return res.status(400).json({error:error instanceof Error?error.message:'Unable to create communication event.'})}finally{client.release()}});
 app.get('/api/communications/threads',async(req:SecurityRequest,res:Response)=>{const actor=identity(req),entityType=text(req.query.entityType),entityId=text(req.query.entityId);const result=await pool.query('SELECT * FROM communication_threads WHERE tenant_id=$1 AND entity_type=$2 AND entity_id=$3 ORDER BY updated_at DESC',[actor.tenantId,entityType,entityId]);return res.json(result.rows)});
 app.post('/api/communications/threads',async(req:SecurityRequest,res:Response)=>{const actor=identity(req),entityType=text(req.body?.entityType),entityId=text(req.body?.entityId),subject=text(req.body?.subject);if(!entityType||!entityId||!subject)return res.status(400).json({error:'entityType, entityId, and subject are required.'});const result=await pool.query(`INSERT INTO communication_threads(tenant_id,entity_type,entity_id,subject,created_by,created_by_role) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[actor.tenantId,entityType,entityId,subject,actor.userId,actor.role]);return res.status(201).json(result.rows[0])});
 app.get('/api/communications/threads/:id',async(req:SecurityRequest,res:Response)=>{const actor=identity(req);const result=await pool.query(`SELECT e.*,COALESCE(jsonb_agg(jsonb_build_object('id',o.id,'fileName',o.file_name,'mimeType',o.mime_type,'size',o.size_bytes,'objectKey',o.object_key)) FILTER(WHERE o.id IS NOT NULL),'[]'::jsonb) attachments FROM communication_events e LEFT JOIN communication_attachments a ON a.event_id=e.id LEFT JOIN object_records o ON o.id=a.object_id WHERE e.tenant_id=$1 AND e.thread_id=$2 GROUP BY e.id ORDER BY e.occurred_at ASC,e.id ASC`,[actor.tenantId,req.params.id]);return res.json(result.rows.map(row=>rowEvent(row as Record<string,unknown>)))});
 app.get('/api/communications/search',async(req:SecurityRequest,res:Response)=>{const actor=identity(req),query=req.query as SearchQuery;const values:unknown[]=[actor.tenantId],where=['e.tenant_id=$1'];const add=(sql:string,value:unknown)=>{values.push(value);where.push(sql.replace('?',`$${values.length}`))};if(query.entityType)add('e.entity_type=?',query.entityType);if(query.entityId)add('e.entity_id=?',query.entityId);if(query.actorId)add('e.actor_id=?',query.actorId);if(query.eventType)add('e.event_type=?',query.eventType);if(query.from)add('e.occurred_at>=?',query.from);if(query.to)add('e.occurred_at<=?',query.to);if(query.q)add(`to_tsvector('english',e.content) @@ plainto_tsquery('english',?)`,query.q);const result=await pool.query(`SELECT e.* FROM communication_events e WHERE ${where.join(' AND ')} ORDER BY e.occurred_at DESC,e.id DESC LIMIT 200`,values);return res.json(result.rows.map(row=>rowEvent(row as Record<string,unknown>)))});
 app.get('/api/notifications',async(req:SecurityRequest,res:Response)=>{const actor=identity(req);const result=await pool.query(`SELECT n.*,e.entity_type,e.entity_id,e.event_type,e.content,e.occurred_at FROM communication_notifications n JOIN communication_events e ON e.id=n.event_id WHERE n.tenant_id=$1 AND n.recipient_user_id=$2 ORDER BY n.read_at NULLS FIRST,n.created_at DESC`,[actor.tenantId,actor.userId]);return res.json(result.rows)});
 app.post('/api/notifications/:id/read',async(req:SecurityRequest,res:Response)=>{const actor=identity(req);const result=await pool.query(`UPDATE communication_notifications SET read_at=COALESCE(read_at,now()) WHERE id=$1 AND tenant_id=$2 AND recipient_user_id=$3 RETURNING *`,[req.params.id,actor.tenantId,actor.userId]);return result.rowCount?res.json(result.rows[0]):res.status(404).json({error:'Notification not found.'})});
}
