import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { CommercialAccessError, CommercialEntitlementService, LEGACY_NORTHSTAR_TENANT_ID, reconcileLegacyDesignStudioInitialOwnerBootstrap, reconcileLegacyNorthstarCoreBootstrap } from './infrastructure/commercial-entitlements.js';
import { createPostgresPool, PostgresRegistry } from './infrastructure/postgres.js';
import { DefaultPostgresRepositoryFactory } from './infrastructure/postgres-repositories.js';

const databaseUrl=process.env.DATABASE_URL;
if(!databaseUrl)throw new Error('DATABASE_URL is required.');
const pool=createPostgresPool(databaseUrl),registry=new PostgresRegistry(pool,new DefaultPostgresRepositoryFactory());
const service=new CommercialEntitlementService(registry);
const tenantA=randomUUID(),tenantB=randomUUID();
const platform={actorId:'platform-admin',actorName:'CADence Platform Admin',platformRole:'platform-admin' as const};
const member=(tenantId:string,userId:string,platformRole:'none'|'platform-admin'='none')=>registry.memberships.save({tenantId,userId,laboratoryRole:platformRole==='none'?'laboratory-administrator':'system-administrator',platformRole,status:'ACTIVE',locationIds:[],practiceIds:[],administrativeOverride:true});
const identity=(tenantId:string,userId:string)=>({userId,name:userId,email:`${userId}@example.test`,role:'laboratory-administrator' as const,tenantId,locationIds:[],practiceIds:[],administrativeOverride:true,sessionId:'test-session',csrfToken:'test-csrf',platformRole:'none' as const});
const denied=async(work:()=>Promise<unknown>,message:RegExp)=>await assert.rejects(work,(error:unknown)=>error instanceof CommercialAccessError&&error.statusCode===403&&message.test(error.message));

try {
  await registry.tenants.create({id:tenantA,name:'Laboratory A',status:'ACTIVE',activationState:'ACTIVATED',commercialAccountReference:'acct-commercial-entitlements-a',auditMetadata:{test:'commercial-entitlements'}});
  await registry.tenants.create({id:tenantB,name:'Laboratory B',status:'ACTIVE',activationState:'ACTIVATED',commercialAccountReference:'acct-commercial-entitlements-b',auditMetadata:{test:'commercial-entitlements'}});
  const duplicateTenant=randomUUID();
  await assert.rejects(()=>registry.tenants.create({id:duplicateTenant,name:'Duplicate Commercial Account',status:'ACTIVE',activationState:'ACTIVATED',commercialAccountReference:'acct-commercial-entitlements-a',auditMetadata:{test:'commercial-account-uniqueness'}}),(error:unknown)=>error instanceof Error&&/tenants_commercial_account_reference_idx/.test(error.message),'database must reject duplicate commercial-account references');
  await registry.tenants.updateLifecycle({id:tenantA,status:'ACTIVE',activationState:'ACTIVATED',commercialAccountReference:'acct-commercial-entitlements-a',auditMetadata:{test:'commercial-entitlements'}});
  assert.equal((await registry.tenants.get(tenantA))?.commercialAccountReference,'acct-commercial-entitlements-a','a tenant may retain its own unique commercial-account reference');
  for(const userId of['a-owner','a-1','a-2','a-3','a-4'])await member(tenantA,userId);
  await member(tenantA,'platform-admin','platform-admin');await member(tenantB,'b-owner');

  await service.grantOrDisable(platform,{tenantId:tenantA,moduleKey:'NORTHSTAR_CORE',state:'ACTIVE'});
  await service.grantOrDisable(platform,{tenantId:tenantA,moduleKey:'DESIGN_STUDIO',state:'ACTIVE'});
  await service.grantOrDisable(platform,{tenantId:tenantA,moduleKey:'GVM',state:'DISABLED'});
  await service.grantOrDisable(platform,{tenantId:tenantB,moduleKey:'NORTHSTAR_CORE',state:'ACTIVE'});
  await service.setSeatPool(platform,tenantA,'NORTHSTAR_CORE',20);
  await service.setSeatPool(platform,tenantA,'DESIGN_STUDIO',3);
  await service.setSeatPool(platform,tenantA,'GVM',1);
  await service.setSeatPool(platform,tenantB,'NORTHSTAR_CORE',1);

  for(const userId of['a-owner','a-1','a-2','a-3','a-4'])await service.assignSeat(platform,tenantA,'NORTHSTAR_CORE',userId);
  for(const userId of['a-owner','a-1','a-2'])await service.assignSeat(platform,tenantA,'DESIGN_STUDIO',userId);
  const northstar=await registry.commercial.getSeatPool(tenantA,'NORTHSTAR_CORE');const designStudio=await registry.commercial.getSeatPool(tenantA,'DESIGN_STUDIO');
  assert.deepEqual({purchased:northstar?.purchasedSeatCount,assigned:northstar?.assignedSeatCount,available:northstar?.availableSeatCount},{purchased:20,assigned:5,available:15});
  assert.deepEqual({purchased:designStudio?.purchasedSeatCount,assigned:designStudio?.assignedSeatCount,available:designStudio?.availableSeatCount},{purchased:3,assigned:3,available:0});
  await assert.rejects(()=>service.assignSeat(platform,tenantA,'DESIGN_STUDIO','a-3'),(error:unknown)=>error instanceof CommercialAccessError&&error.statusCode===409);
  await assert.rejects(()=>service.assignSeat(platform,tenantA,'DESIGN_STUDIO','b-owner'),(error:unknown)=>error instanceof CommercialAccessError&&error.statusCode===403);
  await assert.rejects(()=>service.assignSeat(platform,tenantA,'NORTHSTAR_CORE','platform-admin'),(error:unknown)=>error instanceof CommercialAccessError&&error.statusCode===403);

  assert.equal((await service.checkAccess(identity(tenantA,'a-owner'),'NORTHSTAR_CORE')).module,'NORTHSTAR_CORE');
  assert.equal((await service.checkAccess(identity(tenantA,'a-owner'),'DESIGN_STUDIO')).module,'DESIGN_STUDIO');
  await service.grantOrDisable(platform,{tenantId:tenantA,moduleKey:'DESIGN_STUDIO',state:'DISABLED'});
  await denied(()=>service.checkAccess(identity(tenantA,'a-owner'),'DESIGN_STUDIO'),/not active/);
  assert.equal((await registry.commercial.activeAssignment(tenantA,'DESIGN_STUDIO','a-owner'))?.userId,'a-owner','disabling preserves seat history and assignment');
  await service.grantOrDisable(platform,{tenantId:tenantA,moduleKey:'DESIGN_STUDIO',state:'ACTIVE'});
  assert.equal((await service.checkAccess(identity(tenantA,'a-owner'),'DESIGN_STUDIO')).module,'DESIGN_STUDIO','re-enabling restores authorized access');
  await service.releaseSeat(platform,tenantA,'DESIGN_STUDIO','a-2');
  await service.assignSeat(platform,tenantA,'DESIGN_STUDIO','a-3');
  assert.equal((await service.checkAccess(identity(tenantA,'a-3'),'DESIGN_STUDIO')).module,'DESIGN_STUDIO','released Design Studio seat is reassigned without changing NorthStar capacity');
  await service.grantOrDisable(platform,{tenantId:tenantA,moduleKey:'GVM',state:'ACTIVE'});
  await service.assignSeat(platform,tenantA,'GVM','a-owner');
  assert.equal((await service.checkAccess(identity(tenantA,'a-owner'),'GVM')).module,'GVM','GVM is an entitlement domain without an operational module route');
  await service.grantOrDisable(platform,{tenantId:tenantA,moduleKey:'NORTHSTAR_CORE',state:'DISABLED'});
  await denied(()=>service.checkAccess(identity(tenantA,'a-owner'),'NORTHSTAR_CORE'),/not active/);
  await denied(()=>service.checkAccess({...identity(tenantA,'platform-admin'),platformRole:'platform-admin'},'DESIGN_STUDIO'),/Platform administrators/);
  const legacyUser=`legacy-bootstrap-${randomUUID()}`;
  const legacyEntitlement=await pool.query<{state:string;source:string}>('SELECT state,source FROM tenant_module_entitlements WHERE tenant_id=$1 AND module_key=\'NORTHSTAR_CORE\'',[LEGACY_NORTHSTAR_TENANT_ID]);
  const legacyPool=await pool.query<{purchased_seat_count:number;source:string}>('SELECT purchased_seat_count,source FROM tenant_module_seat_pools WHERE tenant_id=$1 AND module_key=\'NORTHSTAR_CORE\'',[LEGACY_NORTHSTAR_TENANT_ID]);
  await registry.memberships.save({tenantId:LEGACY_NORTHSTAR_TENANT_ID,userId:legacyUser,laboratoryRole:'laboratory-administrator',platformRole:'none',status:'ACTIVE',locationIds:[],practiceIds:[],administrativeOverride:true});
  await pool.query('DELETE FROM tenant_migration_ledger WHERE migration_key=$1',['0009_legacy_northstar_core_post_identity_bootstrap']);
  assert.equal(await reconcileLegacyNorthstarCoreBootstrap(pool,LEGACY_NORTHSTAR_TENANT_ID),true,'designated legacy tenant receives one post-identity snapshot');
  assert.equal((await registry.commercial.activeAssignment(LEGACY_NORTHSTAR_TENANT_ID,'NORTHSTAR_CORE',legacyUser))?.userId,legacyUser,'existing legacy membership receives a finite core seat');
  assert.equal(await reconcileLegacyNorthstarCoreBootstrap(pool,LEGACY_NORTHSTAR_TENANT_ID),false,'bootstrap ledger prevents duplicate runtime assignment');
  await pool.query(`UPDATE tenant_module_entitlements SET state='DISABLED',source='commercial-control-plane' WHERE tenant_id=$1 AND module_key='NORTHSTAR_CORE'`,[LEGACY_NORTHSTAR_TENANT_ID]);
  assert.equal(await reconcileLegacyNorthstarCoreBootstrap(pool,LEGACY_NORTHSTAR_TENANT_ID),false,'ordinary startup cannot reapply the one-time migration');
  assert.equal((await registry.commercial.getEntitlement(LEGACY_NORTHSTAR_TENANT_ID,'NORTHSTAR_CORE'))?.state,'DISABLED','explicit commercial disable is preserved');
  await pool.query('DELETE FROM tenant_module_seat_assignments WHERE tenant_id=$1 AND user_id=$2',[LEGACY_NORTHSTAR_TENANT_ID,legacyUser]);
  await pool.query('DELETE FROM identity_memberships WHERE tenant_id=$1 AND user_id=$2',[LEGACY_NORTHSTAR_TENANT_ID,legacyUser]);
  await pool.query('DELETE FROM tenant_migration_ledger WHERE migration_key=$1',['0009_legacy_northstar_core_post_identity_bootstrap']);
  if(legacyEntitlement.rows[0])await pool.query('UPDATE tenant_module_entitlements SET state=$3,source=$4 WHERE tenant_id=$1 AND module_key=$2',[LEGACY_NORTHSTAR_TENANT_ID,'NORTHSTAR_CORE',legacyEntitlement.rows[0].state,legacyEntitlement.rows[0].source]);
  if(legacyPool.rows[0])await pool.query('UPDATE tenant_module_seat_pools SET purchased_seat_count=$3,source=$4 WHERE tenant_id=$1 AND module_key=$2',[LEGACY_NORTHSTAR_TENANT_ID,'NORTHSTAR_CORE',legacyPool.rows[0].purchased_seat_count,legacyPool.rows[0].source]);
  const previewOwner=`preview-design-owner-${randomUUID()}`;
  const designEntitlement=await pool.query<{state:string;source:string}>('SELECT state,source FROM tenant_module_entitlements WHERE tenant_id=$1 AND module_key=\'DESIGN_STUDIO\'',[LEGACY_NORTHSTAR_TENANT_ID]);
  const designPool=await pool.query<{purchased_seat_count:number;source:string}>('SELECT purchased_seat_count,source FROM tenant_module_seat_pools WHERE tenant_id=$1 AND module_key=\'DESIGN_STUDIO\'',[LEGACY_NORTHSTAR_TENANT_ID]);
  await registry.memberships.save({tenantId:LEGACY_NORTHSTAR_TENANT_ID,userId:previewOwner,laboratoryRole:'laboratory-administrator',platformRole:'none',status:'ACTIVE',locationIds:[],practiceIds:[],administrativeOverride:true});
  await pool.query('DELETE FROM tenant_migration_ledger WHERE migration_key=$1',['preview_legacy_design_studio_initial_owner_bootstrap_v1']);
  await pool.query(`UPDATE tenant_module_entitlements SET state='ACTIVE',source='legacy-migration' WHERE tenant_id=$1 AND module_key='DESIGN_STUDIO'`,[LEGACY_NORTHSTAR_TENANT_ID]);
  await pool.query(`UPDATE tenant_module_seat_pools SET purchased_seat_count=0,source='legacy-migration' WHERE tenant_id=$1 AND module_key='DESIGN_STUDIO'`,[LEGACY_NORTHSTAR_TENANT_ID]);
  assert.equal(await reconcileLegacyDesignStudioInitialOwnerBootstrap(pool,LEGACY_NORTHSTAR_TENANT_ID,previewOwner),true,'the initial legacy owner receives one preview Design Studio seat after identity bootstrap');
  assert.equal((await registry.commercial.getEntitlement(LEGACY_NORTHSTAR_TENANT_ID,'DESIGN_STUDIO'))?.state,'ACTIVE','preview bootstrap preserves the active legacy Design Studio entitlement');
  assert.deepEqual(await registry.commercial.getSeatPool(LEGACY_NORTHSTAR_TENANT_ID,'DESIGN_STUDIO'),{tenantId:LEGACY_NORTHSTAR_TENANT_ID,moduleKey:'DESIGN_STUDIO',purchasedSeatCount:1,assignedSeatCount:1,availableSeatCount:0},'preview bootstrap materializes one finite Design Studio seat');
  assert.equal((await service.checkAccess(identity(LEGACY_NORTHSTAR_TENANT_ID,previewOwner),'DESIGN_STUDIO')).module,'DESIGN_STUDIO','the entitled initial owner is authorized through the normal module gate');
  assert.equal(await reconcileLegacyDesignStudioInitialOwnerBootstrap(pool,LEGACY_NORTHSTAR_TENANT_ID,previewOwner),false,'the initial owner bootstrap is idempotent');
  await pool.query('DELETE FROM tenant_module_seat_assignments WHERE tenant_id=$1 AND module_key=\'DESIGN_STUDIO\' AND user_id=$2',[LEGACY_NORTHSTAR_TENANT_ID,previewOwner]);
  await pool.query('DELETE FROM tenant_migration_ledger WHERE migration_key=$1',['preview_legacy_design_studio_initial_owner_bootstrap_v1']);
  await pool.query(`UPDATE tenant_module_entitlements SET state='DISABLED',source='commercial-control-plane' WHERE tenant_id=$1 AND module_key='DESIGN_STUDIO'`,[LEGACY_NORTHSTAR_TENANT_ID]);
  assert.equal(await reconcileLegacyDesignStudioInitialOwnerBootstrap(pool,LEGACY_NORTHSTAR_TENANT_ID,previewOwner),false,'an explicit commercial entitlement decision is never changed by preview bootstrap');
  assert.equal((await registry.commercial.activeAssignment(LEGACY_NORTHSTAR_TENANT_ID,'DESIGN_STUDIO',previewOwner)),null,'commercially controlled tenants receive no bootstrap Design Studio assignment');
  await pool.query('DELETE FROM identity_memberships WHERE tenant_id=$1 AND user_id=$2',[LEGACY_NORTHSTAR_TENANT_ID,previewOwner]);
  if(designEntitlement.rows[0])await pool.query('UPDATE tenant_module_entitlements SET state=$3,source=$4 WHERE tenant_id=$1 AND module_key=$2',[LEGACY_NORTHSTAR_TENANT_ID,'DESIGN_STUDIO',designEntitlement.rows[0].state,designEntitlement.rows[0].source]);
  if(designPool.rows[0])await pool.query('UPDATE tenant_module_seat_pools SET purchased_seat_count=$3,source=$4 WHERE tenant_id=$1 AND module_key=$2',[LEGACY_NORTHSTAR_TENANT_ID,'DESIGN_STUDIO',designPool.rows[0].purchased_seat_count,designPool.rows[0].source]);
  const futureTenant=randomUUID();await registry.tenants.create({id:futureTenant,name:'No Automatic Core',status:'ACTIVE',activationState:'ACTIVATED',commercialAccountReference:'acct-commercial-entitlements-no-legacy',auditMetadata:{test:'no-legacy-bootstrap'}});
  assert.equal(await reconcileLegacyNorthstarCoreBootstrap(pool,futureTenant),false,'future tenants cannot inherit legacy bootstrap');
  assert.equal(await registry.commercial.getEntitlement(futureTenant,'NORTHSTAR_CORE'),null,'future tenant remains without automatic core entitlement');
  const events=await registry.audit.list(tenantA,'commercial-seat-assignment');
  assert(events.some(event=>event.action==='commercial.seat.assigned'&&event.metadata.newState),'seat assignment audit records a new state');
  assert(events.some(event=>event.action==='commercial.seat.released'&&event.metadata.previousState),'seat release audit records a previous state');
  console.log('CF-1A2 commercial entitlement, seat, isolation, disable/re-enable, and audit tests passed.');
} finally { await pool.end(); }
