import { randomUUID } from 'node:crypto';
import type { Express, Response } from 'express';
import type { Pool, PoolClient } from 'pg';
import type { ObjectStorage, StoredObjectKind } from './infrastructure/object-storage.js';
import type { SecurityRequest } from './security.js';
import { EntityAccessService, type CommunicationEntityType as EntityType } from './entity-access.js';

type EventType='phone-call'|'email'|'internal-note'|'doctor-message'|'laboratory-message'|'production-update'|'qc-comment'|'shipping-event'|'billing-event'|'attachment'|'system-event';
type Priority='low'|'normal'|'high'|'urgent';
type EventInput={entityType:EntityType;entityId:string;threadId?:string;eventType:EventType;content:string;versionOf?:string;attachmentObjectIds?:string[];attachments?:Array<{fileName:string;mimeType:string;kind:StoredObjectKind;contentBase64:string}>;notify?:Array<{userId:string;priority?:Priority;category?:string}>};
type SearchQuery={entityType?:string;entityId?:string;actorId?:string;eventType?:string;from?:string;to?:string;q?:string};
const entityTypes=new Set<EntityType>(['practice','doctor','patient','case','shipment','invoice']);
const eventTypes=new Set<EventType>(['phone-call','email','internal-note','doctor-message','laboratory-message','production-update','qc-comment','shipping-event','billing-event','attachment','system-event']);
const text=(value:unknown)=>typeof value==='string'?value.trim():'';
const identity=(req:SecurityRequest)=>{if(!req.identity)throw new Error('Authenticated identity required.');return req.identity};
const validEntity=(value:string):value is EntityType=>entityTypes.has(value as EntityType);
const validEvent=(value:string):value is EventType=>eventTypes.has(value as EventType);
const safeAttachment=(row:Record<string,unknown>)=>({id:row.id,fileName:row.fileName,mimeType:row.mimeType,size:row.size,kind:row.kind});
const rowEvent=(row:Record<string,unknown>)=>({id:row.id,tenantId:row.tenant_id,threadId:row.thread_id,entityType:row.entity_type,entityId:row.entity_id,eventType:row.event_type,content:row.content,actorId:row.actor_id,actorName:row.actor_name,actorRole:row.actor_role,versionOf:row.version_of,occurredAt:row.occurred_at,attachments:Array.isArray(row.attachments)?row.attachments.map(item=>safeAttachment(item as Record<string,unknown>)):[]});
const statusOf=(error:unknown)=>typeof error==='object'&&error!==null&&'statusCode'in error?Number((error as{statusCode:unknown}).statusCode):400;
async function audit(client:PoolClient,req:SecurityRequest,action:string,entityType:string,entityId:string,metadata:Record<string,unknown>={}){const actor=identity(req);await client.query(`INSERT INTO audit_events(tenant_id,actor_id,actor_name,action,entity_type,entity_id,occurred_at,metadata) VALUES($1,$2,$3,$4,$5,$6,now(),$7::jsonb)`,[actor.tenantId,actor.userId,actor.name,action,entityType,entityId,JSON.stringify({role:actor.role,...metadata})])}
async function threadFor(client:PoolClient,tenantId:string,threadId:string,entityType:EntityType,entityId:string){const result=await client.query(`SELECT id FROM communication_threads WHERE tenant_id=$1 AND id=$2 AND entity_type=$3 AND entity_id=$4`,[tenantId,threadId,entityType,entityId]);if(!result.rowCount){const error=new Error('Thread does not belong to this entity.');Object.assign(error,{statusCode:409});throw error}}
async function insertEvent(client:PoolClient,pool:Pool,objects:ObjectStorage,access:EntityAccessService,req:SecurityRequest,input:EventInput){const actor=identity(req);await access.require(actor,input.entityType,input.entityId,'write');if(input.threadId)await threadFor(client,actor.tenantId,input.threadId,input.entityType,input.entityId);const id=randomUUID();await client.query(`INSERT INTO communication_events(id,tenant_id,thread_id,entity_type,entity_id,event_type,content,actor_id,actor_name,actor_role,version_of) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[id,actor.tenantId,input.threadId??null,input.entityType,input.entityId,input.eventType,text(input.content),actor.userId,actor.name,actor.role,input.versionOf??null]);const objectIds=[...(input.attachmentObjectIds??[])];for(const objectId of objectIds)await access.requireObject(actor,objectId,'read');for(const attachment of input.attachments??[]){const stored=await objects.put({tenantId:actor.tenantId,ownerType:'communication-event',ownerId:id,kind:attachment.kind,fileName:attachment.fileName,mimeType:attachment.mimeType,bytes:Buffer.from(attachment.contentBase64,'base64'),metadata:{entityType:input.entityType,entityId:input.entityId}});objectIds.push(stored.id)}for(const objectId of objectIds)await client.query('INSERT INTO communication_attachments(tenant_id,event_id,object_id) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[actor.tenantId,id,objectId]);for(const notice of input.notify??[]){await access.recipient(actor,notice.userId,input.entityType,input.entityId);await client.query(`INSERT INTO communication_notifications(tenant_id,event_id,recipient_user_id,priority,category) VALUES($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING`,[actor.tenantId,id,notice.userId,notice.priority??'normal',notice.category??input.eventType])}await audit(client,req,'communications.event.created',input.entityType,input.entityId,{eventId:id,eventType:input.eventType,threadId:input.threadId??null,attachmentCount:objectIds.length,notificationCount:input.notify?.length??0});const result=await client.query(`SELECT e.*,COALESCE(jsonb_agg(jsonb_build_object('id',o.id,'fileName',o.file_name,'mimeType',o.mime_type,'size',o.size_bytes,'kind',o.kind)) FILTER(WHERE o.id IS NOT NULL),'[]'::jsonb) attachments FROM communication_events e LEFT JOIN communication_attachments a ON a.event_id=e.id LEFT JOIN object_records o ON o.id=a.object_id WHERE e.id=$1 GROUP BY e.id`,[id]);return rowEvent(result.rows[0] as Record<string,unknown>)}

export function installCommunications(app:Express,pool:Pool,objects:ObjectStorage){const access=new EntityAccessService(pool);
 app.get('/api/communications/timeline',async(req:SecurityRequest,res:Response)=>{const actor=identity(req),entityType=text(req.query.entityType),entityId=text(req.query.entityId);if(!validEntity(entityType)||!entityId)return res.status(400).json({error:'Valid entityType and entityId are required.'});try{await access.require(actor,entityType,entityId,'read');const result=await pool.query(`SELECT e.*,COALESCE(jsonb_agg(jsonb_build_object('id',o.id,'fileName',o.file_name,'mimeType',o.mime_type,'size',o.size_bytes,'kind',o.kind)) FILTER(WHERE o.id IS NOT NULL),'[]'::jsonb) attachments FROM communication_events e LEFT JOIN communication_attachments a ON a.event_id=e.id LEFT JOIN object_records o ON o.id=a.object_id WHERE e.tenant_id=$1 AND e.entity_type=$2 AND e.entity_id=$3 GROUP BY e.id ORDER BY e.occurred_at ASC,e.id ASC`,[actor.tenantId,entityType,entityId]);return res.json(result.rows.map(row=>rowEvent(row as Record<string,unknown>)))}catch(error){return res.status(statusOf(error)).json({error:error instanceof Error?error.message:'Access denied.'})}});
 app.post('/api/communications/events',async(req:SecurityRequest,res:Response)=>{const input=req.body as EventInput;if(!validEntity(input?.entityType)||!input.entityId||!validEvent(input.eventType)||!text(input.content))return res.status(400).json({error:'Valid entityType, entityId, eventType, and content are required.'});const client=await pool.connect();try{await client.query('BEGIN');const event=await insertEvent(client,pool,objects,access,req,input);await client.query('COMMIT');return res.status(201).json(event)}catch(error){await client.query('ROLLBACK');return res.status(statusOf(error)).json({error:error instanceof Error?error.message:'Unable to create communication event.'})}finally{client.release()}});
 app.get('/api/communications/threads',async(req:SecurityRequest,res:Response)=>{const actor=identity(req),entityType=text(req.query.entityType),entityId=text(req.query.entityId);if(!validEntity(entityType)||!entityId)return res.status(400).json({error:'Valid entityType and entityId are required.'});try{await access.require(actor,entityType,entityId,'read');const result=await pool.query('SELECT * FROM communication_threads WHERE tenant_id=$1 AND entity_type=$2 AND entity_id=$3 ORDER BY updated_at DESC',[actor.tenantId,entityType,entityId]);return res.json(result.rows)}catch(error){return res.status(statusOf(error)).json({error:error instanceof Error?error.message:'Access denied.'})}});
 app.post('/api/communications/threads',async(req:SecurityRequest,res:Response)=>{const actor=identity(req),entityType=text(req.body?.entityType),entityId=text(req.body?.entityId),subject=text(req.body?.subject);if(!validEntity(entityType)||!entityId||!subject)return res.status(400).json({error:'Valid entityType, entityId, and subject are required.'});const client=await pool.connect();try{await access.require(actor,entityType,entityId,'write');await client.query('BEGIN');const result=await client.query(`INSERT INTO communication_threads(tenant_id,entity_type,entity_id,subject,created_by,created_by_role) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[actor.tenantId,entityType,entityId,subject,actor.userId,actor.role]);await audit(client,req,'communications.thread.created',entityType,entityId,{threadId:result.rows[0]?.id});await client.query('COMMIT');return res.status(201).json(result.rows[0])}catch(error){await client.query('ROLLBACK');return res.status(statusOf(error)).json({error:error instanceof Error?error.message:'Unable to create thread.'})}finally{client.release()}});
 app.get('/api/communications/threads/:id',async(req:SecurityRequest,res:Response)=>{const actor=identity(req);const thread=await pool.query<{entity_type:EntityType;entity_id:string}>(`SELECT entity_type,entity_id FROM communication_threads WHERE tenant_id=$1 AND id=$2`,[actor.tenantId,req.params.id]);const scope=thread.rows[0];if(!scope)return res.status(404).json({error:'Thread not found.'});try{await access.require(actor,scope.entity_type,scope.entity_id,'read');const result=await pool.query(`SELECT e.*,COALESCE(jsonb_agg(jsonb_build_object('id',o.id,'fileName',o.file_name,'mimeType',o.mime_type,'size',o.size_bytes,'kind',o.kind)) FILTER(WHERE o.id IS NOT NULL),'[]'::jsonb) attachments FROM communication_events e LEFT JOIN communication_attachments a ON a.event_id=e.id LEFT JOIN object_records o ON o.id=a.object_id WHERE e.tenant_id=$1 AND e.thread_id=$2 GROUP BY e.id ORDER BY e.occurred_at ASC,e.id ASC`,[actor.tenantId,req.params.id]);return res.json(result.rows.map(row=>rowEvent(row as Record<string,unknown>)))}catch(error){return res.status(statusOf(error)).json({error:error instanceof Error?error.message:'Access denied.'})}});
 app.get('/api/communications/search',async(req:SecurityRequest,res:Response)=>{const actor=identity(req),query=req.query as SearchQuery,values:unknown[]=[actor.tenantId],where=['e.tenant_id=$1'];const add=(sql:string,value:unknown)=>{values.push(value);where.push(sql.replace('?',`$${values.length}`))};if(query.entityType)add('e.entity_type=?',query.entityType);if(query.entityId)add('e.entity_id=?',query.entityId);if(query.actorId)add('e.actor_id=?',query.actorId);if(query.eventType)add('e.event_type=?',query.eventType);if(query.from)add('e.occurred_at>=?',query.from);if(query.to)add('e.occurred_at<=?',query.to);if(query.q)add(`to_tsvector('english',e.content) @@ plainto_tsquery('english',?)`,query.q);const result=await pool.query(`SELECT e.* FROM communication_events e WHERE ${where.join(' AND ')} ORDER BY e.occurred_at DESC,e.id DESC LIMIT 200`,values);const filtered=[];for(const row of result.rows){if(validEntity(row.entity_type)&&await access.canAccess(actor,row.entity_type,row.entity_id,'read'))filtered.push(rowEvent(row as Record<string,unknown>))}return res.json(filtered)});
 app.get('/api/notifications',async(req:SecurityRequest,res:Response)=>{const actor=identity(req);const result=await pool.query(`SELECT n.*,e.entity_type,e.entity_id,e.event_type,e.content,e.occurred_at FROM communication_notifications n JOIN communication_events e ON e.id=n.event_id WHERE n.tenant_id=$1 AND n.recipient_user_id=$2 ORDER BY n.read_at NULLS FIRST,n.created_at DESC`,[actor.tenantId,actor.userId]);const filtered=[];for(const row of result.rows){if(validEntity(row.entity_type)&&await access.canAccess(actor,row.entity_type,row.entity_id,'read'))filtered.push(row)}return res.json(filtered)});
 app.post('/api/notifications/:id/read',async(req:SecurityRequest,res:Response)=>{const actor=identity(req),client=await pool.connect();try{await client.query('BEGIN');const existing=await client.query<{entity_type:EntityType;entity_id:string}>(`SELECT e.entity_type,e.entity_id FROM communication_notifications n JOIN communication_events e ON e.id=n.event_id WHERE n.id=$1 AND n.tenant_id=$2 AND n.recipient_user_id=$3`,[req.params.id,actor.tenantId,actor.userId]);const scope=existing.rows[0];if(!scope){await client.query('ROLLBACK');return res.status(404).json({error:'Notification not found.'})}await access.require(actor,scope.entity_type,scope.entity_id,'read');const result=await client.query(`UPDATE communication_notifications SET read_at=COALESCE(read_at,now()) WHERE id=$1 AND tenant_id=$2 AND recipient_user_id=$3 RETURNING *`,[req.params.id,actor.tenantId,actor.userId]);await audit(client,req,'communications.notification.read',scope.entity_type,scope.entity_id,{notificationId:req.params.id});await client.query('COMMIT');return res.json(result.rows[0])}catch(error){await client.query('ROLLBACK');return res.status(statusOf(error)).json({error:error instanceof Error?error.message:'Unable to update notification.'})}finally{client.release()}});
}
