import assert from 'node:assert/strict';
import express from 'express';
import { Pool } from 'pg';
import { PostgresObjectStorage } from './infrastructure/postgres-object-storage.js';
import type { StoredObjectKind } from './infrastructure/object-storage.js';
import type { AuditEventInput, AuditRepository } from './infrastructure/contracts.js';
import type { NorthStarRole, SecurityRequest } from './security.js';
import { installDigitalIntake } from './digital-intake.js';
import { installIntakeAdministration } from './intake-administration.js';
import { installProductCatalogFoundation } from './product-catalog-foundation.js';

const databaseUrl=process.env.DATABASE_URL;
if(!databaseUrl)throw new Error('DATABASE_URL is required.');
const pool=new Pool({connectionString:databaseUrl});
const tenantId=process.env.NORTHSTAR_TENANT_ID??'00000000-0000-0000-0000-000000000001';
const otherTenant='00000000-0000-0000-0000-000000000002';
const audits:AuditEventInput[]=[];
const audit:AuditRepository={append:async event=>{audits.push(event)},list:async tenant=>audits.filter(item=>item.tenantId===tenant)};
let role:NorthStarRole='system-administrator';

await pool.query(`INSERT INTO tenants(id,name) VALUES($1,'NorthStar Test') ON CONFLICT(id) DO NOTHING`,[tenantId]);
await pool.query(`INSERT INTO tenants(id,name) VALUES($1,'Other Tenant') ON CONFLICT(id) DO NOTHING`,[otherTenant]);
await pool.query('TRUNCATE pricing_schedule_items,pricing_schedules,tenant_routing_defaults,practice_routing_profiles,intake_history,intake_billing_reviews,intake_product_resolutions,intake_routing_resolutions,intake_validations,intake_attachments,digital_prescriptions,intake_submissions,doctor_preference_profiles,product_catalog,scanner_providers RESTART IDENTITY CASCADE');

const app=express();app.use(express.json({limit:'25mb'}));app.use((req:SecurityRequest,_res,next)=>{req.identity={userId:'usr-admin',name:'Dorian Habet',email:'dorianhabet@yahoo.com',role,tenantId,locationIds:['location-primary'],practiceIds:[],administrativeOverride:true,sessionId:'test-session',csrfToken:'test'};next()});
installIntakeAdministration(app,{pool,audit});
installProductCatalogFoundation(app,pool,audit);
installDigitalIntake(app,{pool,objects:new PostgresObjectStorage(pool),audit,context:{tenantId,actorId:'usr-admin',actorName:'Dorian Habet'},createOperationalCase:async()=>({id:'case-intake-1',caseNumber:'KDL-INT-1'})});
const server=app.listen(0);await new Promise<void>(resolve=>server.once('listening',resolve));const address=server.address();if(!address||typeof address==='string')throw new Error('Unable to start test server.');const base=`http://127.0.0.1:${address.port}`;
async function request(path:string,method='GET',body?:unknown){const response=await fetch(base+path,{method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const payload=await response.json().catch(()=>null);return{response,payload}}

try{
 const tenantRoute=await request('/api/intake/admin/tenant-routing','PUT',{preferredRoute:'internal'});assert.equal(tenantRoute.response.status,200);
 const practiceRoute=await request('/api/intake/admin/practice-routing/practice-1','PUT',{preferredRoute:'outsourced',preferredOutsourcePartner:'Partner Lab'});assert.equal(practiceRoute.response.status,200);
 const doctorPreference=await request('/api/intake/admin/doctor-preferences','POST',{doctorId:'doctor-1',practiceId:'practice-1',preferredRoute:'hybrid',preferredOutsourcePartner:'Hybrid Partner',defaults:{material:'Zirconia',marginDesign:'Chamfer',contacts:'Normal',occlusion:'Light',productionPreferences:'Return with model.'}});assert.equal(doctorPreference.response.status,201);
 const schedule=await request('/api/intake/admin/pricing-schedules','POST',{scheduleType:'contract',name:'Future Contract Schedule',practiceId:'practice-1',priority:10});assert.equal(schedule.response.status,201);assert.equal('price' in schedule.payload,false);
 const rejectedCatalog=await request('/api/intake/catalog','POST',{sku:'PRICE-LEAK',productName:'Invalid',restorationCategory:'Fixed Restorations',restorationSubtype:'Crown',defaultCustomerPrice:99});assert.equal(rejectedCatalog.response.status,400);
 role='read-only-auditor';const denied=await request('/api/intake/admin/tenant-routing','PUT',{preferredRoute:'hybrid'});assert.equal(denied.response.status,403);role='system-administrator';

 const provider=await request('/api/intake/providers','POST',{providerKey:'manual-upload',displayName:'Manual Upload',providerType:'manual-upload',productionReady:true});assert.equal(provider.response.status,201);
 const submission=await request('/api/intake/submissions','POST',{intakeMethod:'manual-digital',providerKey:'manual-upload',sourceReference:'email-1001',practiceId:'practice-1',doctorId:'doctor-1',patientId:'patient-1'});assert.equal(submission.response.status,201);const submissionId=String(submission.payload.id);assert.equal(submission.payload.status,'prescription-required');
 const premature=await request(`/api/intake/submissions/${submissionId}/accept`,'POST',{});assert.equal(premature.response.status,409,'case cannot bypass mandatory prescription');
 const prescription={practiceId:'practice-1',doctorId:'doctor-1',patientId:'patient-1',patientName:'Test Patient',patientReference:'PAT-1001',shippingLocation:{city:'Northridge'},billingAccount:{accountNumber:'KDL-1001'},contactInformation:{phone:'747-240-4008'},restorations:[{category:'Fixed Restorations',type:'Crown',subtype:'Full Zirconia Crown',material:'Zirconia',toothNumbers:[30],quantity:1},{category:'Removable Prosthetics',type:'Complete Upper Denture',subtype:'Premium Denture',material:'Acrylic',arches:['maxillary'],quantity:1},{category:'Implant Restorations',type:'Screw-Retained Crown',subtype:'Screw-Retained Crown',material:'Zirconia',implantSystem:'Nobel Biocare',implantPositions:[8],quantity:1},{category:'Orthodontics',type:'Essix Retainer',subtype:'Essix Retainer',material:'Not applicable',toothNumbers:[1],quantity:1},{category:'Appliances',type:'Night Guard',subtype:'Hard Night Guard',material:'Acrylic',toothNumbers:[2],quantity:1}],clinicalInformation:{shade:'A2',stumpShade:'ND2'},productionNotes:'Verify occlusion.',specialInstructions:'Return with model.'};
 const saved=await request(`/api/intake/submissions/${submissionId}/prescription`,'PUT',prescription);assert.equal(saved.response.status,200);assert.equal(saved.payload.clinical_information.marginDesign,'Chamfer');assert.equal(saved.payload.clinical_information.contacts,'Normal');
 const files:Array<{name:string;kind:StoredObjectKind;mime:string}>=[{name:'upper.stl',kind:'stl',mime:'model/stl'},{name:'lower.obj',kind:'obj',mime:'model/obj'},{name:'bite.ply',kind:'ply',mime:'application/octet-stream'},{name:'scan.cbct',kind:'cbct',mime:'application/dicom'},{name:'series.dcm',kind:'dicom',mime:'application/dicom'},{name:'xray.png',kind:'xray',mime:'image/png'},{name:'clinical.jpg',kind:'clinical-photo',mime:'image/jpeg'},{name:'shade.png',kind:'shade-photo',mime:'image/png'},{name:'records.zip',kind:'intake-package',mime:'application/zip'}];
 for(const file of files){const attachment=await request(`/api/intake/submissions/${submissionId}/attachments`,'POST',{fileName:file.name,mimeType:file.mime,kind:file.kind,purpose:file.kind,contentBase64:Buffer.from(`content-${file.kind}`).toString('base64')});assert.equal(attachment.response.status,201)}
 const validation=await request(`/api/intake/submissions/${submissionId}/validate`,'POST',{});assert.equal(validation.response.status,200);assert.equal(validation.payload.status,'complete');
 const route=await request(`/api/intake/submissions/${submissionId}/route`,'POST',{});assert.equal(route.response.status,200);assert.equal(route.payload.route,'hybrid');assert.equal(route.payload.precedence_source,'doctor-profile');
 const products=await request(`/api/intake/submissions/${submissionId}/resolve-products`,'POST',{});assert.equal(products.response.status,200);assert.equal(products.payload.length,5);assert.ok(products.payload.every((item:Record<string,unknown>)=>!Object.keys(item).some(key=>key.toLowerCase().includes('price'))));assert.ok(products.payload.some((item:{sku:string;department:string;accounting_category:string;quantity:string})=>item.sku==='AUTO-FULL-ZIRCONIA-CROWN-ZIRCONIA'&&item.department==='fixed'&&item.accounting_category==='Fixed Restorations'&&Number(item.quantity)===1));
 const pdf=await request(`/api/intake/submissions/${submissionId}/prescription-pdf`,'POST',{copy:'production'});assert.equal(pdf.response.status,201);assert.equal(pdf.payload.mimeType,'application/pdf');assert.ok(Buffer.from(pdf.payload.contentBase64,'base64').toString('utf8').startsWith('%PDF-1.4'));
 const accepted=await request(`/api/intake/submissions/${submissionId}/accept`,'POST',{});assert.equal(accepted.response.status,200);assert.equal(accepted.payload.operationalCase.caseNumber,'KDL-INT-1');assert.equal(accepted.payload.billingReview,'pending');
 const review=await request(`/api/intake/submissions/${submissionId}/billing-review`,'POST',{status:'approved',notes:'Products verified.'});assert.equal(review.response.status,200);assert.equal(review.payload.status,'approved');
 const detail=await request(`/api/intake/submissions/${submissionId}`);assert.equal(detail.response.status,200);assert.equal(detail.payload.submission.status,'operational-case-created');assert.ok(detail.payload.history.length>=7);assert.equal(detail.payload.attachments.length,10);assert.ok(detail.payload.products.every((item:{frozen_at:string|null})=>item.frozen_at!==null));

 const practiceSubmission=await request('/api/intake/submissions','POST',{intakeMethod:'physical',sourceReference:'walk-in-practice',practiceId:'practice-1',doctorId:'doctor-2'});const practiceId=String(practiceSubmission.payload.id);await request(`/api/intake/submissions/${practiceId}/prescription`,'PUT',{...prescription,doctorId:'doctor-2',patientReference:'PAT-2002',restorations:[prescription.restorations[0]]});await request(`/api/intake/submissions/${practiceId}/validate`,'POST',{});const practiceResolution=await request(`/api/intake/submissions/${practiceId}/route`,'POST',{});assert.equal(practiceResolution.payload.precedence_source,'practice-profile');assert.equal(practiceResolution.payload.route,'outsourced');
 const tenantSubmission=await request('/api/intake/submissions','POST',{intakeMethod:'physical',sourceReference:'walk-in-tenant',practiceId:'practice-2',doctorId:'doctor-3'});const tenantSubmissionId=String(tenantSubmission.payload.id);await request(`/api/intake/submissions/${tenantSubmissionId}/prescription`,'PUT',{...prescription,practiceId:'practice-2',doctorId:'doctor-3',patientReference:'PAT-3003',restorations:[prescription.restorations[0]]});await request(`/api/intake/submissions/${tenantSubmissionId}/validate`,'POST',{});const tenantResolution=await request(`/api/intake/submissions/${tenantSubmissionId}/route`,'POST',{});assert.equal(tenantResolution.payload.precedence_source,'tenant-default');assert.equal(tenantResolution.payload.route,'internal');

 const objectRows=await pool.query('SELECT owner_type,owner_id,file_name,kind,provider FROM object_records WHERE tenant_id=$1 AND owner_id=$2 ORDER BY created_at',[tenantId,submissionId]);for(const file of files)assert.ok(objectRows.rows.some(row=>row.file_name===file.name&&row.kind===file.kind&&row.provider==='postgres'));assert.ok(objectRows.rows.some(row=>row.owner_type==='digital-prescription'&&row.kind==='prescription-pdf'&&row.provider==='postgres'));
 const notifications=await pool.query('SELECT category FROM communication_notifications WHERE tenant_id=$1',[tenantId]);assert.ok(notifications.rows.some(row=>row.category==='new-submission'));assert.ok(notifications.rows.some(row=>row.category==='billing-review'));
 const communications=await pool.query('SELECT content FROM communication_events WHERE tenant_id=$1 AND entity_id=$2 ORDER BY occurred_at',[tenantId,submissionId]);assert.ok(communications.rows.some(row=>String(row.content).includes('submission received')));assert.ok(communications.rows.some(row=>String(row.content).includes('product resolution completed')));
 await assert.rejects(pool.query(`UPDATE intake_history SET event_type='tampered' WHERE submission_id=$1`,[submissionId]));
 assert.ok(audits.some(item=>item.action==='intake.submission.created'));assert.ok(audits.some(item=>item.action==='intake.prescription.changed'));assert.ok(audits.some(item=>item.action==='intake.submission.accepted'));assert.ok(audits.some(item=>item.action==='intake.doctor-preference.saved'));assert.ok(audits.some(item=>item.action==='intake.practice-routing.saved'));assert.ok(audits.some(item=>item.action==='intake.tenant-routing.saved'));assert.ok(audits.some(item=>item.action==='pricing-schedule.created'));
 const otherCount=await pool.query('SELECT count(*)::int count FROM intake_submissions WHERE tenant_id=$1',[otherTenant]);assert.equal(otherCount.rows[0]?.count,0);const otherAdminCount=await pool.query('SELECT count(*)::int count FROM pricing_schedules WHERE tenant_id=$1',[otherTenant]);assert.equal(otherAdminCount.rows[0]?.count,0);
 const catalogColumns=await pool.query(`SELECT column_name FROM information_schema.columns WHERE table_name='product_catalog'`);assert.equal(catalogColumns.rows.some(row=>['default_customer_price','promotional_price','customer_price'].includes(row.column_name)),false);
 console.log('Digital intake production-readiness integration tests passed.');
}finally{server.close();await pool.end()}
