import { randomUUID } from 'node:crypto';
import type { Express, Response } from 'express';
import type { Pool } from 'pg';
import type { AuditRepository } from './infrastructure/contracts.js';
import type { SecurityRequest } from './security.js';

type Route='internal'|'outsourced'|'hybrid'|'manual-review';
type Dependencies={pool:Pool;audit:AuditRepository};
const text=(value:unknown)=>typeof value==='string'?value.trim():'';
const adminRoles=new Set(['system-administrator','laboratory-administrator']);
function identity(req:SecurityRequest){if(!req.identity)throw new Error('Authenticated identity required.');return req.identity}
function requireAdmin(req:SecurityRequest,res:Response){const actor=identity(req);if(!adminRoles.has(actor.role)){res.status(403).json({error:'Laboratory administration permission is required.'});return null}return actor}
async function audit(deps:Dependencies,req:SecurityRequest,action:string,entityType:string,entityId:string,metadata:Record<string,unknown>={}){const actor=identity(req);await deps.audit.append({tenantId:actor.tenantId,actorId:actor.userId,actorName:actor.name,action,entityType,entityId,occurredAt:new Date().toISOString(),metadata:{role:actor.role,...metadata}})}
function validRoute(value:string):value is Route{return['internal','outsourced','hybrid','manual-review'].includes(value)}

export function installIntakeAdministration(app:Express,deps:Dependencies){
 app.get('/api/intake/admin/doctor-preferences',async(req:SecurityRequest,res)=>{const actor=identity(req);const result=await deps.pool.query('SELECT * FROM doctor_preference_profiles WHERE tenant_id=$1 ORDER BY doctor_id,version DESC',[actor.tenantId]);return res.json(result.rows)});
 app.post('/api/intake/admin/doctor-preferences',async(req:SecurityRequest,res)=>{const actor=requireAdmin(req,res);if(!actor)return;const doctorId=text(req.body?.doctorId),practiceId=text(req.body?.practiceId),preferredRoute=text(req.body?.preferredRoute);if(!doctorId||!practiceId||(preferredRoute&&!validRoute(preferredRoute)))return res.status(400).json({error:'Doctor, practice, and a valid route are required.'});const versionResult=await deps.pool.query<{version:number}>('SELECT COALESCE(max(version),0)+1 version FROM doctor_preference_profiles WHERE tenant_id=$1 AND doctor_id=$2',[actor.tenantId,doctorId]);const version=versionResult.rows[0]?.version??1;await deps.pool.query('UPDATE doctor_preference_profiles SET active=false,updated_at=now() WHERE tenant_id=$1 AND doctor_id=$2 AND active=true',[actor.tenantId,doctorId]);const result=await deps.pool.query('INSERT INTO doctor_preference_profiles(id,tenant_id,doctor_id,practice_id,defaults,preferred_route,preferred_outsource_partner,version,active) VALUES($1,$2,$3,$4,$5::jsonb,$6,$7,$8,true) RETURNING *',[randomUUID(),actor.tenantId,doctorId,practiceId,JSON.stringify(req.body?.defaults??{}),preferredRoute||null,text(req.body?.preferredOutsourcePartner)||null,version]);await audit(deps,req,'intake.doctor-preference.saved','doctor-preference',String(result.rows[0]?.id),{doctorId,version});return res.status(201).json(result.rows[0])});
 app.delete('/api/intake/admin/doctor-preferences/:id',async(req:SecurityRequest,res)=>{const actor=requireAdmin(req,res);if(!actor)return;const result=await deps.pool.query('UPDATE doctor_preference_profiles SET active=false,updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING id',[actor.tenantId,req.params.id]);if(!result.rowCount)return res.status(404).json({error:'Preference profile not found.'});await audit(deps,req,'intake.doctor-preference.deactivated','doctor-preference',req.params.id);return res.status(204).send()});

 app.get('/api/intake/admin/practice-routing',async(req:SecurityRequest,res)=>{const actor=identity(req);const result=await deps.pool.query('SELECT * FROM practice_routing_profiles WHERE tenant_id=$1 ORDER BY practice_id',[actor.tenantId]);return res.json(result.rows)});
 app.put('/api/intake/admin/practice-routing/:practiceId',async(req:SecurityRequest,res)=>{const actor=requireAdmin(req,res);if(!actor)return;const route=text(req.body?.preferredRoute);if(!validRoute(route))return res.status(400).json({error:'A valid preferred route is required.'});const result=await deps.pool.query(`INSERT INTO practice_routing_profiles(tenant_id,practice_id,preferred_route,preferred_outsource_partner,configuration,active) VALUES($1,$2,$3,$4,$5::jsonb,true) ON CONFLICT(tenant_id,practice_id) DO UPDATE SET preferred_route=EXCLUDED.preferred_route,preferred_outsource_partner=EXCLUDED.preferred_outsource_partner,configuration=EXCLUDED.configuration,active=true,updated_at=now() RETURNING *`,[actor.tenantId,req.params.practiceId,route,text(req.body?.preferredOutsourcePartner)||null,JSON.stringify(req.body?.configuration??{})]);await audit(deps,req,'intake.practice-routing.saved','practice-routing',req.params.practiceId,{route});return res.json(result.rows[0])});
 app.delete('/api/intake/admin/practice-routing/:practiceId',async(req:SecurityRequest,res)=>{const actor=requireAdmin(req,res);if(!actor)return;await deps.pool.query('UPDATE practice_routing_profiles SET active=false,updated_at=now() WHERE tenant_id=$1 AND practice_id=$2',[actor.tenantId,req.params.practiceId]);await audit(deps,req,'intake.practice-routing.deactivated','practice-routing',req.params.practiceId);return res.status(204).send()});

 app.get('/api/intake/admin/tenant-routing',async(req:SecurityRequest,res)=>{const actor=identity(req);const result=await deps.pool.query('SELECT * FROM tenant_routing_defaults WHERE tenant_id=$1',[actor.tenantId]);return res.json(result.rows[0]??null)});
 app.put('/api/intake/admin/tenant-routing',async(req:SecurityRequest,res)=>{const actor=requireAdmin(req,res);if(!actor)return;const route=text(req.body?.preferredRoute);if(!validRoute(route))return res.status(400).json({error:'A valid tenant route is required.'});const result=await deps.pool.query(`INSERT INTO tenant_routing_defaults(tenant_id,preferred_route,preferred_outsource_partner,configuration,updated_by) VALUES($1,$2,$3,$4::jsonb,$5) ON CONFLICT(tenant_id) DO UPDATE SET preferred_route=EXCLUDED.preferred_route,preferred_outsource_partner=EXCLUDED.preferred_outsource_partner,configuration=EXCLUDED.configuration,updated_by=EXCLUDED.updated_by,updated_at=now() RETURNING *`,[actor.tenantId,route,text(req.body?.preferredOutsourcePartner)||null,JSON.stringify(req.body?.configuration??{}),actor.userId]);await audit(deps,req,'intake.tenant-routing.saved','tenant-routing',actor.tenantId,{route});return res.json(result.rows[0])});

 app.get('/api/intake/admin/pricing-schedules',async(req:SecurityRequest,res)=>{const actor=identity(req);const result=await deps.pool.query('SELECT id,schedule_type,name,practice_id,starts_at,ends_at,priority,active,metadata,created_at,updated_at FROM pricing_schedules WHERE tenant_id=$1 ORDER BY priority,name',[actor.tenantId]);return res.json(result.rows)});
 app.post('/api/intake/admin/pricing-schedules',async(req:SecurityRequest,res)=>{const actor=requireAdmin(req,res);if(!actor)return;const scheduleType=text(req.body?.scheduleType),name=text(req.body?.name);if(!['standard','contract','promotion','customer-override'].includes(scheduleType)||!name)return res.status(400).json({error:'A valid schedule type and name are required.'});const result=await deps.pool.query('INSERT INTO pricing_schedules(tenant_id,schedule_type,name,practice_id,starts_at,ends_at,priority,active,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,true,$8::jsonb) RETURNING id,schedule_type,name,practice_id,starts_at,ends_at,priority,active,metadata',[actor.tenantId,scheduleType,name,text(req.body?.practiceId)||null,req.body?.startsAt||null,req.body?.endsAt||null,Number(req.body?.priority??100),JSON.stringify(req.body?.metadata??{})]);await audit(deps,req,'pricing-schedule.created','pricing-schedule',String(result.rows[0]?.id),{scheduleType});return res.status(201).json(result.rows[0])});
 app.put('/api/intake/admin/pricing-schedules/:id',async(req:SecurityRequest,res)=>{const actor=requireAdmin(req,res);if(!actor)return;const result=await deps.pool.query('UPDATE pricing_schedules SET name=COALESCE(NULLIF($3,\'\'),name),practice_id=$4,starts_at=$5,ends_at=$6,priority=$7,active=$8,metadata=$9::jsonb,updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING id,schedule_type,name,practice_id,starts_at,ends_at,priority,active,metadata',[actor.tenantId,req.params.id,text(req.body?.name),text(req.body?.practiceId)||null,req.body?.startsAt||null,req.body?.endsAt||null,Number(req.body?.priority??100),req.body?.active!==false,JSON.stringify(req.body?.metadata??{})]);if(!result.rowCount)return res.status(404).json({error:'Pricing schedule not found.'});await audit(deps,req,'pricing-schedule.updated','pricing-schedule',req.params.id);return res.json(result.rows[0])});
}
