import { randomUUID } from 'node:crypto';
import type { Express } from 'express';
import type { Pool, PoolClient } from 'pg';
import type { AuditRepository } from './infrastructure/contracts.js';
import type { SecurityRequest } from './security.js';

const text=(value:unknown)=>typeof value==='string'?value.trim():'';
const publicProduct=(row:Record<string,unknown>)=>({id:row.id,sku:row.sku,productName:row.product_name,restorationCategory:row.restoration_category,restorationSubtype:row.restoration_subtype,material:row.material,department:row.department,accountingCategory:row.accounting_category,taxStatus:row.tax_status,turnaroundCategory:row.turnaround_category,active:row.active});
const forbiddenPricingFields=['defaultCustomerPrice','promotionalPrice','customerPrice','contractPrice','unitPrice','price'];
const slug=(value:string)=>value.toUpperCase().replace(/[^A-Z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,40);

type CatalogIdentity={sku:string;productName:string;restorationCategory:string;restorationSubtype:string;material:string;department:string;accountingCategory:string;taxStatus:string;turnaroundCategory:string;metadata:Record<string,unknown>};
type Restoration={category?:string;type?:string;subtype?:string;material?:string;quantity?:number;units?:number[];toothNumbers?:number[];arches?:string[]};

export class ProductCatalogFoundation {
 constructor(private readonly pool:Pool){}
 private hasPricing(input:Record<string,unknown>){return forbiddenPricingFields.some(field=>input[field]!==undefined)}
 async create(tenantId:string,input:Record<string,unknown>){
  if(this.hasPricing(input))throw new Error('Customer pricing belongs to Pricing Schedules and Billing, not Product Catalog.');
  if(!text(input.sku)||!text(input.productName)||!text(input.restorationCategory)||!text(input.restorationSubtype))throw new Error('SKU, product name, category, and subtype are required.');
  const result=await this.pool.query(`INSERT INTO product_catalog(tenant_id,sku,product_name,restoration_category,restoration_subtype,material,department,accounting_category,internal_cost,outsource_cost,tax_status,turnaround_category,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13::jsonb) RETURNING *`,[tenantId,text(input.sku),text(input.productName),text(input.restorationCategory),text(input.restorationSubtype),text(input.material)||null,text(input.department)||'fixed',text(input.accountingCategory)||text(input.restorationCategory),input.internalCost??null,input.outsourceCost??null,text(input.taxStatus)||'taxable',text(input.turnaroundCategory)||'standard',JSON.stringify(input.metadata??{})]);
  return result.rows[0] as Record<string,unknown>;
 }
 async ensure(client:PoolClient,tenantId:string,identity:CatalogIdentity){
  const result=await client.query<{id:string}>(`INSERT INTO product_catalog(tenant_id,sku,product_name,restoration_category,restoration_subtype,material,department,accounting_category,tax_status,turnaround_category,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb) ON CONFLICT(tenant_id,sku) DO UPDATE SET product_name=EXCLUDED.product_name,restoration_category=EXCLUDED.restoration_category,restoration_subtype=EXCLUDED.restoration_subtype,material=EXCLUDED.material,department=EXCLUDED.department,accounting_category=EXCLUDED.accounting_category,tax_status=EXCLUDED.tax_status,turnaround_category=EXCLUDED.turnaround_category,metadata=product_catalog.metadata||EXCLUDED.metadata,active=true,updated_at=now() RETURNING id`,[tenantId,identity.sku,identity.productName,identity.restorationCategory,identity.restorationSubtype,identity.material,identity.department,identity.accountingCategory,identity.taxStatus,identity.turnaroundCategory,JSON.stringify(identity.metadata)]);
  return result.rows[0]?.id;
 }
}

function descriptor(item:Restoration):CatalogIdentity&{quantity:number;restorationType:string}{
 const category=text(item.category),restorationType=text(item.type),subtype=text(item.subtype)||restorationType,material=text(item.material)||'Not applicable';
 const department=/denture|partial|removable/i.test(category)?'removables':/implant|abutment|guide/i.test(`${category} ${subtype}`)?'implants':'fixed';
 return{sku:`AUTO-${slug(subtype)}-${slug(material)}`,productName:`${subtype}${material==='Not applicable'?'':` · ${material}`}`,restorationCategory:category,restorationSubtype:subtype,restorationType,material,department,accountingCategory:category||'Restorations',taxStatus:'taxable',turnaroundCategory:'standard',metadata:{autoCreated:true},quantity:Number(item.quantity??item.units?.length??item.toothNumbers?.length??item.arches?.length??1)||1};
}

export function installProductCatalogFoundation(app:Express,pool:Pool,audit:AuditRepository){
 const catalog=new ProductCatalogFoundation(pool);
 app.post('/api/intake/catalog',async(req:SecurityRequest,res)=>{const actor=req.identity;if(!actor)return res.status(401).json({error:'Authentication required.'});try{const row=await catalog.create(actor.tenantId,req.body??{});await audit.append({tenantId:actor.tenantId,actorId:actor.userId,actorName:actor.name,action:'intake.product-catalog.created',entityType:'product-catalog',entityId:String(row.id),occurredAt:new Date().toISOString(),metadata:{role:actor.role,sku:text(row.sku)}});return res.status(201).json(publicProduct(row))}catch(error){return res.status(400).json({error:error instanceof Error?error.message:'Unable to create Product Catalog record.'})}});
 app.post('/api/intake/submissions/:id/resolve-products',async(req:SecurityRequest,res)=>{const actor=req.identity;if(!actor)return res.status(401).json({error:'Authentication required.'});const prescription=await pool.query<{restorations:Restoration[]}>('SELECT restorations FROM digital_prescriptions WHERE tenant_id=$1 AND submission_id=$2',[actor.tenantId,req.params.id]);if(!prescription.rowCount)return res.status(409).json({error:'Digital Prescription is required before product resolution.'});const client=await pool.connect();try{await client.query('BEGIN');await client.query('DELETE FROM intake_product_resolutions WHERE tenant_id=$1 AND submission_id=$2 AND frozen_at IS NULL',[actor.tenantId,req.params.id]);const products=[];for(const item of prescription.rows[0]?.restorations??[]){const value=descriptor(item);const catalogProductId=await catalog.ensure(client,actor.tenantId,value);const result=await client.query(`INSERT INTO intake_product_resolutions(tenant_id,submission_id,catalog_product_id,sku,product_category,restoration_type,restoration_subtype,material,quantity,department,accounting_category,resolved_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING id,sku,product_category,restoration_type,restoration_subtype,material,quantity,department,accounting_category,resolved_at`,[actor.tenantId,req.params.id,catalogProductId,value.sku,value.restorationCategory,value.restorationType,value.restorationSubtype,value.material,value.quantity,value.department,value.accountingCategory,actor.userId]);products.push(result.rows[0])}await client.query('INSERT INTO intake_history(tenant_id,submission_id,event_type,actor_id,actor_name,actor_role,details) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb)',[actor.tenantId,req.params.id,'products.resolved',actor.userId,actor.name,actor.role,JSON.stringify({count:products.length,skus:products.map(item=>item.sku)})]);await client.query(`INSERT INTO communication_events(id,tenant_id,entity_type,entity_id,event_type,content,actor_id,actor_name,actor_role) VALUES($1,$2,'case',$3,'system-event',$4,$5,$6,$7)`,[randomUUID(),actor.tenantId,req.params.id,`Digital intake · product resolution completed: ${products.length} billable product record(s) identified without pricing disclosure.`,actor.userId,actor.name,actor.role]);await client.query('COMMIT');await audit.append({tenantId:actor.tenantId,actorId:actor.userId,actorName:actor.name,action:'intake.products.changed',entityType:'intake-submission',entityId:req.params.id,occurredAt:new Date().toISOString(),metadata:{role:actor.role,count:products.length}});return res.json(products)}catch(error){await client.query('ROLLBACK');return res.status(400).json({error:error instanceof Error?error.message:'Unable to resolve products.'})}finally{client.release()}});
}
