import type { Express } from 'express';
import type { Pool } from 'pg';
import type { AuditRepository } from './infrastructure/contracts.js';
import type { SecurityRequest } from './security.js';

const text=(value:unknown)=>typeof value==='string'?value.trim():'';
const publicProduct=(row:Record<string,unknown>)=>({id:row.id,sku:row.sku,productName:row.product_name,restorationCategory:row.restoration_category,restorationSubtype:row.restoration_subtype,material:row.material,department:row.department,accountingCategory:row.accounting_category,taxStatus:row.tax_status,turnaroundCategory:row.turnaround_category,active:row.active});

export function installProductCatalogFoundation(app:Express,pool:Pool,audit:AuditRepository){
 app.post('/api/intake/catalog',async(req:SecurityRequest,res)=>{const actor=req.identity;if(!actor)return res.status(401).json({error:'Authentication required.'});const input=req.body??{};if(!text(input.sku)||!text(input.productName)||!text(input.restorationCategory)||!text(input.restorationSubtype))return res.status(400).json({error:'SKU, product name, category, and subtype are required.'});if(input.defaultCustomerPrice!==undefined||input.promotionalPrice!==undefined||input.customerPrice!==undefined)return res.status(400).json({error:'Customer pricing belongs to Pricing Schedules and Billing, not Product Catalog.'});const result=await pool.query(`INSERT INTO product_catalog(tenant_id,sku,product_name,restoration_category,restoration_subtype,material,department,accounting_category,internal_cost,outsource_cost,tax_status,turnaround_category,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13::jsonb) RETURNING *`,[actor.tenantId,text(input.sku),text(input.productName),text(input.restorationCategory),text(input.restorationSubtype),text(input.material)||null,text(input.department)||'fixed',text(input.accountingCategory)||text(input.restorationCategory),input.internalCost??null,input.outsourceCost??null,text(input.taxStatus)||'taxable',text(input.turnaroundCategory)||'standard',JSON.stringify(input.metadata??{})]);await audit.append({tenantId:actor.tenantId,actorId:actor.userId,actorName:actor.name,action:'intake.product-catalog.created',entityType:'product-catalog',entityId:String(result.rows[0]?.id),occurredAt:new Date().toISOString(),metadata:{role:actor.role,sku:text(input.sku)}});return res.status(201).json(publicProduct(result.rows[0] as Record<string,unknown>))});
}
