import { randomUUID } from 'node:crypto';
import type { Express } from 'express';
import type { ClinicalCase, QCDefectCategory, QCInspection, QCInspectionInput, QCMetrics, QCOutcome, QCPhoto, QCPhotoInput, QCTemplate, QCTemplateInput } from '@northstar/shared';
import type { AuditRepository, QCRepository, RepositoryContext } from './infrastructure/contracts.js';
import type { ObjectStorage, StoredObjectKind } from './infrastructure/object-storage.js';

const outcomes:QCOutcome[]=['pass','rework','hold','remake','doctor-clarification'];
const categories:QCDefectCategory[]=['fit','contacts','occlusion','margin','anatomy','shade','surface','material','implant-interface','prescription','other'];
type CaseResolver=(caseId:string)=>Promise<ClinicalCase|null>;type CaseUpdater=(caseId:string,value:ClinicalCase)=>Promise<void>;
export interface QCDurableDependencies{repository:QCRepository;objects:ObjectStorage;audit:AuditRepository;context:RepositoryContext}

export function createQcEngine(app:Express,now:()=>string,resolveCase:CaseResolver,updateCase:CaseUpdater,durable:QCDurableDependencies){
 const seed:QCTemplate={id:'template-fixed',name:'Fixed Restoration Final QC',restorationTypes:['Full Zirconia Crown','Layered Zirconia','E.max Crown','Implant Crown'],status:'active',checklistItems:[{id:'check-fit',label:'Internal fit and seating verified',required:true,defectCategory:'fit',sortOrder:1},{id:'check-margin',label:'Margins are closed and continuous',required:true,defectCategory:'margin',sortOrder:2},{id:'check-contact',label:'Proximal contacts verified',required:true,defectCategory:'contacts',sortOrder:3},{id:'check-occlusion',label:'Occlusion verified',required:true,defectCategory:'occlusion',sortOrder:4},{id:'check-anatomy',label:'Anatomy and contour verified',required:true,defectCategory:'anatomy',sortOrder:5},{id:'check-shade',label:'Shade and surface finish verified',required:true,defectCategory:'shade',sortOrder:6}],createdAt:now(),updatedAt:now()};
 const ready=(async()=>{if((await durable.repository.listTemplates(durable.context)).length===0)await durable.repository.saveTemplate(durable.context,seed)})();
 const audit=(action:string,entityType:string,entityId:string,actorId:string,actorName:string,metadata:Record<string,unknown>)=>durable.audit.append({tenantId:durable.context.tenantId,actorId,actorName,action,entityType,entityId,occurredAt:now(),metadata});
 const hydratePhoto=async(photo:QCPhoto)=>{if(!photo.contentBase64.startsWith('object:'))return photo;const bytes=await durable.objects.get(photo.contentBase64.slice(7));return{...photo,contentBase64:bytes?Buffer.from(bytes).toString('base64'):''}};
 const hydrate=async(item:QCInspection)=>({...item,photos:await Promise.all(item.photos.map(hydratePhoto))});
 async function metrics():Promise<QCMetrics>{await ready;const inspections=await durable.repository.listInspections(durable.context);const total=inspections.length;const count=(outcome:QCOutcome)=>inspections.filter(item=>item.outcome===outcome).length;const outcomeCounts=Object.fromEntries(outcomes.map(outcome=>[outcome,count(outcome)])) as Record<QCOutcome,number>;const percentage=(value:number)=>total?Number(((value/total)*100).toFixed(1)):0;const ordered=[...inspections].sort((a,b)=>a.createdAt.localeCompare(b.createdAt));const firstPass=ordered.filter((item,index,array)=>item.outcome==='pass'&&array.findIndex(other=>other.caseId===item.caseId)===index).length;return{totalInspections:total,passRate:percentage(outcomeCounts.pass),remakeRate:percentage(outcomeCounts.remake),reworkRate:percentage(outcomeCounts.rework),firstPassYield:percentage(firstPass),outcomeCounts,defectTrends:categories.map(category=>({category,count:inspections.flatMap(item=>item.defects).filter(defect=>defect.category===category).length})).filter(item=>item.count>0).sort((a,b)=>b.count-a.count)}}
 app.get('/api/qc/templates',async(req,res)=>{await ready;const restoration=typeof req.query.restoration==='string'?req.query.restoration:'';res.json((await durable.repository.listTemplates(durable.context)).filter(item=>item.status==='active'&&(!restoration||item.restorationTypes.includes(restoration))))});
 app.post('/api/qc/templates',async(req,res)=>{await ready;const body=req.body as QCTemplateInput;if(!body.name?.trim()||!body.restorationTypes?.length||!body.checklistItems?.length)return res.status(400).json({error:'Template name, restoration types, and checklist items are required.'});if(body.checklistItems.some(item=>!item.label?.trim()||!categories.includes(item.defectCategory)))return res.status(400).json({error:'Every checklist item requires a label and valid defect category.'});const item:QCTemplate={id:randomUUID(),name:body.name.trim(),restorationTypes:body.restorationTypes,status:body.status,checklistItems:body.checklistItems.map(value=>({...value,id:randomUUID()})),createdAt:now(),updatedAt:now()};await durable.repository.saveTemplate(durable.context,item);await audit('qc.template.created','qc-template',item.id,durable.context.actorId,durable.context.actorName,{});return res.status(201).json(item)});
 app.put('/api/qc/templates/:id',async(req,res)=>{await ready;const existing=(await durable.repository.listTemplates(durable.context)).find(item=>item.id===req.params.id);if(!existing)return res.status(404).json({error:'QC template not found.'});const body=req.body as QCTemplateInput;if(!body.name?.trim()||!body.restorationTypes?.length||!body.checklistItems?.length)return res.status(400).json({error:'Template name, restoration types, and checklist items are required.'});const item={...existing,...body,name:body.name.trim(),checklistItems:body.checklistItems.map(value=>({...value,id:randomUUID()})),updatedAt:now()};await durable.repository.saveTemplate(durable.context,item);await audit('qc.template.updated','qc-template',item.id,durable.context.actorId,durable.context.actorName,{});return res.json(item)});
 app.get('/api/qc/inspections',async(req,res)=>{await ready;const caseId=typeof req.query.caseId==='string'?req.query.caseId:undefined;const outcome=typeof req.query.outcome==='string'?req.query.outcome:'';const rows=(await durable.repository.listInspections(durable.context,caseId)).filter(item=>!outcome||item.outcome===outcome);res.json(await Promise.all(rows.map(hydrate)))});
 app.get('/api/qc/inspections/:id',async(req,res)=>{await ready;const item=(await durable.repository.listInspections(durable.context)).find(value=>value.id===req.params.id);return item?res.json(await hydrate(item)):res.status(404).json({error:'QC inspection not found.'})});
 app.post('/api/qc/inspections',async(req,res)=>{await ready;const body=req.body as QCInspectionInput;const clinicalCase=await resolveCase(body.caseId);const template=(await durable.repository.listTemplates(durable.context)).find(item=>item.id===body.templateId&&item.status==='active');if(!clinicalCase)return res.status(400).json({error:'A valid clinical case is required.'});if(!template||!template.restorationTypes.includes(clinicalCase.restoration))return res.status(400).json({error:'A compatible active QC template is required.'});if(!outcomes.includes(body.outcome)||!body.inspectorId?.trim()||!body.inspectorName?.trim())return res.status(400).json({error:'Outcome and digital inspector sign-off are required.'});const required=template.checklistItems.filter(item=>item.required);if(required.some(item=>!body.checklist.some(result=>result.checklistItemId===item.id&&result.result!=='not-applicable')))return res.status(400).json({error:'All required checklist items must be inspected.'});if(body.checklist.some(result=>result.result==='fail')&&body.defects.length===0)return res.status(400).json({error:'Failed checklist items require at least one categorized defect.'});if(body.outcome==='pass'&&body.checklist.some(result=>result.result==='fail'))return res.status(400).json({error:'A passing inspection cannot contain failed checklist items.'});const id=randomUUID(),timestamp=now();const inspection:QCInspection={id,caseId:clinicalCase.id,caseNumber:clinicalCase.caseNumber,templateId:template.id,restorationType:clinicalCase.restoration,outcome:body.outcome,checklist:body.checklist,defects:body.defects.map(defect=>({...defect,id:randomUUID()})),photos:[],inspectorId:body.inspectorId.trim(),inspectorName:body.inspectorName.trim(),signedAt:timestamp,notes:body.notes?.trim()??'',history:[{id:randomUUID(),inspectionId:id,action:'digitally-signed',outcome:body.outcome,note:body.notes?.trim()??'',actorId:body.inspectorId.trim(),actorName:body.inspectorName.trim(),occurredAt:timestamp}],createdAt:timestamp,updatedAt:timestamp};await durable.repository.saveInspection(durable.context,inspection);await updateCase(clinicalCase.id,{...clinicalCase,status:body.outcome==='pass'?'ready-to-ship':'qc',updatedAt:timestamp});await audit('qc.inspection.signed','qc-inspection',id,inspection.inspectorId,inspection.inspectorName,{caseId:inspection.caseId,outcome:inspection.outcome});return res.status(201).json(inspection)});
 app.post('/api/qc/inspections/:id/photos',async(req,res)=>{await ready;const inspection=(await durable.repository.listInspections(durable.context)).find(item=>item.id===req.params.id);if(!inspection)return res.status(404).json({error:'QC inspection not found.'});const body=req.body as QCPhotoInput;if(!body.fileName?.trim()||!body.mimeType?.startsWith('image/')||!body.contentBase64?.trim())return res.status(400).json({error:'A valid QC photo is required.'});const bytes=Buffer.from(body.contentBase64,'base64');const stored=await durable.objects.put({tenantId:durable.context.tenantId,ownerType:'qc-inspection',ownerId:inspection.id,kind:'qc-photo' as StoredObjectKind,fileName:body.fileName.trim(),mimeType:body.mimeType,bytes});const photo:QCPhoto={...body,id:randomUUID(),inspectionId:inspection.id,fileName:body.fileName.trim(),contentBase64:`object:${stored.objectKey}`,uploadedBy:body.uploadedBy?.trim()||inspection.inspectorName,uploadedAt:now()};inspection.photos.push(photo);inspection.history.unshift({id:randomUUID(),inspectionId:inspection.id,action:'photo-attached',outcome:inspection.outcome,note:photo.fileName,actorId:inspection.inspectorId,actorName:photo.uploadedBy,occurredAt:photo.uploadedAt});inspection.updatedAt=photo.uploadedAt;await durable.repository.saveInspection(durable.context,inspection);await audit('qc.photo.attached','qc-inspection',inspection.id,inspection.inspectorId,photo.uploadedBy,{objectKey:stored.objectKey,fileName:photo.fileName});return res.status(201).json({...photo,contentBase64:body.contentBase64})});
 app.get('/api/qc/metrics',async(_req,res)=>res.json(await metrics()));return{metrics};
}
