import cors from 'cors';
import express from 'express';
import { randomUUID } from 'node:crypto';
import type { AttachmentInput, CaseAttachment, ClinicalCase, ClinicalCaseInput, CommunicationEntry, DashboardSnapshot, Doctor, DoctorInput, EntityStatus, Patient, PatientInput, Practice, PracticeInput } from '@northstar/shared';

const app = express();
const port = Number(process.env.PORT ?? 4000);
app.use(cors());
app.use(express.json({ limit: '25mb' }));

const now = () => new Date().toISOString();
const today = () => new Date().toISOString().slice(0, 10);
let accountSequence = 1001;
let caseSequence = 1;

const practices: Practice[] = [{ id:'practice-1',accountNumber:'KDL-1001',practiceName:'NorthStar Dental Group',status:'active',phone:'818-555-0148',email:'office@northstardental.example',address:'19350 Business Ctr Dr',city:'Northridge',state:'CA',postalCode:'91324',taxExempt:false,scannerType:'iTero',officeManager:{name:'Alex Morgan',email:'manager@northstardental.example',phone:'818-555-0199'},notes:'Primary digital client.',communicationHistory:[],createdAt:now(),updatedAt:now()}];
const doctors: Doctor[] = [{ id:'doctor-1',practiceId:'practice-1',firstName:'Beibei',lastName:'Wu',specialty:'General Dentistry',email:'doctor@example.com',phone:'818-555-0171',status:'active',notes:'',communicationHistory:[],createdAt:now(),updatedAt:now()}];
const patients: Patient[] = [{ id:'patient-1',practiceId:'practice-1',doctorId:'doctor-1',patientReference:'ML-014',firstName:'Marissa',lastName:'Lugo',dateOfBirth:'1984-06-12',status:'active',notes:'Implant restorative patient.',createdAt:now(),updatedAt:now()}];
const cases: ClinicalCase[] = [];

function text(value: unknown) { return typeof value === 'string' ? value.trim() : ''; }
function status(value: unknown): EntityStatus { return value === 'inactive' ? 'inactive' : 'active'; }
function validEmail(value: string) { return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value); }
function queryMatch(values: string[], query: string) { return values.join(' ').toLowerCase().includes(query.toLowerCase()); }
function addBusinessDays(dateValue: string, days: number) { const date = new Date(`${dateValue}T12:00:00`); let added=0; while(added<days){date.setDate(date.getDate()+1);const day=date.getDay();if(day!==0&&day!==6)added+=1;} return date.toISOString().slice(0,10); }
function turnaroundDays(restoration: string, rush: boolean) { const extended = /implant|denture|partial|overdenture|surgical/i.test(restoration); return rush ? (extended ? 7 : 5) : (extended ? 14 : 10); }
function nextCaseNumber() { const date=today().replaceAll('-','').slice(2); return `NS-${date}-${String(caseSequence++).padStart(3,'0')}`; }

function validatePractice(body: Partial<PracticeInput>) { const errors:string[]=[]; if(!text(body.practiceName))errors.push('Practice name is required.'); if(!text(body.phone))errors.push('Practice phone is required.'); if(!validEmail(text(body.email)))errors.push('A valid practice email is required.'); if(!text(body.officeManager?.name))errors.push('Office manager name is required.'); if(!validEmail(text(body.officeManager?.email)))errors.push('A valid office manager email is required.'); return errors; }
function validateDoctor(body: Partial<DoctorInput>) { const errors:string[]=[]; if(!practices.some(item=>item.id===body.practiceId))errors.push('A valid practice is required.'); if(!text(body.firstName))errors.push('First name is required.'); if(!text(body.lastName))errors.push('Last name is required.'); if(!validEmail(text(body.email)))errors.push('A valid doctor email is required.'); return errors; }
function validatePatient(body: Partial<PatientInput>) { const errors:string[]=[]; const doctor=doctors.find(item=>item.id===body.doctorId); if(!practices.some(item=>item.id===body.practiceId))errors.push('A valid practice is required.'); if(!doctor||doctor.practiceId!==body.practiceId)errors.push('Doctor must belong to the selected practice.'); if(!text(body.patientReference))errors.push('Patient reference is required.'); if(!text(body.firstName))errors.push('Patient first name is required.'); if(!text(body.lastName))errors.push('Patient last name is required.'); return errors; }
function validateCase(body: Partial<ClinicalCaseInput>) { const errors:string[]=[]; const patient=patients.find(item=>item.id===body.patientId); const doctor=doctors.find(item=>item.id===body.doctorId); if(!patient)errors.push('A valid patient is required.'); if(!practices.some(item=>item.id===body.practiceId))errors.push('A valid practice is required.'); if(!doctor||doctor.practiceId!==body.practiceId)errors.push('Doctor must belong to the selected practice.'); if(patient&&(patient.practiceId!==body.practiceId||patient.doctorId!==body.doctorId))errors.push('Patient, practice, and doctor associations must match.'); if(!text(body.restoration))errors.push('Restoration is required.'); if(!text(body.material))errors.push('Material is required.'); if(!text(body.shade))errors.push('Shade is required.'); if(!text(body.receivedDate))errors.push('Received date is required.'); if((body.toothNumbers?.length??0)===0&&(!body.arch||body.arch==='not-applicable'))errors.push('Select at least one Universal tooth number or an arch.'); if(body.toothNumbers?.some(value=>!Number.isInteger(value)||value<1||value>32))errors.push('Universal tooth numbers must be between 1 and 32.'); return errors; }
function addCommunication(entityType:'practice'|'doctor',entityId:string,body:Partial<CommunicationEntry>){const summary=text(body.summary);if(!summary)return null;return{id:randomUUID(),entityType,entityId,type:body.type??'note',summary,occurredAt:body.occurredAt??now(),createdBy:text(body.createdBy)||'Dorian Habet'} satisfies CommunicationEntry;}

app.get('/health',(_request,response)=>response.json({service:'cadence-northstar-api',status:'ok',version:'0.4.0'}));
app.post('/api/auth/login',(request,response)=>{const{email,password}=request.body as{email?:string;password?:string};if(email==='dorianhabet@yahoo.com'&&password==='NorthStar!2026')return response.json({user:{id:'usr-admin',name:'Dorian Habet',email,role:'administrator',active:true}});return response.status(401).json({error:'Invalid credentials'});});
app.get('/api/dashboard',(_request,response)=>{const snapshot:DashboardSnapshot={generatedAt:now(),casesReceivedToday:cases.filter(item=>item.receivedDate===today()).length,casesDueToday:cases.filter(item=>item.dueDate===today()&&item.status!=='completed').length,casesAtRisk:cases.filter(item=>item.dueDate<today()&&item.status!=='completed').length,casesInQc:cases.filter(item=>item.status==='qc').length,shipmentsReady:cases.filter(item=>item.status==='ready-to-ship').length,monthRevenue:0,activeDoctors:doctors.filter(item=>item.status==='active').length,activePractices:practices.filter(item=>item.status==='active').length,activePatients:patients.filter(item=>item.status==='active').length,openCases:cases.filter(item=>item.status!=='completed').length,rushCases:cases.filter(item=>item.rushPriority==='rush'&&item.status!=='completed').length};response.json(snapshot);});

app.get('/api/practices',(request,response)=>{const search=text(request.query.search),filter=text(request.query.status);response.json(practices.filter(item=>(!filter||filter==='all'||item.status===filter)&&(!search||queryMatch([item.accountNumber,item.practiceName,item.email,item.officeManager.name],search))));});
app.post('/api/practices',(request,response)=>{const body=request.body as PracticeInput,errors=validatePractice(body);if(errors.length)return response.status(400).json({errors});const item:Practice={...body,id:randomUUID(),accountNumber:`KDL-${++accountSequence}`,status:status(body.status),officeManager:{name:text(body.officeManager.name),email:text(body.officeManager.email),phone:text(body.officeManager.phone)},notes:text(body.notes),communicationHistory:[],createdAt:now(),updatedAt:now()};practices.push(item);return response.status(201).json(item);});
app.put('/api/practices/:id',(request,response)=>{const index=practices.findIndex(item=>item.id===request.params.id);if(index<0)return response.status(404).json({error:'Practice not found.'});const body=request.body as PracticeInput,errors=validatePractice(body);if(errors.length)return response.status(400).json({errors});practices[index]={...practices[index],...body,id:practices[index].id,accountNumber:practices[index].accountNumber,status:status(body.status),communicationHistory:practices[index].communicationHistory,updatedAt:now()};return response.json(practices[index]);});
app.delete('/api/practices/:id',(request,response)=>{const index=practices.findIndex(item=>item.id===request.params.id);if(index<0)return response.status(404).json({error:'Practice not found.'});if(doctors.some(item=>item.practiceId===request.params.id)||patients.some(item=>item.practiceId===request.params.id)||cases.some(item=>item.practiceId===request.params.id))return response.status(409).json({error:'Practice has linked records and cannot be deleted.'});practices.splice(index,1);return response.status(204).send();});
app.post('/api/practices/:id/communications',(request,response)=>{const item=practices.find(value=>value.id===request.params.id);if(!item)return response.status(404).json({error:'Practice not found.'});const entry=addCommunication('practice',item.id,request.body);if(!entry)return response.status(400).json({error:'Communication summary is required.'});item.communicationHistory.unshift(entry);item.updatedAt=now();return response.status(201).json(entry);});

app.get('/api/doctors',(request,response)=>{const search=text(request.query.search),filter=text(request.query.status),practiceId=text(request.query.practiceId);response.json(doctors.filter(item=>(!filter||filter==='all'||item.status===filter)&&(!practiceId||item.practiceId===practiceId)&&(!search||queryMatch([item.firstName,item.lastName,item.email,item.specialty],search))));});
app.post('/api/doctors',(request,response)=>{const body=request.body as DoctorInput,errors=validateDoctor(body);if(errors.length)return response.status(400).json({errors});const item:Doctor={...body,id:randomUUID(),status:status(body.status),notes:text(body.notes),communicationHistory:[],createdAt:now(),updatedAt:now()};doctors.push(item);return response.status(201).json(item);});
app.put('/api/doctors/:id',(request,response)=>{const index=doctors.findIndex(item=>item.id===request.params.id);if(index<0)return response.status(404).json({error:'Doctor not found.'});const body=request.body as DoctorInput,errors=validateDoctor(body);if(errors.length)return response.status(400).json({errors});doctors[index]={...doctors[index],...body,id:doctors[index].id,status:status(body.status),communicationHistory:doctors[index].communicationHistory,updatedAt:now()};return response.json(doctors[index]);});
app.delete('/api/doctors/:id',(request,response)=>{const index=doctors.findIndex(item=>item.id===request.params.id);if(index<0)return response.status(404).json({error:'Doctor not found.'});if(patients.some(item=>item.doctorId===request.params.id)||cases.some(item=>item.doctorId===request.params.id))return response.status(409).json({error:'Doctor has linked records and cannot be deleted.'});doctors.splice(index,1);return response.status(204).send();});
app.post('/api/doctors/:id/communications',(request,response)=>{const item=doctors.find(value=>value.id===request.params.id);if(!item)return response.status(404).json({error:'Doctor not found.'});const entry=addCommunication('doctor',item.id,request.body);if(!entry)return response.status(400).json({error:'Communication summary is required.'});item.communicationHistory.unshift(entry);item.updatedAt=now();return response.status(201).json(entry);});

app.get('/api/patients',(request,response)=>{const search=text(request.query.search),filter=text(request.query.status),practiceId=text(request.query.practiceId),doctorId=text(request.query.doctorId);response.json(patients.filter(item=>(!filter||filter==='all'||item.status===filter)&&(!practiceId||item.practiceId===practiceId)&&(!doctorId||item.doctorId===doctorId)&&(!search||queryMatch([item.patientReference,item.firstName,item.lastName],search))));});
app.get('/api/patients/:id',(request,response)=>{const item=patients.find(value=>value.id===request.params.id);return item?response.json(item):response.status(404).json({error:'Patient not found.'});});
app.post('/api/patients',(request,response)=>{const body=request.body as PatientInput,errors=validatePatient(body);if(errors.length)return response.status(400).json({errors});const item:Patient={...body,id:randomUUID(),status:status(body.status),notes:text(body.notes),createdAt:now(),updatedAt:now()};patients.push(item);return response.status(201).json(item);});
app.put('/api/patients/:id',(request,response)=>{const index=patients.findIndex(item=>item.id===request.params.id);if(index<0)return response.status(404).json({error:'Patient not found.'});const body=request.body as PatientInput,errors=validatePatient(body);if(errors.length)return response.status(400).json({errors});patients[index]={...patients[index],...body,id:patients[index].id,status:status(body.status),notes:text(body.notes),updatedAt:now()};return response.json(patients[index]);});
app.delete('/api/patients/:id',(request,response)=>{const index=patients.findIndex(item=>item.id===request.params.id);if(index<0)return response.status(404).json({error:'Patient not found.'});if(cases.some(item=>item.patientId===request.params.id))return response.status(409).json({error:'Patient has linked cases and cannot be deleted.'});patients.splice(index,1);return response.status(204).send();});

app.get('/api/cases',(request,response)=>{const search=text(request.query.search),filter=text(request.query.status),practiceId=text(request.query.practiceId),doctorId=text(request.query.doctorId),patientId=text(request.query.patientId);response.json(cases.filter(item=>(!filter||filter==='all'||item.status===filter)&&(!practiceId||item.practiceId===practiceId)&&(!doctorId||item.doctorId===doctorId)&&(!patientId||item.patientId===patientId)&&(!search||queryMatch([item.caseNumber,item.restoration,item.material,item.shade],search))));});
app.get('/api/cases/:id',(request,response)=>{const item=cases.find(value=>value.id===request.params.id);return item?response.json(item):response.status(404).json({error:'Case not found.'});});
app.post('/api/cases',(request,response)=>{const body=request.body as ClinicalCaseInput,errors=validateCase(body);if(errors.length)return response.status(400).json({errors});const item:ClinicalCase={...body,id:randomUUID(),caseNumber:nextCaseNumber(),dueDate:addBusinessDays(body.receivedDate,turnaroundDays(body.restoration,body.rushPriority==='rush')),attachments:[],createdAt:now(),updatedAt:now()};cases.push(item);return response.status(201).json(item);});
app.put('/api/cases/:id',(request,response)=>{const index=cases.findIndex(item=>item.id===request.params.id);if(index<0)return response.status(404).json({error:'Case not found.'});const body=request.body as ClinicalCaseInput,errors=validateCase(body);if(errors.length)return response.status(400).json({errors});cases[index]={...cases[index],...body,id:cases[index].id,caseNumber:cases[index].caseNumber,dueDate:addBusinessDays(body.receivedDate,turnaroundDays(body.restoration,body.rushPriority==='rush')),attachments:cases[index].attachments,updatedAt:now()};return response.json(cases[index]);});
app.delete('/api/cases/:id',(request,response)=>{const index=cases.findIndex(item=>item.id===request.params.id);if(index<0)return response.status(404).json({error:'Case not found.'});cases.splice(index,1);return response.status(204).send();});
app.post('/api/cases/:id/attachments',(request,response)=>{const item=cases.find(value=>value.id===request.params.id);if(!item)return response.status(404).json({error:'Case not found.'});const body=request.body as AttachmentInput;const allowed=['stl','obj','ply','dicom-cbct','rx','photo'];if(!allowed.includes(body.kind)||!text(body.fileName)||!text(body.contentBase64))return response.status(400).json({error:'Valid attachment metadata and content are required.'});const attachment:CaseAttachment={...body,id:randomUUID(),caseId:item.id,uploadedAt:now()};item.attachments.push(attachment);item.updatedAt=now();return response.status(201).json(attachment);});
app.delete('/api/cases/:caseId/attachments/:attachmentId',(request,response)=>{const item=cases.find(value=>value.id===request.params.caseId);if(!item)return response.status(404).json({error:'Case not found.'});const index=item.attachments.findIndex(value=>value.id===request.params.attachmentId);if(index<0)return response.status(404).json({error:'Attachment not found.'});item.attachments.splice(index,1);item.updatedAt=now();return response.status(204).send();});

app.listen(port,()=>console.log(`CADence NorthStar API listening on http://localhost:${port}`));
