import cors from 'cors';
import express from 'express';
import { randomUUID } from 'node:crypto';
import type { AttachmentInput, CaseAttachment, ClinicalCase, ClinicalCaseInput, CommunicationEntry, DashboardSnapshot, DepartmentWorkload, Doctor, DoctorInput, EntityStatus, Patient, PatientInput, Practice, PracticeInput, ProductionDepartment, ProductionHistoryEntry, ProductionTransitionInput, ProductionWorkItem, ProductionWorkItemInput, Technician } from '@northstar/shared';

const app=express();const port=Number(process.env.PORT??4000);app.use(cors());app.use(express.json({limit:'25mb'}));
const now=()=>new Date().toISOString();const today=()=>now().slice(0,10);let accountSequence=1001;let caseSequence=1;
const departments:ProductionDepartment[]=['receiving','case-review','model','cad','manufacturing','ceramics','qc','shipping'];
const practices:Practice[]=[{id:'practice-1',accountNumber:'KDL-1001',practiceName:'NorthStar Dental Group',status:'active',phone:'818-555-0148',email:'office@northstardental.example',address:'19350 Business Ctr Dr',city:'Northridge',state:'CA',postalCode:'91324',taxExempt:false,scannerType:'iTero',officeManager:{name:'Alex Morgan',email:'manager@northstardental.example',phone:'818-555-0199'},notes:'Primary digital client.',communicationHistory:[],createdAt:now(),updatedAt:now()}];
const doctors:Doctor[]=[{id:'doctor-1',practiceId:'practice-1',firstName:'Beibei',lastName:'Wu',specialty:'General Dentistry',email:'doctor@example.com',phone:'818-555-0171',status:'active',notes:'',communicationHistory:[],createdAt:now(),updatedAt:now()}];
const patients:Patient[]=[{id:'patient-1',practiceId:'practice-1',doctorId:'doctor-1',patientReference:'ML-014',firstName:'Marissa',lastName:'Lugo',dateOfBirth:'1984-06-12',status:'active',notes:'Implant restorative patient.',createdAt:now(),updatedAt:now()}];
const cases:ClinicalCase[]=[];
const technicians:Technician[]=[
{id:'tech-receiving',name:'Ana Receiving',departments:['receiving','case-review'],status:'active'},
{id:'tech-model',name:'Cecia Model',departments:['model'],status:'active'},
{id:'tech-cad',name:'Kelvin CAD',departments:['cad'],status:'active'},
{id:'tech-manufacturing',name:'John Manufacturing',departments:['manufacturing'],status:'active'},
{id:'tech-ceramics',name:'Shelly Ceramics',departments:['ceramics'],status:'active'},
{id:'tech-qc',name:'Dorian QC',departments:['qc'],status:'active'},
{id:'tech-shipping',name:'Roxanna Shipping',departments:['shipping'],status:'active'}];
const workItems:ProductionWorkItem[]=[];

function text(value:unknown){return typeof value==='string'?value.trim():''}function entityStatus(value:unknown):EntityStatus{return value==='inactive'?'inactive':'active'}function validEmail(value:string){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)}function queryMatch(values:string[],query:string){return values.join(' ').toLowerCase().includes(query.toLowerCase())}
function addBusinessDays(dateValue:string,days:number){const date=new Date(`${dateValue}T12:00:00`);let added=0;while(added<days){date.setDate(date.getDate()+1);if(date.getDay()!==0&&date.getDay()!==6)added++}return date.toISOString().slice(0,10)}function turnaroundDays(restoration:string,rush:boolean){const extended=/implant|denture|partial|overdenture|surgical/i.test(restoration);return rush?(extended?7:5):(extended?14:10)}function nextCaseNumber(){return `NS-${today().replaceAll('-','').slice(2)}-${String(caseSequence++).padStart(3,'0')}`}
function slaFor(department:ProductionDepartment,rush:boolean){const hours:Record<ProductionDepartment,number>={receiving:8,'case-review':8,model:24,cad:24,manufacturing:24,ceramics:48,qc:12,shipping:12};return new Date(Date.now()+hours[department]*(rush?.5:1)*3600000).toISOString()}
function validatePractice(body:Partial<PracticeInput>){const errors:string[]=[];if(!text(body.practiceName))errors.push('Practice name is required.');if(!text(body.phone))errors.push('Practice phone is required.');if(!validEmail(text(body.email)))errors.push('A valid practice email is required.');if(!text(body.officeManager?.name))errors.push('Office manager name is required.');if(!validEmail(text(body.officeManager?.email)))errors.push('A valid office manager email is required.');return errors}
function validateDoctor(body:Partial<DoctorInput>){const errors:string[]=[];if(!practices.some(item=>item.id===body.practiceId))errors.push('A valid practice is required.');if(!text(body.firstName))errors.push('First name is required.');if(!text(body.lastName))errors.push('Last name is required.');if(!validEmail(text(body.email)))errors.push('A valid doctor email is required.');return errors}
function validatePatient(body:Partial<PatientInput>){const errors:string[]=[];const doctor=doctors.find(item=>item.id===body.doctorId);if(!practices.some(item=>item.id===body.practiceId))errors.push('A valid practice is required.');if(!doctor||doctor.practiceId!==body.practiceId)errors.push('Doctor must belong to the selected practice.');if(!text(body.patientReference))errors.push('Patient reference is required.');if(!text(body.firstName))errors.push('Patient first name is required.');if(!text(body.lastName))errors.push('Patient last name is required.');return errors}
function validateCase(body:Partial<ClinicalCaseInput>){const errors:string[]=[];const patient=patients.find(item=>item.id===body.patientId);const doctor=doctors.find(item=>item.id===body.doctorId);if(!patient)errors.push('A valid patient is required.');if(!practices.some(item=>item.id===body.practiceId))errors.push('A valid practice is required.');if(!doctor||doctor.practiceId!==body.practiceId)errors.push('Doctor must belong to the selected practice.');if(patient&&(patient.practiceId!==body.practiceId||patient.doctorId!==body.doctorId))errors.push('Patient, practice, and doctor associations must match.');if(!text(body.restoration))errors.push('Restoration is required.');if(!text(body.material))errors.push('Material is required.');if(!text(body.shade))errors.push('Shade is required.');if(!text(body.receivedDate))errors.push('Received date is required.');if((body.toothNumbers?.length??0)===0&&(!body.arch||body.arch==='not-applicable'))errors.push('Select at least one Universal tooth number or an arch.');if(body.toothNumbers?.some(value=>!Number.isInteger(value)||value<1||value>32))errors.push('Universal tooth numbers must be between 1 and 32.');return errors}
function addCommunication(entityType:'practice'|'doctor',entityId:string,body:Partial<CommunicationEntry>){const summary=text(body.summary);if(!summary)return null;return{id:randomUUID(),entityType,entityId,type:body.type??'note',summary,occurredAt:body.occurredAt??now(),createdBy:text(body.createdBy)||'Dorian Habet'} satisfies CommunicationEntry}
function workload():DepartmentWorkload[]{const current=Date.now();return departments.map(department=>{const rows=workItems.filter(item=>item.currentDepartment===department&&item.status!=='completed');return{department,queued:rows.filter(item=>item.status==='queued').length,inProgress:rows.filter(item=>item.status==='in-progress').length,blocked:rows.filter(item=>item.status==='blocked').length,overdue:rows.filter(item=>new Date(item.slaDueAt).getTime()<current).length,total:rows.length}})}

app.get('/health',(_req,res)=>res.json({service:'cadence-northstar-api',status:'ok',version:'0.5.0'}));
app.post('/api/auth/login',(req,res)=>{const{email,password}=req.body as{email?:string;password?:string};return email==='dorianhabet@yahoo.com'&&password==='NorthStar!2026'?res.json({user:{id:'usr-admin',name:'Dorian Habet',email,role:'administrator',active:true}}):res.status(401).json({error:'Invalid credentials'})});
app.get('/api/dashboard',(_req,res)=>{const departmentWorkload=workload();const snapshot:DashboardSnapshot={generatedAt:now(),casesReceivedToday:cases.filter(item=>item.receivedDate===today()).length,casesDueToday:cases.filter(item=>item.dueDate===today()&&item.status!=='completed').length,casesAtRisk:cases.filter(item=>item.dueDate<today()&&item.status!=='completed').length,casesInQc:workItems.filter(item=>item.currentDepartment==='qc'&&item.status!=='completed').length,shipmentsReady:workItems.filter(item=>item.currentDepartment==='shipping'&&item.status!=='completed').length,monthRevenue:0,activeDoctors:doctors.filter(item=>item.status==='active').length,activePractices:practices.filter(item=>item.status==='active').length,activePatients:patients.filter(item=>item.status==='active').length,openCases:cases.filter(item=>item.status!=='completed').length,rushCases:cases.filter(item=>item.rushPriority==='rush'&&item.status!=='completed').length,productionOverdue:departmentWorkload.reduce((sum,item)=>sum+item.overdue,0),productionInProgress:workItems.filter(item=>item.status==='in-progress').length,departmentWorkload};res.json(snapshot)});
app.get('/api/practices',(req,res)=>{const search=text(req.query.search),filter=text(req.query.status);res.json(practices.filter(item=>(!filter||filter==='all'||item.status===filter)&&(!search||queryMatch([item.accountNumber,item.practiceName,item.email,item.officeManager.name],search))))});
app.post('/api/practices',(req,res)=>{const body=req.body as PracticeInput,errors=validatePractice(body);if(errors.length)return res.status(400).json({errors});const item:Practice={...body,id:randomUUID(),accountNumber:`KDL-${++accountSequence}`,status:entityStatus(body.status),communicationHistory:[],createdAt:now(),updatedAt:now()};practices.push(item);return res.status(201).json(item)});
app.put('/api/practices/:id',(req,res)=>{const i=practices.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({error:'Practice not found.'});const body=req.body as PracticeInput,errors=validatePractice(body);if(errors.length)return res.status(400).json({errors});practices[i]={...practices[i],...body,id:practices[i].id,accountNumber:practices[i].accountNumber,status:entityStatus(body.status),communicationHistory:practices[i].communicationHistory,updatedAt:now()};return res.json(practices[i])});
app.delete('/api/practices/:id',(req,res)=>{const i=practices.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({error:'Practice not found.'});if(doctors.some(x=>x.practiceId===req.params.id)||patients.some(x=>x.practiceId===req.params.id)||cases.some(x=>x.practiceId===req.params.id))return res.status(409).json({error:'Practice has linked records.'});practices.splice(i,1);return res.status(204).send()});
app.post('/api/practices/:id/communications',(req,res)=>{const item=practices.find(x=>x.id===req.params.id);if(!item)return res.status(404).json({error:'Practice not found.'});const entry=addCommunication('practice',item.id,req.body);if(!entry)return res.status(400).json({error:'Communication summary is required.'});item.communicationHistory.unshift(entry);return res.status(201).json(entry)});
app.get('/api/doctors',(req,res)=>{const search=text(req.query.search),filter=text(req.query.status),practiceId=text(req.query.practiceId);res.json(doctors.filter(item=>(!filter||filter==='all'||item.status===filter)&&(!practiceId||item.practiceId===practiceId)&&(!search||queryMatch([item.firstName,item.lastName,item.email,item.specialty],search))))});
app.post('/api/doctors',(req,res)=>{const body=req.body as DoctorInput,errors=validateDoctor(body);if(errors.length)return res.status(400).json({errors});const item:Doctor={...body,id:randomUUID(),status:entityStatus(body.status),communicationHistory:[],createdAt:now(),updatedAt:now()};doctors.push(item);return res.status(201).json(item)});
app.put('/api/doctors/:id',(req,res)=>{const i=doctors.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({error:'Doctor not found.'});const body=req.body as DoctorInput,errors=validateDoctor(body);if(errors.length)return res.status(400).json({errors});doctors[i]={...doctors[i],...body,id:doctors[i].id,status:entityStatus(body.status),communicationHistory:doctors[i].communicationHistory,updatedAt:now()};return res.json(doctors[i])});
app.delete('/api/doctors/:id',(req,res)=>{const i=doctors.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({error:'Doctor not found.'});if(patients.some(x=>x.doctorId===req.params.id)||cases.some(x=>x.doctorId===req.params.id))return res.status(409).json({error:'Doctor has linked records.'});doctors.splice(i,1);return res.status(204).send()});
app.post('/api/doctors/:id/communications',(req,res)=>{const item=doctors.find(x=>x.id===req.params.id);if(!item)return res.status(404).json({error:'Doctor not found.'});const entry=addCommunication('doctor',item.id,req.body);if(!entry)return res.status(400).json({error:'Communication summary is required.'});item.communicationHistory.unshift(entry);return res.status(201).json(entry)});
app.get('/api/patients',(req,res)=>{const search=text(req.query.search),filter=text(req.query.status),practiceId=text(req.query.practiceId),doctorId=text(req.query.doctorId);res.json(patients.filter(item=>(!filter||filter==='all'||item.status===filter)&&(!practiceId||item.practiceId===practiceId)&&(!doctorId||item.doctorId===doctorId)&&(!search||queryMatch([item.patientReference,item.firstName,item.lastName],search))))});
app.get('/api/patients/:id',(req,res)=>{const item=patients.find(x=>x.id===req.params.id);return item?res.json(item):res.status(404).json({error:'Patient not found.'})});
app.post('/api/patients',(req,res)=>{const body=req.body as PatientInput,errors=validatePatient(body);if(errors.length)return res.status(400).json({errors});const item:Patient={...body,id:randomUUID(),status:entityStatus(body.status),createdAt:now(),updatedAt:now()};patients.push(item);return res.status(201).json(item)});
app.put('/api/patients/:id',(req,res)=>{const i=patients.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({error:'Patient not found.'});const body=req.body as PatientInput,errors=validatePatient(body);if(errors.length)return res.status(400).json({errors});patients[i]={...patients[i],...body,id:patients[i].id,status:entityStatus(body.status),updatedAt:now()};return res.json(patients[i])});
app.delete('/api/patients/:id',(req,res)=>{const i=patients.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({error:'Patient not found.'});if(cases.some(x=>x.patientId===req.params.id))return res.status(409).json({error:'Patient has linked cases.'});patients.splice(i,1);return res.status(204).send()});
app.get('/api/cases',(req,res)=>{const search=text(req.query.search),filter=text(req.query.status);res.json(cases.filter(item=>(!filter||filter==='all'||item.status===filter)&&(!search||queryMatch([item.caseNumber,item.restoration,item.material,item.shade],search))))});
app.get('/api/cases/:id',(req,res)=>{const item=cases.find(x=>x.id===req.params.id);return item?res.json(item):res.status(404).json({error:'Case not found.'})});
app.post('/api/cases',(req,res)=>{const body=req.body as ClinicalCaseInput,errors=validateCase(body);if(errors.length)return res.status(400).json({errors});const item:ClinicalCase={...body,id:randomUUID(),caseNumber:nextCaseNumber(),dueDate:addBusinessDays(body.receivedDate,turnaroundDays(body.restoration,body.rushPriority==='rush')),attachments:[],createdAt:now(),updatedAt:now()};cases.push(item);return res.status(201).json(item)});
app.put('/api/cases/:id',(req,res)=>{const i=cases.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({error:'Case not found.'});const body=req.body as ClinicalCaseInput,errors=validateCase(body);if(errors.length)return res.status(400).json({errors});cases[i]={...cases[i],...body,id:cases[i].id,caseNumber:cases[i].caseNumber,dueDate:addBusinessDays(body.receivedDate,turnaroundDays(body.restoration,body.rushPriority==='rush')),attachments:cases[i].attachments,updatedAt:now()};return res.json(cases[i])});
app.delete('/api/cases/:id',(req,res)=>{const i=cases.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({error:'Case not found.'});if(workItems.some(x=>x.caseId===req.params.id))return res.status(409).json({error:'Case has production history.'});cases.splice(i,1);return res.status(204).send()});
app.post('/api/cases/:id/attachments',(req,res)=>{const item=cases.find(x=>x.id===req.params.id);if(!item)return res.status(404).json({error:'Case not found.'});const body=req.body as AttachmentInput;if(!['stl','obj','ply','dicom-cbct','rx','photo'].includes(body.kind)||!text(body.fileName)||!text(body.contentBase64))return res.status(400).json({error:'Valid attachment required.'});const attachment:CaseAttachment={...body,id:randomUUID(),caseId:item.id,uploadedAt:now()};item.attachments.push(attachment);return res.status(201).json(attachment)});
app.delete('/api/cases/:caseId/attachments/:attachmentId',(req,res)=>{const item=cases.find(x=>x.id===req.params.caseId);if(!item)return res.status(404).json({error:'Case not found.'});const i=item.attachments.findIndex(x=>x.id===req.params.attachmentId);if(i<0)return res.status(404).json({error:'Attachment not found.'});item.attachments.splice(i,1);return res.status(204).send()});

app.get('/api/production/departments',(_req,res)=>res.json(departments));
app.get('/api/production/technicians',(req,res)=>{const department=text(req.query.department);res.json(technicians.filter(item=>item.status==='active'&&(!department||item.departments.includes(department as ProductionDepartment))))});
app.get('/api/production/work-items',(req,res)=>{const department=text(req.query.department),statusFilter=text(req.query.status),overdue=text(req.query.overdue);res.json(workItems.filter(item=>(!department||item.currentDepartment===department)&&(!statusFilter||statusFilter==='all'||item.status===statusFilter)&&(!overdue||overdue!=='true'||(item.status!=='completed'&&new Date(item.slaDueAt).getTime()<Date.now()))))});
app.get('/api/production/work-items/:id',(req,res)=>{const item=workItems.find(x=>x.id===req.params.id);return item?res.json(item):res.status(404).json({error:'Work item not found.'})});
app.post('/api/production/work-items',(req,res)=>{const body=req.body as ProductionWorkItemInput;const clinicalCase=cases.find(x=>x.id===body.caseId);if(!clinicalCase)return res.status(400).json({error:'A valid case is required.'});if(workItems.some(x=>x.caseId===body.caseId))return res.status(409).json({error:'Case already has a production work item.'});if(!body.route?.length||body.route.some(value=>!departments.includes(value)))return res.status(400).json({error:'A valid department route is required.'});if(body.route[0]!=='receiving'||body.route[body.route.length-1]!=='shipping')return res.status(400).json({error:'Route must begin at Receiving and end at Shipping.'});const currentDepartment=body.route[0];const id=randomUUID();const history:ProductionHistoryEntry={id:randomUUID(),workItemId:id,fromDepartment:null,toDepartment:currentDepartment,status:'queued',technicianId:body.technicianId,note:'Production work item created.',occurredAt:now(),actorId:text(body.actorId),actorName:text(body.actorName)};const item:ProductionWorkItem={id,caseId:clinicalCase.id,caseNumber:clinicalCase.caseNumber,route:body.route,currentDepartment,status:'queued',technicianId:body.technicianId,startedAt:null,completedAt:null,slaDueAt:slaFor(currentDepartment,clinicalCase.rushPriority==='rush'),history:[history],createdAt:now(),updatedAt:now()};workItems.push(item);return res.status(201).json(item)});
app.put('/api/production/work-items/:id/assignment',(req,res)=>{const item=workItems.find(x=>x.id===req.params.id);if(!item)return res.status(404).json({error:'Work item not found.'});const technicianId=text(req.body.technicianId);const technician=technicians.find(x=>x.id===technicianId&&x.departments.includes(item.currentDepartment));if(!technician)return res.status(400).json({error:'Technician is not eligible for this department.'});item.technicianId=technician.id;item.updatedAt=now();return res.json(item)});
app.post('/api/production/work-items/:id/transitions',(req,res)=>{const item=workItems.find(x=>x.id===req.params.id);if(!item)return res.status(404).json({error:'Work item not found.'});const body=req.body as ProductionTransitionInput;if(!item.route.includes(body.toDepartment))return res.status(400).json({error:'Department is not in the configured route.'});const currentIndex=item.route.indexOf(item.currentDepartment),targetIndex=item.route.indexOf(body.toDepartment);if(body.status==='completed'&&body.toDepartment!=='shipping')return res.status(400).json({error:'Only Shipping can complete production.'});if(targetIndex<currentIndex||targetIndex>currentIndex+1)return res.status(400).json({error:'Transitions must follow the configured route.'});const from=item.currentDepartment;item.currentDepartment=body.toDepartment;item.status=body.status;item.technicianId=body.technicianId||null;if(!item.startedAt&&body.status==='in-progress')item.startedAt=now();if(body.status==='completed')item.completedAt=now();item.slaDueAt=slaFor(body.toDepartment,cases.find(x=>x.id===item.caseId)?.rushPriority==='rush');const history:ProductionHistoryEntry={id:randomUUID(),workItemId:item.id,fromDepartment:from,toDepartment:body.toDepartment,status:body.status,technicianId:item.technicianId,note:text(body.note),occurredAt:now(),actorId:text(body.actorId),actorName:text(body.actorName)};item.history.unshift(history);item.updatedAt=now();return res.json(item)});
app.get('/api/production/workload',(_req,res)=>res.json(workload()));

app.listen(port,()=>console.log(`CADence NorthStar API listening on http://localhost:${port}`));
