import type { MeshData } from './core';
import { buildTopology, faceNormal, indexedMesh, inspectGeometry } from './editing-geometry';
import { dot3 } from './geometry';
import { CROWN_MATERIAL_PROFILES } from './morphology-core';
import { analyzeSelfIntersections } from './editing-geometry';
import { CROWN_QC_RULESET_VERSION, type CrownQcCheck, type CrownQcResult, type CrownRoundTripResult, type RestorationRecord } from './restoration-types';

function check(id: string, status: CrownQcCheck['status'], measuredValue: CrownQcCheck['measuredValue'], threshold: string, affectedElementIds: string[], explanation: string, hardFailure: boolean): CrownQcCheck {
  return { id, status, measuredValue, threshold, affectedElementIds, explanation, hardFailure };
}

function hard(id: string, passed: boolean, measuredValue: CrownQcCheck['measuredValue'], threshold: string, affected: string[], pass: string, fail: string): CrownQcCheck {
  return check(id, passed ? 'pass' : 'fail', measuredValue, threshold, affected, passed ? pass : fail, true);
}

export function runCrownQc(restoration: RestorationRecord, mesh: MeshData, roundTrips: CrownRoundTripResult[] = []): CrownQcResult {
  if (!restoration.topologyMap) throw new Error('Crown QC requires a restoration topology map.');
  const indexed = indexedMesh(mesh); const topology = buildTopology(indexed); const inspection = inspectGeometry(indexed); const material = CROWN_MATERIAL_PROFILES[restoration.materialProfileId];
  const selfIntersections = analyzeSelfIntersections(indexed);
  const inconsistentEdges = topology.edgeFaces.flatMap((faces, edgeId) => {
    if (faces.length !== 2) return [];
    const [first, second] = faces; const firstFace = indexed.faces[first]; const secondFace = indexed.faces[second]; const edge = topology.edges[edgeId];
    const direction = (face: typeof firstFace) => { const a = face.indexOf(edge[0]); const b = face.indexOf(edge[1]); return (a + 1) % 3 === b ? 1 : -1; };
    return direction(firstFace) === direction(secondFace) ? [edgeId] : [];
  });
  const sharpEdges = topology.edgeFaces.flatMap((faces, edgeId) => {
    if (faces.length !== 2) return [];
    const angle = Math.acos(Math.max(-1, Math.min(1, dot3(faceNormal(indexed, indexed.faces[faces[0]]), faceNormal(indexed, indexed.faces[faces[1]]))))) * 180 / Math.PI;
    return angle > material.maximumSharpProjectionDegrees ? [edgeId] : [];
  });
  const marginCount = restoration.topologyMap.marginOuterVertexIds.length; const innerMarginCount = restoration.topologyMap.marginInnerVertexIds.length;
  const thicknessFailures = restoration.thickness?.failingVertexIds ?? [];
  const dimensions = inspection.boundingDimensionsMm;
  const unsupportedProjectionEdges = sharpEdges.filter((edgeId) => topology.edgeFaces[edgeId]?.some((faceId) => indexed.faces[faceId].some((vertexId) => restoration.thickness?.failingVertexIds.includes(vertexId))));
  const toolingRequired = material.minimumMillingToolDiameterMm !== null;
  const toolAccessSatisfied = !toolingRequired || (restoration.parameters.internalRadiusMm >= material.minimumInternalRadiusMm && restoration.parameters.millingToolDiameterMm >= (material.minimumMillingToolDiameterMm ?? 0) && restoration.parameters.toolAccessAllowanceMm >= material.toolAccessAllowanceMm);
  const checks: CrownQcCheck[] = [
    hard('margin-integrity', marginCount >= 24 && marginCount === innerMarginCount, `outer=${marginCount}; inner=${innerMarginCount}`, 'matching closed outer and intaglio margin rings with at least 24 samples', [], 'The margin boundary is complete and paired.', 'The restoration margin boundary is incomplete or unpaired.'),
    hard('margin-adaptation', Boolean(restoration.cementSpace && restoration.cementSpace.measuredMinimumMm >= material.marginalGapMm.minimum - 1e-4), restoration.cementSpace?.measuredMinimumMm ?? null, `>= ${material.marginalGapMm.minimum} mm`, restoration.cementSpace?.invalidSampleVertexIds.map(String) ?? [], 'Measured marginal adaptation meets the material rule.', 'Measured marginal adaptation is below the governed material rule.'),
    hard('intaglio-integrity', restoration.topologyMap.innerVertexIds.length > marginCount, restoration.topologyMap.innerVertexIds.length, 'complete inner surface with occlusal/incisal closure', [], 'The intaglio is present and topologically mapped.', 'The restoration does not contain a usable intaglio.'),
    hard('seating-path', restoration.seating?.status === 'pass', restoration.seating?.seated ?? false, 'collision-free insertion to full seat', restoration.seating?.blockingVertexIds.map(String) ?? [], 'Insertion simulation reaches full seat without collisions.', 'Insertion simulation found a blocked or impossible seating path.'),
    hard('internal-collision', (restoration.seating?.maximumPenetrationMm ?? Infinity) <= 1e-5, restoration.seating?.maximumPenetrationMm ?? null, '<= 0.00001 mm sampled penetration', restoration.seating?.blockingVertexIds.map(String) ?? [], 'No sampled internal collision was detected.', 'Internal collision was detected.'),
    hard('cement-space-validity', restoration.cementSpace?.status === 'pass', restoration.cementSpace?.measuredMeanMm ?? null, `${material.cementGapMm.minimum}–${material.cementGapMm.maximum} mm governed space`, restoration.cementSpace?.invalidSampleVertexIds.map(String) ?? [], 'Cement-space samples satisfy the governed profile.', 'Cement-space samples are invalid or out of range.'),
    hard('minimum-thickness', Boolean(restoration.thickness && !thicknessFailures.length), restoration.thickness?.globalMinimumMm ?? null, `regional minima from ${material.id}@${material.version}`, thicknessFailures.map(String), 'All sampled wall thicknesses satisfy regional material minima.', 'One or more wall-thickness samples fail the material profile.'),
    hard('mesial-contact', restoration.mesialContact?.status === 'pass', restoration.mesialContact?.minimumDistanceMm ?? null, `${material.contactDistanceMm.minimum}–${material.contactDistanceMm.maximum} mm`, restoration.mesialContact?.distanceSamples.filter((sample) => sample.distanceMm < material.contactDistanceMm.minimum).map((sample) => String(sample.vertexId)) ?? [], 'Mesial contact satisfies the governed static-distance range.', 'Mesial contact is missing or outside the governed static-distance range.'),
    hard('distal-contact', restoration.distalContact?.status === 'pass', restoration.distalContact?.minimumDistanceMm ?? null, `${material.contactDistanceMm.minimum}–${material.contactDistanceMm.maximum} mm`, restoration.distalContact?.distanceSamples.filter((sample) => sample.distanceMm < material.contactDistanceMm.minimum).map((sample) => String(sample.vertexId)) ?? [], 'Distal contact satisfies the governed static-distance range.', 'Distal contact is missing or outside the governed static-distance range.'),
    hard('static-occlusion', restoration.occlusion?.status === 'pass', restoration.occlusion?.minimumDistanceMm ?? null, `${material.occlusalClearanceMm.minimum}–${material.occlusalClearanceMm.maximum} mm static clearance`, restoration.occlusion?.distanceSamples.filter((sample) => sample.distanceMm < material.occlusalClearanceMm.minimum).map((sample) => String(sample.vertexId)) ?? [], 'Static antagonist clearance satisfies the material target range.', 'Static occlusion is missing or outside the governed clearance range.'),
    hard('clearance', restoration.mesialContact?.status === 'pass' && restoration.distalContact?.status === 'pass' && restoration.occlusion?.status === 'pass', `mesial=${restoration.mesialContact?.minimumDistanceMm ?? 'not-run'}; distal=${restoration.distalContact?.minimumDistanceMm ?? 'not-run'}; occlusal=${restoration.occlusion?.minimumDistanceMm ?? 'not-run'}`, `proximal ${material.contactDistanceMm.minimum}–${material.contactDistanceMm.maximum} mm; occlusal ${material.occlusalClearanceMm.minimum}–${material.occlusalClearanceMm.maximum} mm`, [], 'All assigned proximal and antagonist surfaces have governed measured clearance.', 'At least one required proximal or antagonist clearance is missing or outside its governed range.'),
    hard('excessive-penetration', Math.max(restoration.mesialContact?.penetrationMm ?? Infinity, restoration.distalContact?.penetrationMm ?? Infinity, restoration.occlusion?.maximumPenetrationMm ?? Infinity) <= Math.max(0.05, Math.abs(material.contactDistanceMm.minimum)), Math.max(restoration.mesialContact?.penetrationMm ?? Infinity, restoration.distalContact?.penetrationMm ?? Infinity, restoration.occlusion?.maximumPenetrationMm ?? Infinity), `<= ${Math.max(0.05, Math.abs(material.contactDistanceMm.minimum))} mm`, [], 'No excessive proximal or occlusal penetration was measured.', 'Excessive proximal or occlusal penetration was measured.'),
    check('over-contour', restoration.contour?.status ?? 'not-run', restoration.contour?.maximumOverContourMm ?? null, '<= 0.5 mm from assigned references', restoration.contour?.overContouredVertexIds.map(String) ?? [], restoration.contour?.status === 'warning' && (restoration.contour?.overContouredVertexIds.length ?? 0) ? 'Reference comparison found excess crown contour for technician review.' : restoration.contour?.status === 'pass' ? 'No over-contour outside tolerance was measured.' : 'No usable reference surface was assigned for over-contour analysis.', false),
    check('under-contour', restoration.contour?.status ?? 'not-run', restoration.contour?.maximumUnderContourMm ?? null, '<= 0.5 mm from assigned references', restoration.contour?.underContouredVertexIds.map(String) ?? [], restoration.contour?.status === 'warning' && (restoration.contour?.underContouredVertexIds.length ?? 0) ? 'Reference comparison found deficient crown contour for technician review.' : restoration.contour?.status === 'pass' ? 'No under-contour outside tolerance was measured.' : 'No usable reference surface was assigned for under-contour analysis.', false),
    check('sharp-projections', sharpEdges.length ? 'warning' : 'pass', sharpEdges.length, `dihedral <= ${material.maximumSharpProjectionDegrees}°`, sharpEdges.map(String), sharpEdges.length ? 'Sharp surface transitions require technician review.' : 'No governed sharp-projection candidate was detected.', false),
    hard('unsupported-thin-projections', unsupportedProjectionEdges.length === 0, unsupportedProjectionEdges.length, '0 sharp edges incident to minimum-thickness failures', unsupportedProjectionEdges.map(String), 'No unsupported thin projection was detected.', 'One or more sharp projections are incident to material-thickness failures.'),
    hard('self-intersection', selfIntersections.length === 0, selfIntersections.length, '0 invalid triangle intersections', selfIntersections.map((item) => `${item.triangleIds[0]}-${item.triangleIds[1]}`), 'No self-intersection was detected.', 'Self-intersecting crown geometry was detected.'),
    hard('manifold-topology', topology.nonManifoldEdges.length === 0, topology.nonManifoldEdges.length, '0 non-manifold edges', topology.nonManifoldEdges.map(String), 'The crown is two-manifold.', 'Non-manifold crown edges were detected.'),
    hard('watertightness', inspection.watertight, inspection.watertight, 'true', topology.boundaryEdges.map(String), 'The crown is watertight.', 'The crown contains open boundaries or invalid topology.'),
    hard('normals', inconsistentEdges.length === 0 && (inspection.volumeMm3 ?? 0) > 0, inconsistentEdges.length, 'consistent winding and positive closed volume', inconsistentEdges.map(String), 'Crown face winding and closed volume are consistent.', 'Inconsistent winding or invalid closed volume was detected.'),
    hard('single-shell', inspection.shellCount === 1, inspection.shellCount, '1 connected restoration shell', [], 'The crown is one connected restoration shell.', 'The crown contains disconnected components.'),
    hard('geometry-dimensions', dimensions.every((value) => Number.isFinite(value) && value > 0), dimensions.map((value) => Number(value.toFixed(4))).join(' × '), 'three finite positive millimeter dimensions', [], 'Restoration bounding dimensions are finite and positive.', 'Restoration bounding dimensions are invalid.'),
    hard('material-profile-compliance', Boolean(restoration.thickness && restoration.cementSpace && restoration.materialProfileId === material.id), `${material.id}@${material.version}`, 'governed material profile applied to thickness and cement space', [], 'The governed material profile is attached to measured crown geometry.', 'Material rules were not fully applied to measured geometry.'),
    hard('manufacturing-accessibility', toolAccessSatisfied, toolingRequired ? `tool=${restoration.parameters.millingToolDiameterMm} mm; radius=${restoration.parameters.internalRadiusMm} mm; allowance=${restoration.parameters.toolAccessAllowanceMm} mm` : `not-applicable for ${material.compatibility.manufacturingModes.join('/')}`, toolingRequired ? `tool >= ${material.minimumMillingToolDiameterMm} mm; radius >= ${material.minimumInternalRadiusMm} mm; allowance >= ${material.toolAccessAllowanceMm} mm` : 'explicitly not applicable to the configured non-milling manufacturing path', [], 'Configured manufacturing-accessibility rules are satisfied or explicitly not applicable.', 'Configured milling tool cannot access the requested internal geometry.'),
    hard('export-integrity', roundTrips.length > 0 && roundTrips.every((result) => result.passed), roundTrips.length ? roundTrips.filter((result) => result.passed).length : 0, 'all generated formats pass automatic re-import comparison', roundTrips.filter((result) => !result.passed).map((result) => result.format), 'Every generated export passed round-trip validation.', 'No export validation is present or at least one format failed round-trip validation.'),
  ];
  const failureCount = checks.filter((item) => item.status === 'fail').length; const warningCount = checks.filter((item) => item.status === 'warning').length; const hardFailureCount = checks.filter((item) => item.status === 'fail' && item.hardFailure).length;
  return { id: crypto.randomUUID(), restorationId: restoration.id, rulesetVersion: CROWN_QC_RULESET_VERSION, materialProfileId: restoration.materialProfileId, checks, overall: failureCount ? 'fail' : warningCount ? 'warning' : 'pass', warningCount, failureCount, hardFailureCount, executedAt: new Date().toISOString() };
}
